// Code generated by ent, DO NOT EDIT.

package sysdictitem

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/teamsillybees/initra/examples/internal/data/ent/predicate"
	"github.com/teamsillybees/initra/pkg/idgen"
)

// ID filters vertices based on their ID field.
func ID(id idgen.ID) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id idgen.ID) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id idgen.ID) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...idgen.ID) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...idgen.ID) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id idgen.ID) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id idgen.ID) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id idgen.ID) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id idgen.ID) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldLTE(FieldID, id))
}

// CollectionID applies equality check predicate on the "collection_id" field. It's identical to CollectionIDEQ.
func CollectionID(v idgen.ID) predicate.SysDictItem {
	vc := int64(v)
	return predicate.SysDictItem(sql.FieldEQ(FieldCollectionID, vc))
}

// CollectionCode applies equality check predicate on the "collection_code" field. It's identical to CollectionCodeEQ.
func CollectionCode(v string) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldEQ(FieldCollectionCode, v))
}

// Code applies equality check predicate on the "code" field. It's identical to CodeEQ.
func Code(v string) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldEQ(FieldCode, v))
}

// ParentCode applies equality check predicate on the "parent_code" field. It's identical to ParentCodeEQ.
func ParentCode(v string) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldEQ(FieldParentCode, v))
}

// IsDefaultValue applies equality check predicate on the "is_default_value" field. It's identical to IsDefaultValueEQ.
func IsDefaultValue(v bool) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldEQ(FieldIsDefaultValue, v))
}

// IsEnable applies equality check predicate on the "is_enable" field. It's identical to IsEnableEQ.
func IsEnable(v bool) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldEQ(FieldIsEnable, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldEQ(FieldDescription, v))
}

// SortID applies equality check predicate on the "sort_id" field. It's identical to SortIDEQ.
func SortID(v int32) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldEQ(FieldSortID, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldEQ(FieldDeletedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldEQ(FieldUpdatedAt, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v idgen.ID) predicate.SysDictItem {
	vc := int64(v)
	return predicate.SysDictItem(sql.FieldEQ(FieldCreatedBy, vc))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v idgen.ID) predicate.SysDictItem {
	vc := int64(v)
	return predicate.SysDictItem(sql.FieldEQ(FieldUpdatedBy, vc))
}

// CollectionIDEQ applies the EQ predicate on the "collection_id" field.
func CollectionIDEQ(v idgen.ID) predicate.SysDictItem {
	vc := int64(v)
	return predicate.SysDictItem(sql.FieldEQ(FieldCollectionID, vc))
}

// CollectionIDNEQ applies the NEQ predicate on the "collection_id" field.
func CollectionIDNEQ(v idgen.ID) predicate.SysDictItem {
	vc := int64(v)
	return predicate.SysDictItem(sql.FieldNEQ(FieldCollectionID, vc))
}

// CollectionIDIn applies the In predicate on the "collection_id" field.
func CollectionIDIn(vs ...idgen.ID) predicate.SysDictItem {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = int64(vs[i])
	}
	return predicate.SysDictItem(sql.FieldIn(FieldCollectionID, v...))
}

// CollectionIDNotIn applies the NotIn predicate on the "collection_id" field.
func CollectionIDNotIn(vs ...idgen.ID) predicate.SysDictItem {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = int64(vs[i])
	}
	return predicate.SysDictItem(sql.FieldNotIn(FieldCollectionID, v...))
}

// CollectionCodeEQ applies the EQ predicate on the "collection_code" field.
func CollectionCodeEQ(v string) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldEQ(FieldCollectionCode, v))
}

// CollectionCodeNEQ applies the NEQ predicate on the "collection_code" field.
func CollectionCodeNEQ(v string) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldNEQ(FieldCollectionCode, v))
}

// CollectionCodeIn applies the In predicate on the "collection_code" field.
func CollectionCodeIn(vs ...string) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldIn(FieldCollectionCode, vs...))
}

// CollectionCodeNotIn applies the NotIn predicate on the "collection_code" field.
func CollectionCodeNotIn(vs ...string) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldNotIn(FieldCollectionCode, vs...))
}

// CollectionCodeGT applies the GT predicate on the "collection_code" field.
func CollectionCodeGT(v string) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldGT(FieldCollectionCode, v))
}

// CollectionCodeGTE applies the GTE predicate on the "collection_code" field.
func CollectionCodeGTE(v string) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldGTE(FieldCollectionCode, v))
}

// CollectionCodeLT applies the LT predicate on the "collection_code" field.
func CollectionCodeLT(v string) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldLT(FieldCollectionCode, v))
}

// CollectionCodeLTE applies the LTE predicate on the "collection_code" field.
func CollectionCodeLTE(v string) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldLTE(FieldCollectionCode, v))
}

// CollectionCodeContains applies the Contains predicate on the "collection_code" field.
func CollectionCodeContains(v string) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldContains(FieldCollectionCode, v))
}

// CollectionCodeHasPrefix applies the HasPrefix predicate on the "collection_code" field.
func CollectionCodeHasPrefix(v string) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldHasPrefix(FieldCollectionCode, v))
}

// CollectionCodeHasSuffix applies the HasSuffix predicate on the "collection_code" field.
func CollectionCodeHasSuffix(v string) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldHasSuffix(FieldCollectionCode, v))
}

// CollectionCodeEqualFold applies the EqualFold predicate on the "collection_code" field.
func CollectionCodeEqualFold(v string) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldEqualFold(FieldCollectionCode, v))
}

// CollectionCodeContainsFold applies the ContainsFold predicate on the "collection_code" field.
func CollectionCodeContainsFold(v string) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldContainsFold(FieldCollectionCode, v))
}

// CodeEQ applies the EQ predicate on the "code" field.
func CodeEQ(v string) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldEQ(FieldCode, v))
}

// CodeNEQ applies the NEQ predicate on the "code" field.
func CodeNEQ(v string) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldNEQ(FieldCode, v))
}

// CodeIn applies the In predicate on the "code" field.
func CodeIn(vs ...string) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldIn(FieldCode, vs...))
}

// CodeNotIn applies the NotIn predicate on the "code" field.
func CodeNotIn(vs ...string) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldNotIn(FieldCode, vs...))
}

// CodeGT applies the GT predicate on the "code" field.
func CodeGT(v string) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldGT(FieldCode, v))
}

// CodeGTE applies the GTE predicate on the "code" field.
func CodeGTE(v string) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldGTE(FieldCode, v))
}

// CodeLT applies the LT predicate on the "code" field.
func CodeLT(v string) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldLT(FieldCode, v))
}

// CodeLTE applies the LTE predicate on the "code" field.
func CodeLTE(v string) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldLTE(FieldCode, v))
}

// CodeContains applies the Contains predicate on the "code" field.
func CodeContains(v string) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldContains(FieldCode, v))
}

// CodeHasPrefix applies the HasPrefix predicate on the "code" field.
func CodeHasPrefix(v string) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldHasPrefix(FieldCode, v))
}

// CodeHasSuffix applies the HasSuffix predicate on the "code" field.
func CodeHasSuffix(v string) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldHasSuffix(FieldCode, v))
}

// CodeEqualFold applies the EqualFold predicate on the "code" field.
func CodeEqualFold(v string) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldEqualFold(FieldCode, v))
}

// CodeContainsFold applies the ContainsFold predicate on the "code" field.
func CodeContainsFold(v string) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldContainsFold(FieldCode, v))
}

// ParentCodeEQ applies the EQ predicate on the "parent_code" field.
func ParentCodeEQ(v string) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldEQ(FieldParentCode, v))
}

// ParentCodeNEQ applies the NEQ predicate on the "parent_code" field.
func ParentCodeNEQ(v string) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldNEQ(FieldParentCode, v))
}

// ParentCodeIn applies the In predicate on the "parent_code" field.
func ParentCodeIn(vs ...string) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldIn(FieldParentCode, vs...))
}

// ParentCodeNotIn applies the NotIn predicate on the "parent_code" field.
func ParentCodeNotIn(vs ...string) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldNotIn(FieldParentCode, vs...))
}

// ParentCodeGT applies the GT predicate on the "parent_code" field.
func ParentCodeGT(v string) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldGT(FieldParentCode, v))
}

// ParentCodeGTE applies the GTE predicate on the "parent_code" field.
func ParentCodeGTE(v string) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldGTE(FieldParentCode, v))
}

// ParentCodeLT applies the LT predicate on the "parent_code" field.
func ParentCodeLT(v string) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldLT(FieldParentCode, v))
}

// ParentCodeLTE applies the LTE predicate on the "parent_code" field.
func ParentCodeLTE(v string) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldLTE(FieldParentCode, v))
}

// ParentCodeContains applies the Contains predicate on the "parent_code" field.
func ParentCodeContains(v string) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldContains(FieldParentCode, v))
}

// ParentCodeHasPrefix applies the HasPrefix predicate on the "parent_code" field.
func ParentCodeHasPrefix(v string) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldHasPrefix(FieldParentCode, v))
}

// ParentCodeHasSuffix applies the HasSuffix predicate on the "parent_code" field.
func ParentCodeHasSuffix(v string) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldHasSuffix(FieldParentCode, v))
}

// ParentCodeEqualFold applies the EqualFold predicate on the "parent_code" field.
func ParentCodeEqualFold(v string) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldEqualFold(FieldParentCode, v))
}

// ParentCodeContainsFold applies the ContainsFold predicate on the "parent_code" field.
func ParentCodeContainsFold(v string) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldContainsFold(FieldParentCode, v))
}

// LabelEQ applies the EQ predicate on the "label" field.
func LabelEQ(v string) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldEQ(FieldLabel, v))
}

// LabelNEQ applies the NEQ predicate on the "label" field.
func LabelNEQ(v string) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldNEQ(FieldLabel, v))
}

// LabelIn applies the In predicate on the "label" field.
func LabelIn(vs ...string) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldIn(FieldLabel, vs...))
}

// LabelNotIn applies the NotIn predicate on the "label" field.
func LabelNotIn(vs ...string) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldNotIn(FieldLabel, vs...))
}

// LabelGT applies the GT predicate on the "label" field.
func LabelGT(v string) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldGT(FieldLabel, v))
}

// LabelGTE applies the GTE predicate on the "label" field.
func LabelGTE(v string) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldGTE(FieldLabel, v))
}

// LabelLT applies the LT predicate on the "label" field.
func LabelLT(v string) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldLT(FieldLabel, v))
}

// LabelLTE applies the LTE predicate on the "label" field.
func LabelLTE(v string) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldLTE(FieldLabel, v))
}

// LabelContains applies the Contains predicate on the "label" field.
func LabelContains(v string) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldContains(FieldLabel, v))
}

// LabelHasPrefix applies the HasPrefix predicate on the "label" field.
func LabelHasPrefix(v string) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldHasPrefix(FieldLabel, v))
}

// LabelHasSuffix applies the HasSuffix predicate on the "label" field.
func LabelHasSuffix(v string) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldHasSuffix(FieldLabel, v))
}

// LabelEqualFold applies the EqualFold predicate on the "label" field.
func LabelEqualFold(v string) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldEqualFold(FieldLabel, v))
}

// LabelContainsFold applies the ContainsFold predicate on the "label" field.
func LabelContainsFold(v string) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldContainsFold(FieldLabel, v))
}

// IsDefaultValueEQ applies the EQ predicate on the "is_default_value" field.
func IsDefaultValueEQ(v bool) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldEQ(FieldIsDefaultValue, v))
}

// IsDefaultValueNEQ applies the NEQ predicate on the "is_default_value" field.
func IsDefaultValueNEQ(v bool) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldNEQ(FieldIsDefaultValue, v))
}

// IsEnableEQ applies the EQ predicate on the "is_enable" field.
func IsEnableEQ(v bool) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldEQ(FieldIsEnable, v))
}

// IsEnableNEQ applies the NEQ predicate on the "is_enable" field.
func IsEnableNEQ(v bool) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldNEQ(FieldIsEnable, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldContainsFold(FieldDescription, v))
}

// SortIDEQ applies the EQ predicate on the "sort_id" field.
func SortIDEQ(v int32) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldEQ(FieldSortID, v))
}

// SortIDNEQ applies the NEQ predicate on the "sort_id" field.
func SortIDNEQ(v int32) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldNEQ(FieldSortID, v))
}

// SortIDIn applies the In predicate on the "sort_id" field.
func SortIDIn(vs ...int32) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldIn(FieldSortID, vs...))
}

// SortIDNotIn applies the NotIn predicate on the "sort_id" field.
func SortIDNotIn(vs ...int32) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldNotIn(FieldSortID, vs...))
}

// SortIDGT applies the GT predicate on the "sort_id" field.
func SortIDGT(v int32) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldGT(FieldSortID, v))
}

// SortIDGTE applies the GTE predicate on the "sort_id" field.
func SortIDGTE(v int32) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldGTE(FieldSortID, v))
}

// SortIDLT applies the LT predicate on the "sort_id" field.
func SortIDLT(v int32) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldLT(FieldSortID, v))
}

// SortIDLTE applies the LTE predicate on the "sort_id" field.
func SortIDLTE(v int32) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldLTE(FieldSortID, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldNotNull(FieldDeletedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldLTE(FieldUpdatedAt, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v idgen.ID) predicate.SysDictItem {
	vc := int64(v)
	return predicate.SysDictItem(sql.FieldEQ(FieldCreatedBy, vc))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v idgen.ID) predicate.SysDictItem {
	vc := int64(v)
	return predicate.SysDictItem(sql.FieldNEQ(FieldCreatedBy, vc))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...idgen.ID) predicate.SysDictItem {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = int64(vs[i])
	}
	return predicate.SysDictItem(sql.FieldIn(FieldCreatedBy, v...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...idgen.ID) predicate.SysDictItem {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = int64(vs[i])
	}
	return predicate.SysDictItem(sql.FieldNotIn(FieldCreatedBy, v...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v idgen.ID) predicate.SysDictItem {
	vc := int64(v)
	return predicate.SysDictItem(sql.FieldGT(FieldCreatedBy, vc))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v idgen.ID) predicate.SysDictItem {
	vc := int64(v)
	return predicate.SysDictItem(sql.FieldGTE(FieldCreatedBy, vc))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v idgen.ID) predicate.SysDictItem {
	vc := int64(v)
	return predicate.SysDictItem(sql.FieldLT(FieldCreatedBy, vc))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v idgen.ID) predicate.SysDictItem {
	vc := int64(v)
	return predicate.SysDictItem(sql.FieldLTE(FieldCreatedBy, vc))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldNotNull(FieldCreatedBy))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v idgen.ID) predicate.SysDictItem {
	vc := int64(v)
	return predicate.SysDictItem(sql.FieldEQ(FieldUpdatedBy, vc))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v idgen.ID) predicate.SysDictItem {
	vc := int64(v)
	return predicate.SysDictItem(sql.FieldNEQ(FieldUpdatedBy, vc))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...idgen.ID) predicate.SysDictItem {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = int64(vs[i])
	}
	return predicate.SysDictItem(sql.FieldIn(FieldUpdatedBy, v...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...idgen.ID) predicate.SysDictItem {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = int64(vs[i])
	}
	return predicate.SysDictItem(sql.FieldNotIn(FieldUpdatedBy, v...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v idgen.ID) predicate.SysDictItem {
	vc := int64(v)
	return predicate.SysDictItem(sql.FieldGT(FieldUpdatedBy, vc))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v idgen.ID) predicate.SysDictItem {
	vc := int64(v)
	return predicate.SysDictItem(sql.FieldGTE(FieldUpdatedBy, vc))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v idgen.ID) predicate.SysDictItem {
	vc := int64(v)
	return predicate.SysDictItem(sql.FieldLT(FieldUpdatedBy, vc))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v idgen.ID) predicate.SysDictItem {
	vc := int64(v)
	return predicate.SysDictItem(sql.FieldLTE(FieldUpdatedBy, vc))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.SysDictItem {
	return predicate.SysDictItem(sql.FieldNotNull(FieldUpdatedBy))
}

// HasCollection applies the HasEdge predicate on the "collection" edge.
func HasCollection() predicate.SysDictItem {
	return predicate.SysDictItem(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, CollectionTable, CollectionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCollectionWith applies the HasEdge predicate on the "collection" edge with a given conditions (other predicates).
func HasCollectionWith(preds ...predicate.SysDictCollection) predicate.SysDictItem {
	return predicate.SysDictItem(func(s *sql.Selector) {
		step := newCollectionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SysDictItem) predicate.SysDictItem {
	return predicate.SysDictItem(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SysDictItem) predicate.SysDictItem {
	return predicate.SysDictItem(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SysDictItem) predicate.SysDictItem {
	return predicate.SysDictItem(sql.NotPredicates(p))
}
