// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/teamsillybees/initra/examples/api/internal/ent/predicate"
	"github.com/teamsillybees/initra/examples/api/internal/ent/sysuser"
	"github.com/teamsillybees/initra/examples/api/internal/ent/sysuserrole"
)

// SysUserUpdate is the builder for updating SysUser entities.
type SysUserUpdate struct {
	config
	hooks    []Hook
	mutation *SysUserMutation
}

// Where appends a list predicates to the SysUserUpdate builder.
func (_u *SysUserUpdate) Where(ps ...predicate.SysUser) *SysUserUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *SysUserUpdate) SetDeletedAt(v time.Time) *SysUserUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *SysUserUpdate) SetNillableDeletedAt(v *time.Time) *SysUserUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *SysUserUpdate) ClearDeletedAt() *SysUserUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SysUserUpdate) SetUpdatedAt(v time.Time) *SysUserUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *SysUserUpdate) SetNillableUpdatedAt(v *time.Time) *SysUserUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *SysUserUpdate) SetCreatedBy(v int64) *SysUserUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *SysUserUpdate) SetNillableCreatedBy(v *int64) *SysUserUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *SysUserUpdate) AddCreatedBy(v int64) *SysUserUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *SysUserUpdate) ClearCreatedBy() *SysUserUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *SysUserUpdate) SetUpdatedBy(v int64) *SysUserUpdate {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *SysUserUpdate) SetNillableUpdatedBy(v *int64) *SysUserUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *SysUserUpdate) AddUpdatedBy(v int64) *SysUserUpdate {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *SysUserUpdate) ClearUpdatedBy() *SysUserUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetUsername sets the "username" field.
func (_u *SysUserUpdate) SetUsername(v string) *SysUserUpdate {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *SysUserUpdate) SetNillableUsername(v *string) *SysUserUpdate {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetPasswordHash sets the "password_hash" field.
func (_u *SysUserUpdate) SetPasswordHash(v string) *SysUserUpdate {
	_u.mutation.SetPasswordHash(v)
	return _u
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (_u *SysUserUpdate) SetNillablePasswordHash(v *string) *SysUserUpdate {
	if v != nil {
		_u.SetPasswordHash(*v)
	}
	return _u
}

// SetNickname sets the "nickname" field.
func (_u *SysUserUpdate) SetNickname(v string) *SysUserUpdate {
	_u.mutation.SetNickname(v)
	return _u
}

// SetNillableNickname sets the "nickname" field if the given value is not nil.
func (_u *SysUserUpdate) SetNillableNickname(v *string) *SysUserUpdate {
	if v != nil {
		_u.SetNickname(*v)
	}
	return _u
}

// ClearNickname clears the value of the "nickname" field.
func (_u *SysUserUpdate) ClearNickname() *SysUserUpdate {
	_u.mutation.ClearNickname()
	return _u
}

// SetPhone sets the "phone" field.
func (_u *SysUserUpdate) SetPhone(v string) *SysUserUpdate {
	_u.mutation.SetPhone(v)
	return _u
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_u *SysUserUpdate) SetNillablePhone(v *string) *SysUserUpdate {
	if v != nil {
		_u.SetPhone(*v)
	}
	return _u
}

// ClearPhone clears the value of the "phone" field.
func (_u *SysUserUpdate) ClearPhone() *SysUserUpdate {
	_u.mutation.ClearPhone()
	return _u
}

// SetEmail sets the "email" field.
func (_u *SysUserUpdate) SetEmail(v string) *SysUserUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *SysUserUpdate) SetNillableEmail(v *string) *SysUserUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// ClearEmail clears the value of the "email" field.
func (_u *SysUserUpdate) ClearEmail() *SysUserUpdate {
	_u.mutation.ClearEmail()
	return _u
}

// SetAvatarURL sets the "avatar_url" field.
func (_u *SysUserUpdate) SetAvatarURL(v string) *SysUserUpdate {
	_u.mutation.SetAvatarURL(v)
	return _u
}

// SetNillableAvatarURL sets the "avatar_url" field if the given value is not nil.
func (_u *SysUserUpdate) SetNillableAvatarURL(v *string) *SysUserUpdate {
	if v != nil {
		_u.SetAvatarURL(*v)
	}
	return _u
}

// ClearAvatarURL clears the value of the "avatar_url" field.
func (_u *SysUserUpdate) ClearAvatarURL() *SysUserUpdate {
	_u.mutation.ClearAvatarURL()
	return _u
}

// SetIsSuperAdmin sets the "is_super_admin" field.
func (_u *SysUserUpdate) SetIsSuperAdmin(v bool) *SysUserUpdate {
	_u.mutation.SetIsSuperAdmin(v)
	return _u
}

// SetNillableIsSuperAdmin sets the "is_super_admin" field if the given value is not nil.
func (_u *SysUserUpdate) SetNillableIsSuperAdmin(v *bool) *SysUserUpdate {
	if v != nil {
		_u.SetIsSuperAdmin(*v)
	}
	return _u
}

// SetIsEnable sets the "is_enable" field.
func (_u *SysUserUpdate) SetIsEnable(v bool) *SysUserUpdate {
	_u.mutation.SetIsEnable(v)
	return _u
}

// SetNillableIsEnable sets the "is_enable" field if the given value is not nil.
func (_u *SysUserUpdate) SetNillableIsEnable(v *bool) *SysUserUpdate {
	if v != nil {
		_u.SetIsEnable(*v)
	}
	return _u
}

// SetSortID sets the "sort_id" field.
func (_u *SysUserUpdate) SetSortID(v int) *SysUserUpdate {
	_u.mutation.ResetSortID()
	_u.mutation.SetSortID(v)
	return _u
}

// SetNillableSortID sets the "sort_id" field if the given value is not nil.
func (_u *SysUserUpdate) SetNillableSortID(v *int) *SysUserUpdate {
	if v != nil {
		_u.SetSortID(*v)
	}
	return _u
}

// AddSortID adds value to the "sort_id" field.
func (_u *SysUserUpdate) AddSortID(v int) *SysUserUpdate {
	_u.mutation.AddSortID(v)
	return _u
}

// AddUserRoleIDs adds the "user_roles" edge to the SysUserRole entity by IDs.
func (_u *SysUserUpdate) AddUserRoleIDs(ids ...int64) *SysUserUpdate {
	_u.mutation.AddUserRoleIDs(ids...)
	return _u
}

// AddUserRoles adds the "user_roles" edges to the SysUserRole entity.
func (_u *SysUserUpdate) AddUserRoles(v ...*SysUserRole) *SysUserUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserRoleIDs(ids...)
}

// Mutation returns the SysUserMutation object of the builder.
func (_u *SysUserUpdate) Mutation() *SysUserMutation {
	return _u.mutation
}

// ClearUserRoles clears all "user_roles" edges to the SysUserRole entity.
func (_u *SysUserUpdate) ClearUserRoles() *SysUserUpdate {
	_u.mutation.ClearUserRoles()
	return _u
}

// RemoveUserRoleIDs removes the "user_roles" edge to SysUserRole entities by IDs.
func (_u *SysUserUpdate) RemoveUserRoleIDs(ids ...int64) *SysUserUpdate {
	_u.mutation.RemoveUserRoleIDs(ids...)
	return _u
}

// RemoveUserRoles removes "user_roles" edges to SysUserRole entities.
func (_u *SysUserUpdate) RemoveUserRoles(v ...*SysUserRole) *SysUserUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserRoleIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SysUserUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SysUserUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SysUserUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SysUserUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SysUserUpdate) check() error {
	if v, ok := _u.mutation.Username(); ok {
		if err := sysuser.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "SysUser.username": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PasswordHash(); ok {
		if err := sysuser.PasswordHashValidator(v); err != nil {
			return &ValidationError{Name: "password_hash", err: fmt.Errorf(`ent: validator failed for field "SysUser.password_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Nickname(); ok {
		if err := sysuser.NicknameValidator(v); err != nil {
			return &ValidationError{Name: "nickname", err: fmt.Errorf(`ent: validator failed for field "SysUser.nickname": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Phone(); ok {
		if err := sysuser.PhoneValidator(v); err != nil {
			return &ValidationError{Name: "phone", err: fmt.Errorf(`ent: validator failed for field "SysUser.phone": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Email(); ok {
		if err := sysuser.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "SysUser.email": %w`, err)}
		}
	}
	return nil
}

func (_u *SysUserUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sysuser.Table, sysuser.Columns, sqlgraph.NewFieldSpec(sysuser.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(sysuser.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(sysuser.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(sysuser.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(sysuser.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(sysuser.FieldCreatedBy, field.TypeInt64, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(sysuser.FieldCreatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(sysuser.FieldUpdatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(sysuser.FieldUpdatedBy, field.TypeInt64, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(sysuser.FieldUpdatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(sysuser.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.PasswordHash(); ok {
		_spec.SetField(sysuser.FieldPasswordHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Nickname(); ok {
		_spec.SetField(sysuser.FieldNickname, field.TypeString, value)
	}
	if _u.mutation.NicknameCleared() {
		_spec.ClearField(sysuser.FieldNickname, field.TypeString)
	}
	if value, ok := _u.mutation.Phone(); ok {
		_spec.SetField(sysuser.FieldPhone, field.TypeString, value)
	}
	if _u.mutation.PhoneCleared() {
		_spec.ClearField(sysuser.FieldPhone, field.TypeString)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(sysuser.FieldEmail, field.TypeString, value)
	}
	if _u.mutation.EmailCleared() {
		_spec.ClearField(sysuser.FieldEmail, field.TypeString)
	}
	if value, ok := _u.mutation.AvatarURL(); ok {
		_spec.SetField(sysuser.FieldAvatarURL, field.TypeString, value)
	}
	if _u.mutation.AvatarURLCleared() {
		_spec.ClearField(sysuser.FieldAvatarURL, field.TypeString)
	}
	if value, ok := _u.mutation.IsSuperAdmin(); ok {
		_spec.SetField(sysuser.FieldIsSuperAdmin, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsEnable(); ok {
		_spec.SetField(sysuser.FieldIsEnable, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SortID(); ok {
		_spec.SetField(sysuser.FieldSortID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortID(); ok {
		_spec.AddField(sysuser.FieldSortID, field.TypeInt, value)
	}
	if _u.mutation.UserRolesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sysuser.UserRolesTable,
			Columns: []string{sysuser.UserRolesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sysuserrole.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUserRolesIDs(); len(nodes) > 0 && !_u.mutation.UserRolesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sysuser.UserRolesTable,
			Columns: []string{sysuser.UserRolesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sysuserrole.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserRolesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sysuser.UserRolesTable,
			Columns: []string{sysuser.UserRolesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sysuserrole.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sysuser.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SysUserUpdateOne is the builder for updating a single SysUser entity.
type SysUserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SysUserMutation
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *SysUserUpdateOne) SetDeletedAt(v time.Time) *SysUserUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *SysUserUpdateOne) SetNillableDeletedAt(v *time.Time) *SysUserUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *SysUserUpdateOne) ClearDeletedAt() *SysUserUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SysUserUpdateOne) SetUpdatedAt(v time.Time) *SysUserUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *SysUserUpdateOne) SetNillableUpdatedAt(v *time.Time) *SysUserUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *SysUserUpdateOne) SetCreatedBy(v int64) *SysUserUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *SysUserUpdateOne) SetNillableCreatedBy(v *int64) *SysUserUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *SysUserUpdateOne) AddCreatedBy(v int64) *SysUserUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *SysUserUpdateOne) ClearCreatedBy() *SysUserUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *SysUserUpdateOne) SetUpdatedBy(v int64) *SysUserUpdateOne {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *SysUserUpdateOne) SetNillableUpdatedBy(v *int64) *SysUserUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *SysUserUpdateOne) AddUpdatedBy(v int64) *SysUserUpdateOne {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *SysUserUpdateOne) ClearUpdatedBy() *SysUserUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetUsername sets the "username" field.
func (_u *SysUserUpdateOne) SetUsername(v string) *SysUserUpdateOne {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *SysUserUpdateOne) SetNillableUsername(v *string) *SysUserUpdateOne {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetPasswordHash sets the "password_hash" field.
func (_u *SysUserUpdateOne) SetPasswordHash(v string) *SysUserUpdateOne {
	_u.mutation.SetPasswordHash(v)
	return _u
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (_u *SysUserUpdateOne) SetNillablePasswordHash(v *string) *SysUserUpdateOne {
	if v != nil {
		_u.SetPasswordHash(*v)
	}
	return _u
}

// SetNickname sets the "nickname" field.
func (_u *SysUserUpdateOne) SetNickname(v string) *SysUserUpdateOne {
	_u.mutation.SetNickname(v)
	return _u
}

// SetNillableNickname sets the "nickname" field if the given value is not nil.
func (_u *SysUserUpdateOne) SetNillableNickname(v *string) *SysUserUpdateOne {
	if v != nil {
		_u.SetNickname(*v)
	}
	return _u
}

// ClearNickname clears the value of the "nickname" field.
func (_u *SysUserUpdateOne) ClearNickname() *SysUserUpdateOne {
	_u.mutation.ClearNickname()
	return _u
}

// SetPhone sets the "phone" field.
func (_u *SysUserUpdateOne) SetPhone(v string) *SysUserUpdateOne {
	_u.mutation.SetPhone(v)
	return _u
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_u *SysUserUpdateOne) SetNillablePhone(v *string) *SysUserUpdateOne {
	if v != nil {
		_u.SetPhone(*v)
	}
	return _u
}

// ClearPhone clears the value of the "phone" field.
func (_u *SysUserUpdateOne) ClearPhone() *SysUserUpdateOne {
	_u.mutation.ClearPhone()
	return _u
}

// SetEmail sets the "email" field.
func (_u *SysUserUpdateOne) SetEmail(v string) *SysUserUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *SysUserUpdateOne) SetNillableEmail(v *string) *SysUserUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// ClearEmail clears the value of the "email" field.
func (_u *SysUserUpdateOne) ClearEmail() *SysUserUpdateOne {
	_u.mutation.ClearEmail()
	return _u
}

// SetAvatarURL sets the "avatar_url" field.
func (_u *SysUserUpdateOne) SetAvatarURL(v string) *SysUserUpdateOne {
	_u.mutation.SetAvatarURL(v)
	return _u
}

// SetNillableAvatarURL sets the "avatar_url" field if the given value is not nil.
func (_u *SysUserUpdateOne) SetNillableAvatarURL(v *string) *SysUserUpdateOne {
	if v != nil {
		_u.SetAvatarURL(*v)
	}
	return _u
}

// ClearAvatarURL clears the value of the "avatar_url" field.
func (_u *SysUserUpdateOne) ClearAvatarURL() *SysUserUpdateOne {
	_u.mutation.ClearAvatarURL()
	return _u
}

// SetIsSuperAdmin sets the "is_super_admin" field.
func (_u *SysUserUpdateOne) SetIsSuperAdmin(v bool) *SysUserUpdateOne {
	_u.mutation.SetIsSuperAdmin(v)
	return _u
}

// SetNillableIsSuperAdmin sets the "is_super_admin" field if the given value is not nil.
func (_u *SysUserUpdateOne) SetNillableIsSuperAdmin(v *bool) *SysUserUpdateOne {
	if v != nil {
		_u.SetIsSuperAdmin(*v)
	}
	return _u
}

// SetIsEnable sets the "is_enable" field.
func (_u *SysUserUpdateOne) SetIsEnable(v bool) *SysUserUpdateOne {
	_u.mutation.SetIsEnable(v)
	return _u
}

// SetNillableIsEnable sets the "is_enable" field if the given value is not nil.
func (_u *SysUserUpdateOne) SetNillableIsEnable(v *bool) *SysUserUpdateOne {
	if v != nil {
		_u.SetIsEnable(*v)
	}
	return _u
}

// SetSortID sets the "sort_id" field.
func (_u *SysUserUpdateOne) SetSortID(v int) *SysUserUpdateOne {
	_u.mutation.ResetSortID()
	_u.mutation.SetSortID(v)
	return _u
}

// SetNillableSortID sets the "sort_id" field if the given value is not nil.
func (_u *SysUserUpdateOne) SetNillableSortID(v *int) *SysUserUpdateOne {
	if v != nil {
		_u.SetSortID(*v)
	}
	return _u
}

// AddSortID adds value to the "sort_id" field.
func (_u *SysUserUpdateOne) AddSortID(v int) *SysUserUpdateOne {
	_u.mutation.AddSortID(v)
	return _u
}

// AddUserRoleIDs adds the "user_roles" edge to the SysUserRole entity by IDs.
func (_u *SysUserUpdateOne) AddUserRoleIDs(ids ...int64) *SysUserUpdateOne {
	_u.mutation.AddUserRoleIDs(ids...)
	return _u
}

// AddUserRoles adds the "user_roles" edges to the SysUserRole entity.
func (_u *SysUserUpdateOne) AddUserRoles(v ...*SysUserRole) *SysUserUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserRoleIDs(ids...)
}

// Mutation returns the SysUserMutation object of the builder.
func (_u *SysUserUpdateOne) Mutation() *SysUserMutation {
	return _u.mutation
}

// ClearUserRoles clears all "user_roles" edges to the SysUserRole entity.
func (_u *SysUserUpdateOne) ClearUserRoles() *SysUserUpdateOne {
	_u.mutation.ClearUserRoles()
	return _u
}

// RemoveUserRoleIDs removes the "user_roles" edge to SysUserRole entities by IDs.
func (_u *SysUserUpdateOne) RemoveUserRoleIDs(ids ...int64) *SysUserUpdateOne {
	_u.mutation.RemoveUserRoleIDs(ids...)
	return _u
}

// RemoveUserRoles removes "user_roles" edges to SysUserRole entities.
func (_u *SysUserUpdateOne) RemoveUserRoles(v ...*SysUserRole) *SysUserUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserRoleIDs(ids...)
}

// Where appends a list predicates to the SysUserUpdate builder.
func (_u *SysUserUpdateOne) Where(ps ...predicate.SysUser) *SysUserUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SysUserUpdateOne) Select(field string, fields ...string) *SysUserUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SysUser entity.
func (_u *SysUserUpdateOne) Save(ctx context.Context) (*SysUser, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SysUserUpdateOne) SaveX(ctx context.Context) *SysUser {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SysUserUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SysUserUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SysUserUpdateOne) check() error {
	if v, ok := _u.mutation.Username(); ok {
		if err := sysuser.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "SysUser.username": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PasswordHash(); ok {
		if err := sysuser.PasswordHashValidator(v); err != nil {
			return &ValidationError{Name: "password_hash", err: fmt.Errorf(`ent: validator failed for field "SysUser.password_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Nickname(); ok {
		if err := sysuser.NicknameValidator(v); err != nil {
			return &ValidationError{Name: "nickname", err: fmt.Errorf(`ent: validator failed for field "SysUser.nickname": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Phone(); ok {
		if err := sysuser.PhoneValidator(v); err != nil {
			return &ValidationError{Name: "phone", err: fmt.Errorf(`ent: validator failed for field "SysUser.phone": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Email(); ok {
		if err := sysuser.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "SysUser.email": %w`, err)}
		}
	}
	return nil
}

func (_u *SysUserUpdateOne) sqlSave(ctx context.Context) (_node *SysUser, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sysuser.Table, sysuser.Columns, sqlgraph.NewFieldSpec(sysuser.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SysUser.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sysuser.FieldID)
		for _, f := range fields {
			if !sysuser.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != sysuser.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(sysuser.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(sysuser.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(sysuser.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(sysuser.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(sysuser.FieldCreatedBy, field.TypeInt64, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(sysuser.FieldCreatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(sysuser.FieldUpdatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(sysuser.FieldUpdatedBy, field.TypeInt64, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(sysuser.FieldUpdatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(sysuser.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.PasswordHash(); ok {
		_spec.SetField(sysuser.FieldPasswordHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Nickname(); ok {
		_spec.SetField(sysuser.FieldNickname, field.TypeString, value)
	}
	if _u.mutation.NicknameCleared() {
		_spec.ClearField(sysuser.FieldNickname, field.TypeString)
	}
	if value, ok := _u.mutation.Phone(); ok {
		_spec.SetField(sysuser.FieldPhone, field.TypeString, value)
	}
	if _u.mutation.PhoneCleared() {
		_spec.ClearField(sysuser.FieldPhone, field.TypeString)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(sysuser.FieldEmail, field.TypeString, value)
	}
	if _u.mutation.EmailCleared() {
		_spec.ClearField(sysuser.FieldEmail, field.TypeString)
	}
	if value, ok := _u.mutation.AvatarURL(); ok {
		_spec.SetField(sysuser.FieldAvatarURL, field.TypeString, value)
	}
	if _u.mutation.AvatarURLCleared() {
		_spec.ClearField(sysuser.FieldAvatarURL, field.TypeString)
	}
	if value, ok := _u.mutation.IsSuperAdmin(); ok {
		_spec.SetField(sysuser.FieldIsSuperAdmin, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsEnable(); ok {
		_spec.SetField(sysuser.FieldIsEnable, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SortID(); ok {
		_spec.SetField(sysuser.FieldSortID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortID(); ok {
		_spec.AddField(sysuser.FieldSortID, field.TypeInt, value)
	}
	if _u.mutation.UserRolesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sysuser.UserRolesTable,
			Columns: []string{sysuser.UserRolesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sysuserrole.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUserRolesIDs(); len(nodes) > 0 && !_u.mutation.UserRolesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sysuser.UserRolesTable,
			Columns: []string{sysuser.UserRolesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sysuserrole.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserRolesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sysuser.UserRolesTable,
			Columns: []string{sysuser.UserRolesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sysuserrole.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SysUser{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sysuser.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
