// Code generated by ent, DO NOT EDIT.

package sysrolemenu

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/teamsillybees/initra/examples/internal/data/ent/predicate"
	"github.com/teamsillybees/initra/pkg/idgen"
)

// ID filters vertices based on their ID field.
func ID(id idgen.ID) predicate.SysRoleMenu {
	return predicate.SysRoleMenu(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id idgen.ID) predicate.SysRoleMenu {
	return predicate.SysRoleMenu(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id idgen.ID) predicate.SysRoleMenu {
	return predicate.SysRoleMenu(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...idgen.ID) predicate.SysRoleMenu {
	return predicate.SysRoleMenu(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...idgen.ID) predicate.SysRoleMenu {
	return predicate.SysRoleMenu(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id idgen.ID) predicate.SysRoleMenu {
	return predicate.SysRoleMenu(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id idgen.ID) predicate.SysRoleMenu {
	return predicate.SysRoleMenu(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id idgen.ID) predicate.SysRoleMenu {
	return predicate.SysRoleMenu(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id idgen.ID) predicate.SysRoleMenu {
	return predicate.SysRoleMenu(sql.FieldLTE(FieldID, id))
}

// RoleID applies equality check predicate on the "role_id" field. It's identical to RoleIDEQ.
func RoleID(v idgen.ID) predicate.SysRoleMenu {
	vc := int64(v)
	return predicate.SysRoleMenu(sql.FieldEQ(FieldRoleID, vc))
}

// MenuID applies equality check predicate on the "menu_id" field. It's identical to MenuIDEQ.
func MenuID(v idgen.ID) predicate.SysRoleMenu {
	vc := int64(v)
	return predicate.SysRoleMenu(sql.FieldEQ(FieldMenuID, vc))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.SysRoleMenu {
	return predicate.SysRoleMenu(sql.FieldEQ(FieldDeletedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SysRoleMenu {
	return predicate.SysRoleMenu(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SysRoleMenu {
	return predicate.SysRoleMenu(sql.FieldEQ(FieldUpdatedAt, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v idgen.ID) predicate.SysRoleMenu {
	vc := int64(v)
	return predicate.SysRoleMenu(sql.FieldEQ(FieldCreatedBy, vc))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v idgen.ID) predicate.SysRoleMenu {
	vc := int64(v)
	return predicate.SysRoleMenu(sql.FieldEQ(FieldUpdatedBy, vc))
}

// RoleIDEQ applies the EQ predicate on the "role_id" field.
func RoleIDEQ(v idgen.ID) predicate.SysRoleMenu {
	vc := int64(v)
	return predicate.SysRoleMenu(sql.FieldEQ(FieldRoleID, vc))
}

// RoleIDNEQ applies the NEQ predicate on the "role_id" field.
func RoleIDNEQ(v idgen.ID) predicate.SysRoleMenu {
	vc := int64(v)
	return predicate.SysRoleMenu(sql.FieldNEQ(FieldRoleID, vc))
}

// RoleIDIn applies the In predicate on the "role_id" field.
func RoleIDIn(vs ...idgen.ID) predicate.SysRoleMenu {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = int64(vs[i])
	}
	return predicate.SysRoleMenu(sql.FieldIn(FieldRoleID, v...))
}

// RoleIDNotIn applies the NotIn predicate on the "role_id" field.
func RoleIDNotIn(vs ...idgen.ID) predicate.SysRoleMenu {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = int64(vs[i])
	}
	return predicate.SysRoleMenu(sql.FieldNotIn(FieldRoleID, v...))
}

// MenuIDEQ applies the EQ predicate on the "menu_id" field.
func MenuIDEQ(v idgen.ID) predicate.SysRoleMenu {
	vc := int64(v)
	return predicate.SysRoleMenu(sql.FieldEQ(FieldMenuID, vc))
}

// MenuIDNEQ applies the NEQ predicate on the "menu_id" field.
func MenuIDNEQ(v idgen.ID) predicate.SysRoleMenu {
	vc := int64(v)
	return predicate.SysRoleMenu(sql.FieldNEQ(FieldMenuID, vc))
}

// MenuIDIn applies the In predicate on the "menu_id" field.
func MenuIDIn(vs ...idgen.ID) predicate.SysRoleMenu {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = int64(vs[i])
	}
	return predicate.SysRoleMenu(sql.FieldIn(FieldMenuID, v...))
}

// MenuIDNotIn applies the NotIn predicate on the "menu_id" field.
func MenuIDNotIn(vs ...idgen.ID) predicate.SysRoleMenu {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = int64(vs[i])
	}
	return predicate.SysRoleMenu(sql.FieldNotIn(FieldMenuID, v...))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.SysRoleMenu {
	return predicate.SysRoleMenu(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.SysRoleMenu {
	return predicate.SysRoleMenu(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.SysRoleMenu {
	return predicate.SysRoleMenu(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.SysRoleMenu {
	return predicate.SysRoleMenu(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.SysRoleMenu {
	return predicate.SysRoleMenu(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.SysRoleMenu {
	return predicate.SysRoleMenu(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.SysRoleMenu {
	return predicate.SysRoleMenu(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.SysRoleMenu {
	return predicate.SysRoleMenu(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.SysRoleMenu {
	return predicate.SysRoleMenu(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.SysRoleMenu {
	return predicate.SysRoleMenu(sql.FieldNotNull(FieldDeletedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SysRoleMenu {
	return predicate.SysRoleMenu(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SysRoleMenu {
	return predicate.SysRoleMenu(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SysRoleMenu {
	return predicate.SysRoleMenu(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SysRoleMenu {
	return predicate.SysRoleMenu(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SysRoleMenu {
	return predicate.SysRoleMenu(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SysRoleMenu {
	return predicate.SysRoleMenu(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SysRoleMenu {
	return predicate.SysRoleMenu(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SysRoleMenu {
	return predicate.SysRoleMenu(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SysRoleMenu {
	return predicate.SysRoleMenu(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SysRoleMenu {
	return predicate.SysRoleMenu(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SysRoleMenu {
	return predicate.SysRoleMenu(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SysRoleMenu {
	return predicate.SysRoleMenu(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SysRoleMenu {
	return predicate.SysRoleMenu(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SysRoleMenu {
	return predicate.SysRoleMenu(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SysRoleMenu {
	return predicate.SysRoleMenu(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SysRoleMenu {
	return predicate.SysRoleMenu(sql.FieldLTE(FieldUpdatedAt, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v idgen.ID) predicate.SysRoleMenu {
	vc := int64(v)
	return predicate.SysRoleMenu(sql.FieldEQ(FieldCreatedBy, vc))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v idgen.ID) predicate.SysRoleMenu {
	vc := int64(v)
	return predicate.SysRoleMenu(sql.FieldNEQ(FieldCreatedBy, vc))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...idgen.ID) predicate.SysRoleMenu {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = int64(vs[i])
	}
	return predicate.SysRoleMenu(sql.FieldIn(FieldCreatedBy, v...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...idgen.ID) predicate.SysRoleMenu {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = int64(vs[i])
	}
	return predicate.SysRoleMenu(sql.FieldNotIn(FieldCreatedBy, v...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v idgen.ID) predicate.SysRoleMenu {
	vc := int64(v)
	return predicate.SysRoleMenu(sql.FieldGT(FieldCreatedBy, vc))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v idgen.ID) predicate.SysRoleMenu {
	vc := int64(v)
	return predicate.SysRoleMenu(sql.FieldGTE(FieldCreatedBy, vc))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v idgen.ID) predicate.SysRoleMenu {
	vc := int64(v)
	return predicate.SysRoleMenu(sql.FieldLT(FieldCreatedBy, vc))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v idgen.ID) predicate.SysRoleMenu {
	vc := int64(v)
	return predicate.SysRoleMenu(sql.FieldLTE(FieldCreatedBy, vc))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.SysRoleMenu {
	return predicate.SysRoleMenu(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.SysRoleMenu {
	return predicate.SysRoleMenu(sql.FieldNotNull(FieldCreatedBy))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v idgen.ID) predicate.SysRoleMenu {
	vc := int64(v)
	return predicate.SysRoleMenu(sql.FieldEQ(FieldUpdatedBy, vc))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v idgen.ID) predicate.SysRoleMenu {
	vc := int64(v)
	return predicate.SysRoleMenu(sql.FieldNEQ(FieldUpdatedBy, vc))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...idgen.ID) predicate.SysRoleMenu {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = int64(vs[i])
	}
	return predicate.SysRoleMenu(sql.FieldIn(FieldUpdatedBy, v...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...idgen.ID) predicate.SysRoleMenu {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = int64(vs[i])
	}
	return predicate.SysRoleMenu(sql.FieldNotIn(FieldUpdatedBy, v...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v idgen.ID) predicate.SysRoleMenu {
	vc := int64(v)
	return predicate.SysRoleMenu(sql.FieldGT(FieldUpdatedBy, vc))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v idgen.ID) predicate.SysRoleMenu {
	vc := int64(v)
	return predicate.SysRoleMenu(sql.FieldGTE(FieldUpdatedBy, vc))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v idgen.ID) predicate.SysRoleMenu {
	vc := int64(v)
	return predicate.SysRoleMenu(sql.FieldLT(FieldUpdatedBy, vc))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v idgen.ID) predicate.SysRoleMenu {
	vc := int64(v)
	return predicate.SysRoleMenu(sql.FieldLTE(FieldUpdatedBy, vc))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.SysRoleMenu {
	return predicate.SysRoleMenu(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.SysRoleMenu {
	return predicate.SysRoleMenu(sql.FieldNotNull(FieldUpdatedBy))
}

// HasRole applies the HasEdge predicate on the "role" edge.
func HasRole() predicate.SysRoleMenu {
	return predicate.SysRoleMenu(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, RoleTable, RoleColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRoleWith applies the HasEdge predicate on the "role" edge with a given conditions (other predicates).
func HasRoleWith(preds ...predicate.SysRole) predicate.SysRoleMenu {
	return predicate.SysRoleMenu(func(s *sql.Selector) {
		step := newRoleStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasMenu applies the HasEdge predicate on the "menu" edge.
func HasMenu() predicate.SysRoleMenu {
	return predicate.SysRoleMenu(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, MenuTable, MenuColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMenuWith applies the HasEdge predicate on the "menu" edge with a given conditions (other predicates).
func HasMenuWith(preds ...predicate.SysMenu) predicate.SysRoleMenu {
	return predicate.SysRoleMenu(func(s *sql.Selector) {
		step := newMenuStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SysRoleMenu) predicate.SysRoleMenu {
	return predicate.SysRoleMenu(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SysRoleMenu) predicate.SysRoleMenu {
	return predicate.SysRoleMenu(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SysRoleMenu) predicate.SysRoleMenu {
	return predicate.SysRoleMenu(sql.NotPredicates(p))
}
