// Code generated by ent, DO NOT EDIT.

package sysrole

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/teamsillybees/initra/examples/internal/data/ent/predicate"
	"github.com/teamsillybees/initra/pkg/idgen"
)

// ID filters vertices based on their ID field.
func ID(id idgen.ID) predicate.SysRole {
	return predicate.SysRole(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id idgen.ID) predicate.SysRole {
	return predicate.SysRole(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id idgen.ID) predicate.SysRole {
	return predicate.SysRole(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...idgen.ID) predicate.SysRole {
	return predicate.SysRole(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...idgen.ID) predicate.SysRole {
	return predicate.SysRole(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id idgen.ID) predicate.SysRole {
	return predicate.SysRole(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id idgen.ID) predicate.SysRole {
	return predicate.SysRole(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id idgen.ID) predicate.SysRole {
	return predicate.SysRole(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id idgen.ID) predicate.SysRole {
	return predicate.SysRole(sql.FieldLTE(FieldID, id))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.SysRole {
	return predicate.SysRole(sql.FieldEQ(FieldDeletedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SysRole {
	return predicate.SysRole(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SysRole {
	return predicate.SysRole(sql.FieldEQ(FieldUpdatedAt, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v idgen.ID) predicate.SysRole {
	vc := int64(v)
	return predicate.SysRole(sql.FieldEQ(FieldCreatedBy, vc))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v idgen.ID) predicate.SysRole {
	vc := int64(v)
	return predicate.SysRole(sql.FieldEQ(FieldUpdatedBy, vc))
}

// Code applies equality check predicate on the "code" field. It's identical to CodeEQ.
func Code(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldEQ(FieldCode, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldEQ(FieldName, v))
}

// Remark applies equality check predicate on the "remark" field. It's identical to RemarkEQ.
func Remark(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldEQ(FieldRemark, v))
}

// IsBuiltin applies equality check predicate on the "is_builtin" field. It's identical to IsBuiltinEQ.
func IsBuiltin(v bool) predicate.SysRole {
	return predicate.SysRole(sql.FieldEQ(FieldIsBuiltin, v))
}

// IsEnable applies equality check predicate on the "is_enable" field. It's identical to IsEnableEQ.
func IsEnable(v bool) predicate.SysRole {
	return predicate.SysRole(sql.FieldEQ(FieldIsEnable, v))
}

// SortID applies equality check predicate on the "sort_id" field. It's identical to SortIDEQ.
func SortID(v int) predicate.SysRole {
	return predicate.SysRole(sql.FieldEQ(FieldSortID, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.SysRole {
	return predicate.SysRole(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.SysRole {
	return predicate.SysRole(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.SysRole {
	return predicate.SysRole(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.SysRole {
	return predicate.SysRole(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.SysRole {
	return predicate.SysRole(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.SysRole {
	return predicate.SysRole(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.SysRole {
	return predicate.SysRole(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.SysRole {
	return predicate.SysRole(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.SysRole {
	return predicate.SysRole(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.SysRole {
	return predicate.SysRole(sql.FieldNotNull(FieldDeletedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SysRole {
	return predicate.SysRole(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SysRole {
	return predicate.SysRole(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SysRole {
	return predicate.SysRole(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SysRole {
	return predicate.SysRole(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SysRole {
	return predicate.SysRole(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SysRole {
	return predicate.SysRole(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SysRole {
	return predicate.SysRole(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SysRole {
	return predicate.SysRole(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SysRole {
	return predicate.SysRole(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SysRole {
	return predicate.SysRole(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SysRole {
	return predicate.SysRole(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SysRole {
	return predicate.SysRole(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SysRole {
	return predicate.SysRole(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SysRole {
	return predicate.SysRole(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SysRole {
	return predicate.SysRole(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SysRole {
	return predicate.SysRole(sql.FieldLTE(FieldUpdatedAt, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v idgen.ID) predicate.SysRole {
	vc := int64(v)
	return predicate.SysRole(sql.FieldEQ(FieldCreatedBy, vc))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v idgen.ID) predicate.SysRole {
	vc := int64(v)
	return predicate.SysRole(sql.FieldNEQ(FieldCreatedBy, vc))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...idgen.ID) predicate.SysRole {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = int64(vs[i])
	}
	return predicate.SysRole(sql.FieldIn(FieldCreatedBy, v...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...idgen.ID) predicate.SysRole {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = int64(vs[i])
	}
	return predicate.SysRole(sql.FieldNotIn(FieldCreatedBy, v...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v idgen.ID) predicate.SysRole {
	vc := int64(v)
	return predicate.SysRole(sql.FieldGT(FieldCreatedBy, vc))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v idgen.ID) predicate.SysRole {
	vc := int64(v)
	return predicate.SysRole(sql.FieldGTE(FieldCreatedBy, vc))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v idgen.ID) predicate.SysRole {
	vc := int64(v)
	return predicate.SysRole(sql.FieldLT(FieldCreatedBy, vc))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v idgen.ID) predicate.SysRole {
	vc := int64(v)
	return predicate.SysRole(sql.FieldLTE(FieldCreatedBy, vc))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.SysRole {
	return predicate.SysRole(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.SysRole {
	return predicate.SysRole(sql.FieldNotNull(FieldCreatedBy))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v idgen.ID) predicate.SysRole {
	vc := int64(v)
	return predicate.SysRole(sql.FieldEQ(FieldUpdatedBy, vc))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v idgen.ID) predicate.SysRole {
	vc := int64(v)
	return predicate.SysRole(sql.FieldNEQ(FieldUpdatedBy, vc))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...idgen.ID) predicate.SysRole {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = int64(vs[i])
	}
	return predicate.SysRole(sql.FieldIn(FieldUpdatedBy, v...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...idgen.ID) predicate.SysRole {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = int64(vs[i])
	}
	return predicate.SysRole(sql.FieldNotIn(FieldUpdatedBy, v...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v idgen.ID) predicate.SysRole {
	vc := int64(v)
	return predicate.SysRole(sql.FieldGT(FieldUpdatedBy, vc))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v idgen.ID) predicate.SysRole {
	vc := int64(v)
	return predicate.SysRole(sql.FieldGTE(FieldUpdatedBy, vc))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v idgen.ID) predicate.SysRole {
	vc := int64(v)
	return predicate.SysRole(sql.FieldLT(FieldUpdatedBy, vc))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v idgen.ID) predicate.SysRole {
	vc := int64(v)
	return predicate.SysRole(sql.FieldLTE(FieldUpdatedBy, vc))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.SysRole {
	return predicate.SysRole(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.SysRole {
	return predicate.SysRole(sql.FieldNotNull(FieldUpdatedBy))
}

// CodeEQ applies the EQ predicate on the "code" field.
func CodeEQ(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldEQ(FieldCode, v))
}

// CodeNEQ applies the NEQ predicate on the "code" field.
func CodeNEQ(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldNEQ(FieldCode, v))
}

// CodeIn applies the In predicate on the "code" field.
func CodeIn(vs ...string) predicate.SysRole {
	return predicate.SysRole(sql.FieldIn(FieldCode, vs...))
}

// CodeNotIn applies the NotIn predicate on the "code" field.
func CodeNotIn(vs ...string) predicate.SysRole {
	return predicate.SysRole(sql.FieldNotIn(FieldCode, vs...))
}

// CodeGT applies the GT predicate on the "code" field.
func CodeGT(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldGT(FieldCode, v))
}

// CodeGTE applies the GTE predicate on the "code" field.
func CodeGTE(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldGTE(FieldCode, v))
}

// CodeLT applies the LT predicate on the "code" field.
func CodeLT(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldLT(FieldCode, v))
}

// CodeLTE applies the LTE predicate on the "code" field.
func CodeLTE(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldLTE(FieldCode, v))
}

// CodeContains applies the Contains predicate on the "code" field.
func CodeContains(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldContains(FieldCode, v))
}

// CodeHasPrefix applies the HasPrefix predicate on the "code" field.
func CodeHasPrefix(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldHasPrefix(FieldCode, v))
}

// CodeHasSuffix applies the HasSuffix predicate on the "code" field.
func CodeHasSuffix(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldHasSuffix(FieldCode, v))
}

// CodeEqualFold applies the EqualFold predicate on the "code" field.
func CodeEqualFold(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldEqualFold(FieldCode, v))
}

// CodeContainsFold applies the ContainsFold predicate on the "code" field.
func CodeContainsFold(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldContainsFold(FieldCode, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.SysRole {
	return predicate.SysRole(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.SysRole {
	return predicate.SysRole(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldContainsFold(FieldName, v))
}

// RemarkEQ applies the EQ predicate on the "remark" field.
func RemarkEQ(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldEQ(FieldRemark, v))
}

// RemarkNEQ applies the NEQ predicate on the "remark" field.
func RemarkNEQ(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldNEQ(FieldRemark, v))
}

// RemarkIn applies the In predicate on the "remark" field.
func RemarkIn(vs ...string) predicate.SysRole {
	return predicate.SysRole(sql.FieldIn(FieldRemark, vs...))
}

// RemarkNotIn applies the NotIn predicate on the "remark" field.
func RemarkNotIn(vs ...string) predicate.SysRole {
	return predicate.SysRole(sql.FieldNotIn(FieldRemark, vs...))
}

// RemarkGT applies the GT predicate on the "remark" field.
func RemarkGT(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldGT(FieldRemark, v))
}

// RemarkGTE applies the GTE predicate on the "remark" field.
func RemarkGTE(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldGTE(FieldRemark, v))
}

// RemarkLT applies the LT predicate on the "remark" field.
func RemarkLT(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldLT(FieldRemark, v))
}

// RemarkLTE applies the LTE predicate on the "remark" field.
func RemarkLTE(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldLTE(FieldRemark, v))
}

// RemarkContains applies the Contains predicate on the "remark" field.
func RemarkContains(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldContains(FieldRemark, v))
}

// RemarkHasPrefix applies the HasPrefix predicate on the "remark" field.
func RemarkHasPrefix(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldHasPrefix(FieldRemark, v))
}

// RemarkHasSuffix applies the HasSuffix predicate on the "remark" field.
func RemarkHasSuffix(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldHasSuffix(FieldRemark, v))
}

// RemarkIsNil applies the IsNil predicate on the "remark" field.
func RemarkIsNil() predicate.SysRole {
	return predicate.SysRole(sql.FieldIsNull(FieldRemark))
}

// RemarkNotNil applies the NotNil predicate on the "remark" field.
func RemarkNotNil() predicate.SysRole {
	return predicate.SysRole(sql.FieldNotNull(FieldRemark))
}

// RemarkEqualFold applies the EqualFold predicate on the "remark" field.
func RemarkEqualFold(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldEqualFold(FieldRemark, v))
}

// RemarkContainsFold applies the ContainsFold predicate on the "remark" field.
func RemarkContainsFold(v string) predicate.SysRole {
	return predicate.SysRole(sql.FieldContainsFold(FieldRemark, v))
}

// IsBuiltinEQ applies the EQ predicate on the "is_builtin" field.
func IsBuiltinEQ(v bool) predicate.SysRole {
	return predicate.SysRole(sql.FieldEQ(FieldIsBuiltin, v))
}

// IsBuiltinNEQ applies the NEQ predicate on the "is_builtin" field.
func IsBuiltinNEQ(v bool) predicate.SysRole {
	return predicate.SysRole(sql.FieldNEQ(FieldIsBuiltin, v))
}

// IsEnableEQ applies the EQ predicate on the "is_enable" field.
func IsEnableEQ(v bool) predicate.SysRole {
	return predicate.SysRole(sql.FieldEQ(FieldIsEnable, v))
}

// IsEnableNEQ applies the NEQ predicate on the "is_enable" field.
func IsEnableNEQ(v bool) predicate.SysRole {
	return predicate.SysRole(sql.FieldNEQ(FieldIsEnable, v))
}

// SortIDEQ applies the EQ predicate on the "sort_id" field.
func SortIDEQ(v int) predicate.SysRole {
	return predicate.SysRole(sql.FieldEQ(FieldSortID, v))
}

// SortIDNEQ applies the NEQ predicate on the "sort_id" field.
func SortIDNEQ(v int) predicate.SysRole {
	return predicate.SysRole(sql.FieldNEQ(FieldSortID, v))
}

// SortIDIn applies the In predicate on the "sort_id" field.
func SortIDIn(vs ...int) predicate.SysRole {
	return predicate.SysRole(sql.FieldIn(FieldSortID, vs...))
}

// SortIDNotIn applies the NotIn predicate on the "sort_id" field.
func SortIDNotIn(vs ...int) predicate.SysRole {
	return predicate.SysRole(sql.FieldNotIn(FieldSortID, vs...))
}

// SortIDGT applies the GT predicate on the "sort_id" field.
func SortIDGT(v int) predicate.SysRole {
	return predicate.SysRole(sql.FieldGT(FieldSortID, v))
}

// SortIDGTE applies the GTE predicate on the "sort_id" field.
func SortIDGTE(v int) predicate.SysRole {
	return predicate.SysRole(sql.FieldGTE(FieldSortID, v))
}

// SortIDLT applies the LT predicate on the "sort_id" field.
func SortIDLT(v int) predicate.SysRole {
	return predicate.SysRole(sql.FieldLT(FieldSortID, v))
}

// SortIDLTE applies the LTE predicate on the "sort_id" field.
func SortIDLTE(v int) predicate.SysRole {
	return predicate.SysRole(sql.FieldLTE(FieldSortID, v))
}

// HasUserRoles applies the HasEdge predicate on the "user_roles" edge.
func HasUserRoles() predicate.SysRole {
	return predicate.SysRole(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, UserRolesTable, UserRolesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserRolesWith applies the HasEdge predicate on the "user_roles" edge with a given conditions (other predicates).
func HasUserRolesWith(preds ...predicate.SysUserRole) predicate.SysRole {
	return predicate.SysRole(func(s *sql.Selector) {
		step := newUserRolesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRoleMenus applies the HasEdge predicate on the "role_menus" edge.
func HasRoleMenus() predicate.SysRole {
	return predicate.SysRole(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, RoleMenusTable, RoleMenusColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRoleMenusWith applies the HasEdge predicate on the "role_menus" edge with a given conditions (other predicates).
func HasRoleMenusWith(preds ...predicate.SysRoleMenu) predicate.SysRole {
	return predicate.SysRole(func(s *sql.Selector) {
		step := newRoleMenusStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SysRole) predicate.SysRole {
	return predicate.SysRole(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SysRole) predicate.SysRole {
	return predicate.SysRole(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SysRole) predicate.SysRole {
	return predicate.SysRole(sql.NotPredicates(p))
}
