// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// SysConfigColumns holds the columns for the "sys_config" table.
	SysConfigColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "created_by", Type: field.TypeInt64, Nullable: true},
		{Name: "updated_by", Type: field.TypeInt64, Nullable: true},
		{Name: "config_key", Type: field.TypeString, Unique: true, Size: 128},
		{Name: "config_value", Type: field.TypeString, Size: 2147483647, Default: ""},
		{Name: "config_desc", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "is_builtin", Type: field.TypeBool, Default: false},
		{Name: "sort_id", Type: field.TypeInt, Default: 0},
	}
	// SysConfigTable holds the schema information for the "sys_config" table.
	SysConfigTable = &schema.Table{
		Name:       "sys_config",
		Columns:    SysConfigColumns,
		PrimaryKey: []*schema.Column{SysConfigColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "sysconfig_deleted_at",
				Unique:  false,
				Columns: []*schema.Column{SysConfigColumns[1]},
			},
		},
	}
	// SysDictCollectionColumns holds the columns for the "sys_dict_collection" table.
	SysDictCollectionColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "created_by", Type: field.TypeInt64, Nullable: true},
		{Name: "updated_by", Type: field.TypeInt64, Nullable: true},
		{Name: "code", Type: field.TypeString, Unique: true, Size: 64},
		{Name: "name", Type: field.TypeString, Size: 128},
		{Name: "is_enable", Type: field.TypeBool, Default: true},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "item_length", Type: field.TypeInt, Nullable: true},
		{Name: "is_builtin", Type: field.TypeBool, Default: false},
		{Name: "sort_id", Type: field.TypeInt, Default: 0},
	}
	// SysDictCollectionTable holds the schema information for the "sys_dict_collection" table.
	SysDictCollectionTable = &schema.Table{
		Name:       "sys_dict_collection",
		Columns:    SysDictCollectionColumns,
		PrimaryKey: []*schema.Column{SysDictCollectionColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "sysdictcollection_deleted_at",
				Unique:  false,
				Columns: []*schema.Column{SysDictCollectionColumns[1]},
			},
		},
	}
	// SysDictItemColumns holds the columns for the "sys_dict_item" table.
	SysDictItemColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "created_by", Type: field.TypeInt64, Nullable: true},
		{Name: "updated_by", Type: field.TypeInt64, Nullable: true},
		{Name: "collection_code", Type: field.TypeString, Size: 64},
		{Name: "code", Type: field.TypeString, Size: 64},
		{Name: "parent_code", Type: field.TypeString, Size: 64, Default: "0"},
		{Name: "label", Type: field.TypeString, Size: 128},
		{Name: "is_default_value", Type: field.TypeBool, Default: false},
		{Name: "is_enable", Type: field.TypeBool, Default: true},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "sort_id", Type: field.TypeInt, Default: 0},
		{Name: "collection_id", Type: field.TypeInt64},
	}
	// SysDictItemTable holds the schema information for the "sys_dict_item" table.
	SysDictItemTable = &schema.Table{
		Name:       "sys_dict_item",
		Columns:    SysDictItemColumns,
		PrimaryKey: []*schema.Column{SysDictItemColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sys_dict_item_sys_dict_collection_items",
				Columns:    []*schema.Column{SysDictItemColumns[14]},
				RefColumns: []*schema.Column{SysDictCollectionColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "sysdictitem_deleted_at",
				Unique:  false,
				Columns: []*schema.Column{SysDictItemColumns[1]},
			},
			{
				Name:    "sysdictitem_collection_id",
				Unique:  false,
				Columns: []*schema.Column{SysDictItemColumns[14]},
			},
			{
				Name:    "sysdictitem_collection_code",
				Unique:  false,
				Columns: []*schema.Column{SysDictItemColumns[6]},
			},
			{
				Name:    "sysdictitem_collection_code_code",
				Unique:  true,
				Columns: []*schema.Column{SysDictItemColumns[6], SysDictItemColumns[7]},
			},
		},
	}
	// SysMenuColumns holds the columns for the "sys_menu" table.
	SysMenuColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "created_by", Type: field.TypeInt64, Nullable: true},
		{Name: "updated_by", Type: field.TypeInt64, Nullable: true},
		{Name: "parent_id", Type: field.TypeInt64, Default: 0},
		{Name: "app_id", Type: field.TypeString, Nullable: true, Size: 64},
		{Name: "title", Type: field.TypeString, Size: 128},
		{Name: "menu_type", Type: field.TypeInt16},
		{Name: "route_path", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "component_path", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "permission_code", Type: field.TypeString, Unique: true, Nullable: true, Size: 128},
		{Name: "icon", Type: field.TypeString, Nullable: true, Size: 128},
		{Name: "is_visible", Type: field.TypeBool, Default: true},
		{Name: "is_cached", Type: field.TypeBool, Default: true},
		{Name: "sort_id", Type: field.TypeInt, Default: 0},
	}
	// SysMenuTable holds the schema information for the "sys_menu" table.
	SysMenuTable = &schema.Table{
		Name:       "sys_menu",
		Columns:    SysMenuColumns,
		PrimaryKey: []*schema.Column{SysMenuColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "sysmenu_deleted_at",
				Unique:  false,
				Columns: []*schema.Column{SysMenuColumns[1]},
			},
			{
				Name:    "sysmenu_parent_id",
				Unique:  false,
				Columns: []*schema.Column{SysMenuColumns[6]},
			},
		},
	}
	// SysRoleColumns holds the columns for the "sys_role" table.
	SysRoleColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "created_by", Type: field.TypeInt64, Nullable: true},
		{Name: "updated_by", Type: field.TypeInt64, Nullable: true},
		{Name: "code", Type: field.TypeString, Unique: true, Size: 64},
		{Name: "name", Type: field.TypeString, Size: 128},
		{Name: "remark", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "is_builtin", Type: field.TypeBool, Default: false},
		{Name: "is_enable", Type: field.TypeBool, Default: true},
		{Name: "sort_id", Type: field.TypeInt, Default: 0},
	}
	// SysRoleTable holds the schema information for the "sys_role" table.
	SysRoleTable = &schema.Table{
		Name:       "sys_role",
		Columns:    SysRoleColumns,
		PrimaryKey: []*schema.Column{SysRoleColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "sysrole_deleted_at",
				Unique:  false,
				Columns: []*schema.Column{SysRoleColumns[1]},
			},
			{
				Name:    "sysrole_is_enable",
				Unique:  false,
				Columns: []*schema.Column{SysRoleColumns[10]},
			},
		},
	}
	// SysRoleMenuColumns holds the columns for the "sys_role_menu" table.
	SysRoleMenuColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_by", Type: field.TypeInt64, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "menu_id", Type: field.TypeInt64},
		{Name: "role_id", Type: field.TypeInt64},
	}
	// SysRoleMenuTable holds the schema information for the "sys_role_menu" table.
	SysRoleMenuTable = &schema.Table{
		Name:       "sys_role_menu",
		Columns:    SysRoleMenuColumns,
		PrimaryKey: []*schema.Column{SysRoleMenuColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sys_role_menu_sys_menu_role_menus",
				Columns:    []*schema.Column{SysRoleMenuColumns[4]},
				RefColumns: []*schema.Column{SysMenuColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "sys_role_menu_sys_role_role_menus",
				Columns:    []*schema.Column{SysRoleMenuColumns[5]},
				RefColumns: []*schema.Column{SysRoleColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "sysrolemenu_deleted_at",
				Unique:  false,
				Columns: []*schema.Column{SysRoleMenuColumns[1]},
			},
			{
				Name:    "sysrolemenu_role_id",
				Unique:  false,
				Columns: []*schema.Column{SysRoleMenuColumns[5]},
			},
			{
				Name:    "sysrolemenu_menu_id",
				Unique:  false,
				Columns: []*schema.Column{SysRoleMenuColumns[4]},
			},
			{
				Name:    "sysrolemenu_role_id_menu_id",
				Unique:  true,
				Columns: []*schema.Column{SysRoleMenuColumns[5], SysRoleMenuColumns[4]},
			},
		},
	}
	// SysUserColumns holds the columns for the "sys_user" table.
	SysUserColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "created_by", Type: field.TypeInt64, Nullable: true},
		{Name: "updated_by", Type: field.TypeInt64, Nullable: true},
		{Name: "username", Type: field.TypeString, Unique: true, Size: 64},
		{Name: "password_hash", Type: field.TypeString, Size: 2147483647},
		{Name: "nickname", Type: field.TypeString, Nullable: true, Size: 128},
		{Name: "phone", Type: field.TypeString, Unique: true, Nullable: true, Size: 32},
		{Name: "email", Type: field.TypeString, Unique: true, Nullable: true, Size: 255},
		{Name: "avatar_url", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "is_super_admin", Type: field.TypeBool, Default: false},
		{Name: "is_enable", Type: field.TypeBool, Default: true},
		{Name: "sort_id", Type: field.TypeInt, Default: 0},
	}
	// SysUserTable holds the schema information for the "sys_user" table.
	SysUserTable = &schema.Table{
		Name:       "sys_user",
		Columns:    SysUserColumns,
		PrimaryKey: []*schema.Column{SysUserColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "sysuser_deleted_at",
				Unique:  false,
				Columns: []*schema.Column{SysUserColumns[1]},
			},
			{
				Name:    "sysuser_is_enable",
				Unique:  false,
				Columns: []*schema.Column{SysUserColumns[13]},
			},
		},
	}
	// SysUserRoleColumns holds the columns for the "sys_user_role" table.
	SysUserRoleColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_by", Type: field.TypeInt64, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "role_id", Type: field.TypeInt64},
		{Name: "user_id", Type: field.TypeInt64},
	}
	// SysUserRoleTable holds the schema information for the "sys_user_role" table.
	SysUserRoleTable = &schema.Table{
		Name:       "sys_user_role",
		Columns:    SysUserRoleColumns,
		PrimaryKey: []*schema.Column{SysUserRoleColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sys_user_role_sys_role_user_roles",
				Columns:    []*schema.Column{SysUserRoleColumns[4]},
				RefColumns: []*schema.Column{SysRoleColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "sys_user_role_sys_user_user_roles",
				Columns:    []*schema.Column{SysUserRoleColumns[5]},
				RefColumns: []*schema.Column{SysUserColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "sysuserrole_deleted_at",
				Unique:  false,
				Columns: []*schema.Column{SysUserRoleColumns[1]},
			},
			{
				Name:    "sysuserrole_user_id",
				Unique:  false,
				Columns: []*schema.Column{SysUserRoleColumns[5]},
			},
			{
				Name:    "sysuserrole_role_id",
				Unique:  false,
				Columns: []*schema.Column{SysUserRoleColumns[4]},
			},
			{
				Name:    "sysuserrole_user_id_role_id",
				Unique:  true,
				Columns: []*schema.Column{SysUserRoleColumns[5], SysUserRoleColumns[4]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		SysConfigTable,
		SysDictCollectionTable,
		SysDictItemTable,
		SysMenuTable,
		SysRoleTable,
		SysRoleMenuTable,
		SysUserTable,
		SysUserRoleTable,
	}
)

func init() {
	SysConfigTable.Annotation = &entsql.Annotation{
		Table: "sys_config",
	}
	SysDictCollectionTable.Annotation = &entsql.Annotation{
		Table: "sys_dict_collection",
	}
	SysDictItemTable.ForeignKeys[0].RefTable = SysDictCollectionTable
	SysDictItemTable.Annotation = &entsql.Annotation{
		Table: "sys_dict_item",
	}
	SysMenuTable.Annotation = &entsql.Annotation{
		Table: "sys_menu",
	}
	SysRoleTable.Annotation = &entsql.Annotation{
		Table: "sys_role",
	}
	SysRoleMenuTable.ForeignKeys[0].RefTable = SysMenuTable
	SysRoleMenuTable.ForeignKeys[1].RefTable = SysRoleTable
	SysRoleMenuTable.Annotation = &entsql.Annotation{
		Table: "sys_role_menu",
	}
	SysUserTable.Annotation = &entsql.Annotation{
		Table: "sys_user",
	}
	SysUserRoleTable.ForeignKeys[0].RefTable = SysRoleTable
	SysUserRoleTable.ForeignKeys[1].RefTable = SysUserTable
	SysUserRoleTable.Annotation = &entsql.Annotation{
		Table: "sys_user_role",
	}
}
