// Code generated by ent, DO NOT EDIT.

package sysconfig

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/teamsillybees/initra/examples/internal/data/ent/predicate"
	"github.com/teamsillybees/initra/pkg/idgen"
)

// ID filters vertices based on their ID field.
func ID(id idgen.ID) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id idgen.ID) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id idgen.ID) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...idgen.ID) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...idgen.ID) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id idgen.ID) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id idgen.ID) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id idgen.ID) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id idgen.ID) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldLTE(FieldID, id))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldEQ(FieldDeletedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldEQ(FieldUpdatedAt, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v idgen.ID) predicate.SysConfig {
	vc := int64(v)
	return predicate.SysConfig(sql.FieldEQ(FieldCreatedBy, vc))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v idgen.ID) predicate.SysConfig {
	vc := int64(v)
	return predicate.SysConfig(sql.FieldEQ(FieldUpdatedBy, vc))
}

// ConfigKey applies equality check predicate on the "config_key" field. It's identical to ConfigKeyEQ.
func ConfigKey(v string) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldEQ(FieldConfigKey, v))
}

// ConfigValue applies equality check predicate on the "config_value" field. It's identical to ConfigValueEQ.
func ConfigValue(v string) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldEQ(FieldConfigValue, v))
}

// ConfigDesc applies equality check predicate on the "config_desc" field. It's identical to ConfigDescEQ.
func ConfigDesc(v string) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldEQ(FieldConfigDesc, v))
}

// IsBuiltin applies equality check predicate on the "is_builtin" field. It's identical to IsBuiltinEQ.
func IsBuiltin(v bool) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldEQ(FieldIsBuiltin, v))
}

// SortID applies equality check predicate on the "sort_id" field. It's identical to SortIDEQ.
func SortID(v int) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldEQ(FieldSortID, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.SysConfig {
	return predicate.SysConfig(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.SysConfig {
	return predicate.SysConfig(sql.FieldNotNull(FieldDeletedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldLTE(FieldUpdatedAt, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v idgen.ID) predicate.SysConfig {
	vc := int64(v)
	return predicate.SysConfig(sql.FieldEQ(FieldCreatedBy, vc))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v idgen.ID) predicate.SysConfig {
	vc := int64(v)
	return predicate.SysConfig(sql.FieldNEQ(FieldCreatedBy, vc))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...idgen.ID) predicate.SysConfig {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = int64(vs[i])
	}
	return predicate.SysConfig(sql.FieldIn(FieldCreatedBy, v...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...idgen.ID) predicate.SysConfig {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = int64(vs[i])
	}
	return predicate.SysConfig(sql.FieldNotIn(FieldCreatedBy, v...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v idgen.ID) predicate.SysConfig {
	vc := int64(v)
	return predicate.SysConfig(sql.FieldGT(FieldCreatedBy, vc))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v idgen.ID) predicate.SysConfig {
	vc := int64(v)
	return predicate.SysConfig(sql.FieldGTE(FieldCreatedBy, vc))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v idgen.ID) predicate.SysConfig {
	vc := int64(v)
	return predicate.SysConfig(sql.FieldLT(FieldCreatedBy, vc))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v idgen.ID) predicate.SysConfig {
	vc := int64(v)
	return predicate.SysConfig(sql.FieldLTE(FieldCreatedBy, vc))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.SysConfig {
	return predicate.SysConfig(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.SysConfig {
	return predicate.SysConfig(sql.FieldNotNull(FieldCreatedBy))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v idgen.ID) predicate.SysConfig {
	vc := int64(v)
	return predicate.SysConfig(sql.FieldEQ(FieldUpdatedBy, vc))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v idgen.ID) predicate.SysConfig {
	vc := int64(v)
	return predicate.SysConfig(sql.FieldNEQ(FieldUpdatedBy, vc))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...idgen.ID) predicate.SysConfig {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = int64(vs[i])
	}
	return predicate.SysConfig(sql.FieldIn(FieldUpdatedBy, v...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...idgen.ID) predicate.SysConfig {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = int64(vs[i])
	}
	return predicate.SysConfig(sql.FieldNotIn(FieldUpdatedBy, v...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v idgen.ID) predicate.SysConfig {
	vc := int64(v)
	return predicate.SysConfig(sql.FieldGT(FieldUpdatedBy, vc))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v idgen.ID) predicate.SysConfig {
	vc := int64(v)
	return predicate.SysConfig(sql.FieldGTE(FieldUpdatedBy, vc))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v idgen.ID) predicate.SysConfig {
	vc := int64(v)
	return predicate.SysConfig(sql.FieldLT(FieldUpdatedBy, vc))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v idgen.ID) predicate.SysConfig {
	vc := int64(v)
	return predicate.SysConfig(sql.FieldLTE(FieldUpdatedBy, vc))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.SysConfig {
	return predicate.SysConfig(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.SysConfig {
	return predicate.SysConfig(sql.FieldNotNull(FieldUpdatedBy))
}

// ConfigKeyEQ applies the EQ predicate on the "config_key" field.
func ConfigKeyEQ(v string) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldEQ(FieldConfigKey, v))
}

// ConfigKeyNEQ applies the NEQ predicate on the "config_key" field.
func ConfigKeyNEQ(v string) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldNEQ(FieldConfigKey, v))
}

// ConfigKeyIn applies the In predicate on the "config_key" field.
func ConfigKeyIn(vs ...string) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldIn(FieldConfigKey, vs...))
}

// ConfigKeyNotIn applies the NotIn predicate on the "config_key" field.
func ConfigKeyNotIn(vs ...string) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldNotIn(FieldConfigKey, vs...))
}

// ConfigKeyGT applies the GT predicate on the "config_key" field.
func ConfigKeyGT(v string) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldGT(FieldConfigKey, v))
}

// ConfigKeyGTE applies the GTE predicate on the "config_key" field.
func ConfigKeyGTE(v string) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldGTE(FieldConfigKey, v))
}

// ConfigKeyLT applies the LT predicate on the "config_key" field.
func ConfigKeyLT(v string) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldLT(FieldConfigKey, v))
}

// ConfigKeyLTE applies the LTE predicate on the "config_key" field.
func ConfigKeyLTE(v string) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldLTE(FieldConfigKey, v))
}

// ConfigKeyContains applies the Contains predicate on the "config_key" field.
func ConfigKeyContains(v string) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldContains(FieldConfigKey, v))
}

// ConfigKeyHasPrefix applies the HasPrefix predicate on the "config_key" field.
func ConfigKeyHasPrefix(v string) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldHasPrefix(FieldConfigKey, v))
}

// ConfigKeyHasSuffix applies the HasSuffix predicate on the "config_key" field.
func ConfigKeyHasSuffix(v string) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldHasSuffix(FieldConfigKey, v))
}

// ConfigKeyEqualFold applies the EqualFold predicate on the "config_key" field.
func ConfigKeyEqualFold(v string) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldEqualFold(FieldConfigKey, v))
}

// ConfigKeyContainsFold applies the ContainsFold predicate on the "config_key" field.
func ConfigKeyContainsFold(v string) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldContainsFold(FieldConfigKey, v))
}

// ConfigValueEQ applies the EQ predicate on the "config_value" field.
func ConfigValueEQ(v string) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldEQ(FieldConfigValue, v))
}

// ConfigValueNEQ applies the NEQ predicate on the "config_value" field.
func ConfigValueNEQ(v string) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldNEQ(FieldConfigValue, v))
}

// ConfigValueIn applies the In predicate on the "config_value" field.
func ConfigValueIn(vs ...string) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldIn(FieldConfigValue, vs...))
}

// ConfigValueNotIn applies the NotIn predicate on the "config_value" field.
func ConfigValueNotIn(vs ...string) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldNotIn(FieldConfigValue, vs...))
}

// ConfigValueGT applies the GT predicate on the "config_value" field.
func ConfigValueGT(v string) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldGT(FieldConfigValue, v))
}

// ConfigValueGTE applies the GTE predicate on the "config_value" field.
func ConfigValueGTE(v string) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldGTE(FieldConfigValue, v))
}

// ConfigValueLT applies the LT predicate on the "config_value" field.
func ConfigValueLT(v string) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldLT(FieldConfigValue, v))
}

// ConfigValueLTE applies the LTE predicate on the "config_value" field.
func ConfigValueLTE(v string) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldLTE(FieldConfigValue, v))
}

// ConfigValueContains applies the Contains predicate on the "config_value" field.
func ConfigValueContains(v string) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldContains(FieldConfigValue, v))
}

// ConfigValueHasPrefix applies the HasPrefix predicate on the "config_value" field.
func ConfigValueHasPrefix(v string) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldHasPrefix(FieldConfigValue, v))
}

// ConfigValueHasSuffix applies the HasSuffix predicate on the "config_value" field.
func ConfigValueHasSuffix(v string) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldHasSuffix(FieldConfigValue, v))
}

// ConfigValueEqualFold applies the EqualFold predicate on the "config_value" field.
func ConfigValueEqualFold(v string) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldEqualFold(FieldConfigValue, v))
}

// ConfigValueContainsFold applies the ContainsFold predicate on the "config_value" field.
func ConfigValueContainsFold(v string) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldContainsFold(FieldConfigValue, v))
}

// ConfigDescEQ applies the EQ predicate on the "config_desc" field.
func ConfigDescEQ(v string) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldEQ(FieldConfigDesc, v))
}

// ConfigDescNEQ applies the NEQ predicate on the "config_desc" field.
func ConfigDescNEQ(v string) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldNEQ(FieldConfigDesc, v))
}

// ConfigDescIn applies the In predicate on the "config_desc" field.
func ConfigDescIn(vs ...string) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldIn(FieldConfigDesc, vs...))
}

// ConfigDescNotIn applies the NotIn predicate on the "config_desc" field.
func ConfigDescNotIn(vs ...string) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldNotIn(FieldConfigDesc, vs...))
}

// ConfigDescGT applies the GT predicate on the "config_desc" field.
func ConfigDescGT(v string) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldGT(FieldConfigDesc, v))
}

// ConfigDescGTE applies the GTE predicate on the "config_desc" field.
func ConfigDescGTE(v string) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldGTE(FieldConfigDesc, v))
}

// ConfigDescLT applies the LT predicate on the "config_desc" field.
func ConfigDescLT(v string) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldLT(FieldConfigDesc, v))
}

// ConfigDescLTE applies the LTE predicate on the "config_desc" field.
func ConfigDescLTE(v string) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldLTE(FieldConfigDesc, v))
}

// ConfigDescContains applies the Contains predicate on the "config_desc" field.
func ConfigDescContains(v string) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldContains(FieldConfigDesc, v))
}

// ConfigDescHasPrefix applies the HasPrefix predicate on the "config_desc" field.
func ConfigDescHasPrefix(v string) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldHasPrefix(FieldConfigDesc, v))
}

// ConfigDescHasSuffix applies the HasSuffix predicate on the "config_desc" field.
func ConfigDescHasSuffix(v string) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldHasSuffix(FieldConfigDesc, v))
}

// ConfigDescIsNil applies the IsNil predicate on the "config_desc" field.
func ConfigDescIsNil() predicate.SysConfig {
	return predicate.SysConfig(sql.FieldIsNull(FieldConfigDesc))
}

// ConfigDescNotNil applies the NotNil predicate on the "config_desc" field.
func ConfigDescNotNil() predicate.SysConfig {
	return predicate.SysConfig(sql.FieldNotNull(FieldConfigDesc))
}

// ConfigDescEqualFold applies the EqualFold predicate on the "config_desc" field.
func ConfigDescEqualFold(v string) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldEqualFold(FieldConfigDesc, v))
}

// ConfigDescContainsFold applies the ContainsFold predicate on the "config_desc" field.
func ConfigDescContainsFold(v string) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldContainsFold(FieldConfigDesc, v))
}

// IsBuiltinEQ applies the EQ predicate on the "is_builtin" field.
func IsBuiltinEQ(v bool) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldEQ(FieldIsBuiltin, v))
}

// IsBuiltinNEQ applies the NEQ predicate on the "is_builtin" field.
func IsBuiltinNEQ(v bool) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldNEQ(FieldIsBuiltin, v))
}

// SortIDEQ applies the EQ predicate on the "sort_id" field.
func SortIDEQ(v int) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldEQ(FieldSortID, v))
}

// SortIDNEQ applies the NEQ predicate on the "sort_id" field.
func SortIDNEQ(v int) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldNEQ(FieldSortID, v))
}

// SortIDIn applies the In predicate on the "sort_id" field.
func SortIDIn(vs ...int) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldIn(FieldSortID, vs...))
}

// SortIDNotIn applies the NotIn predicate on the "sort_id" field.
func SortIDNotIn(vs ...int) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldNotIn(FieldSortID, vs...))
}

// SortIDGT applies the GT predicate on the "sort_id" field.
func SortIDGT(v int) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldGT(FieldSortID, v))
}

// SortIDGTE applies the GTE predicate on the "sort_id" field.
func SortIDGTE(v int) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldGTE(FieldSortID, v))
}

// SortIDLT applies the LT predicate on the "sort_id" field.
func SortIDLT(v int) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldLT(FieldSortID, v))
}

// SortIDLTE applies the LTE predicate on the "sort_id" field.
func SortIDLTE(v int) predicate.SysConfig {
	return predicate.SysConfig(sql.FieldLTE(FieldSortID, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SysConfig) predicate.SysConfig {
	return predicate.SysConfig(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SysConfig) predicate.SysConfig {
	return predicate.SysConfig(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SysConfig) predicate.SysConfig {
	return predicate.SysConfig(sql.NotPredicates(p))
}
