app:
  instance_id: prod-1

database:
  host: ""
  user: ""
  password: ""
  dbname: ""
  max_open_conns: 50
  max_idle_conns: 20

redis:
  addr: ""
  db: 0
  pool:
    size: 20

auth:
  jwt:
    secret: ""

log:
  level: info

cache:
  local_ttl: 30s
  remote_ttl: 5m
