app:
  instance_id: test-1

server:
  addr: ":18080"

database:
  dbname: "initra_test"
  max_open_conns: 10
  max_idle_conns: 5

redis:
  db: 2

auth:
  access_token_ttl: 10m
  jwt:
    secret: "change-me-test"

log:
  level: debug

cache:
  local_ttl: 30s
  remote_ttl: 2m

storage:
  local:
    root_dir: ./var/test-uploads

task:
  redis:
    db: 3
