// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/teamsillybees/initra/examples/internal/data/ent/migrate"
	"github.com/teamsillybees/initra/pkg/idgen"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/teamsillybees/initra/examples/internal/data/ent/sysconfig"
	"github.com/teamsillybees/initra/examples/internal/data/ent/sysdictcollection"
	"github.com/teamsillybees/initra/examples/internal/data/ent/sysdictitem"
	"github.com/teamsillybees/initra/examples/internal/data/ent/sysmenu"
	"github.com/teamsillybees/initra/examples/internal/data/ent/sysrole"
	"github.com/teamsillybees/initra/examples/internal/data/ent/sysrolemenu"
	"github.com/teamsillybees/initra/examples/internal/data/ent/sysuser"
	"github.com/teamsillybees/initra/examples/internal/data/ent/sysuserrole"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// SysConfig is the client for interacting with the SysConfig builders.
	SysConfig *SysConfigClient
	// SysDictCollection is the client for interacting with the SysDictCollection builders.
	SysDictCollection *SysDictCollectionClient
	// SysDictItem is the client for interacting with the SysDictItem builders.
	SysDictItem *SysDictItemClient
	// SysMenu is the client for interacting with the SysMenu builders.
	SysMenu *SysMenuClient
	// SysRole is the client for interacting with the SysRole builders.
	SysRole *SysRoleClient
	// SysRoleMenu is the client for interacting with the SysRoleMenu builders.
	SysRoleMenu *SysRoleMenuClient
	// SysUser is the client for interacting with the SysUser builders.
	SysUser *SysUserClient
	// SysUserRole is the client for interacting with the SysUserRole builders.
	SysUserRole *SysUserRoleClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.SysConfig = NewSysConfigClient(c.config)
	c.SysDictCollection = NewSysDictCollectionClient(c.config)
	c.SysDictItem = NewSysDictItemClient(c.config)
	c.SysMenu = NewSysMenuClient(c.config)
	c.SysRole = NewSysRoleClient(c.config)
	c.SysRoleMenu = NewSysRoleMenuClient(c.config)
	c.SysUser = NewSysUserClient(c.config)
	c.SysUserRole = NewSysUserRoleClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:               ctx,
		config:            cfg,
		SysConfig:         NewSysConfigClient(cfg),
		SysDictCollection: NewSysDictCollectionClient(cfg),
		SysDictItem:       NewSysDictItemClient(cfg),
		SysMenu:           NewSysMenuClient(cfg),
		SysRole:           NewSysRoleClient(cfg),
		SysRoleMenu:       NewSysRoleMenuClient(cfg),
		SysUser:           NewSysUserClient(cfg),
		SysUserRole:       NewSysUserRoleClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:               ctx,
		config:            cfg,
		SysConfig:         NewSysConfigClient(cfg),
		SysDictCollection: NewSysDictCollectionClient(cfg),
		SysDictItem:       NewSysDictItemClient(cfg),
		SysMenu:           NewSysMenuClient(cfg),
		SysRole:           NewSysRoleClient(cfg),
		SysRoleMenu:       NewSysRoleMenuClient(cfg),
		SysUser:           NewSysUserClient(cfg),
		SysUserRole:       NewSysUserRoleClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		SysConfig.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.SysConfig, c.SysDictCollection, c.SysDictItem, c.SysMenu, c.SysRole,
		c.SysRoleMenu, c.SysUser, c.SysUserRole,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.SysConfig, c.SysDictCollection, c.SysDictItem, c.SysMenu, c.SysRole,
		c.SysRoleMenu, c.SysUser, c.SysUserRole,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *SysConfigMutation:
		return c.SysConfig.mutate(ctx, m)
	case *SysDictCollectionMutation:
		return c.SysDictCollection.mutate(ctx, m)
	case *SysDictItemMutation:
		return c.SysDictItem.mutate(ctx, m)
	case *SysMenuMutation:
		return c.SysMenu.mutate(ctx, m)
	case *SysRoleMutation:
		return c.SysRole.mutate(ctx, m)
	case *SysRoleMenuMutation:
		return c.SysRoleMenu.mutate(ctx, m)
	case *SysUserMutation:
		return c.SysUser.mutate(ctx, m)
	case *SysUserRoleMutation:
		return c.SysUserRole.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// SysConfigClient is a client for the SysConfig schema.
type SysConfigClient struct {
	config
}

// NewSysConfigClient returns a client for the SysConfig from the given config.
func NewSysConfigClient(c config) *SysConfigClient {
	return &SysConfigClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `sysconfig.Hooks(f(g(h())))`.
func (c *SysConfigClient) Use(hooks ...Hook) {
	c.hooks.SysConfig = append(c.hooks.SysConfig, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `sysconfig.Intercept(f(g(h())))`.
func (c *SysConfigClient) Intercept(interceptors ...Interceptor) {
	c.inters.SysConfig = append(c.inters.SysConfig, interceptors...)
}

// Create returns a builder for creating a SysConfig entity.
func (c *SysConfigClient) Create() *SysConfigCreate {
	mutation := newSysConfigMutation(c.config, OpCreate)
	return &SysConfigCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of SysConfig entities.
func (c *SysConfigClient) CreateBulk(builders ...*SysConfigCreate) *SysConfigCreateBulk {
	return &SysConfigCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SysConfigClient) MapCreateBulk(slice any, setFunc func(*SysConfigCreate, int)) *SysConfigCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SysConfigCreateBulk{err: fmt.Errorf("calling to SysConfigClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SysConfigCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SysConfigCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for SysConfig.
func (c *SysConfigClient) Update() *SysConfigUpdate {
	mutation := newSysConfigMutation(c.config, OpUpdate)
	return &SysConfigUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SysConfigClient) UpdateOne(_m *SysConfig) *SysConfigUpdateOne {
	mutation := newSysConfigMutation(c.config, OpUpdateOne, withSysConfig(_m))
	return &SysConfigUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SysConfigClient) UpdateOneID(id idgen.ID) *SysConfigUpdateOne {
	mutation := newSysConfigMutation(c.config, OpUpdateOne, withSysConfigID(id))
	return &SysConfigUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for SysConfig.
func (c *SysConfigClient) Delete() *SysConfigDelete {
	mutation := newSysConfigMutation(c.config, OpDelete)
	return &SysConfigDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SysConfigClient) DeleteOne(_m *SysConfig) *SysConfigDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SysConfigClient) DeleteOneID(id idgen.ID) *SysConfigDeleteOne {
	builder := c.Delete().Where(sysconfig.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SysConfigDeleteOne{builder}
}

// Query returns a query builder for SysConfig.
func (c *SysConfigClient) Query() *SysConfigQuery {
	return &SysConfigQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSysConfig},
		inters: c.Interceptors(),
	}
}

// Get returns a SysConfig entity by its id.
func (c *SysConfigClient) Get(ctx context.Context, id idgen.ID) (*SysConfig, error) {
	return c.Query().Where(sysconfig.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SysConfigClient) GetX(ctx context.Context, id idgen.ID) *SysConfig {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *SysConfigClient) Hooks() []Hook {
	return c.hooks.SysConfig
}

// Interceptors returns the client interceptors.
func (c *SysConfigClient) Interceptors() []Interceptor {
	return c.inters.SysConfig
}

func (c *SysConfigClient) mutate(ctx context.Context, m *SysConfigMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SysConfigCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SysConfigUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SysConfigUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SysConfigDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown SysConfig mutation op: %q", m.Op())
	}
}

// SysDictCollectionClient is a client for the SysDictCollection schema.
type SysDictCollectionClient struct {
	config
}

// NewSysDictCollectionClient returns a client for the SysDictCollection from the given config.
func NewSysDictCollectionClient(c config) *SysDictCollectionClient {
	return &SysDictCollectionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `sysdictcollection.Hooks(f(g(h())))`.
func (c *SysDictCollectionClient) Use(hooks ...Hook) {
	c.hooks.SysDictCollection = append(c.hooks.SysDictCollection, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `sysdictcollection.Intercept(f(g(h())))`.
func (c *SysDictCollectionClient) Intercept(interceptors ...Interceptor) {
	c.inters.SysDictCollection = append(c.inters.SysDictCollection, interceptors...)
}

// Create returns a builder for creating a SysDictCollection entity.
func (c *SysDictCollectionClient) Create() *SysDictCollectionCreate {
	mutation := newSysDictCollectionMutation(c.config, OpCreate)
	return &SysDictCollectionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of SysDictCollection entities.
func (c *SysDictCollectionClient) CreateBulk(builders ...*SysDictCollectionCreate) *SysDictCollectionCreateBulk {
	return &SysDictCollectionCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SysDictCollectionClient) MapCreateBulk(slice any, setFunc func(*SysDictCollectionCreate, int)) *SysDictCollectionCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SysDictCollectionCreateBulk{err: fmt.Errorf("calling to SysDictCollectionClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SysDictCollectionCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SysDictCollectionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for SysDictCollection.
func (c *SysDictCollectionClient) Update() *SysDictCollectionUpdate {
	mutation := newSysDictCollectionMutation(c.config, OpUpdate)
	return &SysDictCollectionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SysDictCollectionClient) UpdateOne(_m *SysDictCollection) *SysDictCollectionUpdateOne {
	mutation := newSysDictCollectionMutation(c.config, OpUpdateOne, withSysDictCollection(_m))
	return &SysDictCollectionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SysDictCollectionClient) UpdateOneID(id idgen.ID) *SysDictCollectionUpdateOne {
	mutation := newSysDictCollectionMutation(c.config, OpUpdateOne, withSysDictCollectionID(id))
	return &SysDictCollectionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for SysDictCollection.
func (c *SysDictCollectionClient) Delete() *SysDictCollectionDelete {
	mutation := newSysDictCollectionMutation(c.config, OpDelete)
	return &SysDictCollectionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SysDictCollectionClient) DeleteOne(_m *SysDictCollection) *SysDictCollectionDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SysDictCollectionClient) DeleteOneID(id idgen.ID) *SysDictCollectionDeleteOne {
	builder := c.Delete().Where(sysdictcollection.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SysDictCollectionDeleteOne{builder}
}

// Query returns a query builder for SysDictCollection.
func (c *SysDictCollectionClient) Query() *SysDictCollectionQuery {
	return &SysDictCollectionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSysDictCollection},
		inters: c.Interceptors(),
	}
}

// Get returns a SysDictCollection entity by its id.
func (c *SysDictCollectionClient) Get(ctx context.Context, id idgen.ID) (*SysDictCollection, error) {
	return c.Query().Where(sysdictcollection.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SysDictCollectionClient) GetX(ctx context.Context, id idgen.ID) *SysDictCollection {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryItems queries the items edge of a SysDictCollection.
func (c *SysDictCollectionClient) QueryItems(_m *SysDictCollection) *SysDictItemQuery {
	query := (&SysDictItemClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(sysdictcollection.Table, sysdictcollection.FieldID, id),
			sqlgraph.To(sysdictitem.Table, sysdictitem.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, sysdictcollection.ItemsTable, sysdictcollection.ItemsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *SysDictCollectionClient) Hooks() []Hook {
	return c.hooks.SysDictCollection
}

// Interceptors returns the client interceptors.
func (c *SysDictCollectionClient) Interceptors() []Interceptor {
	return c.inters.SysDictCollection
}

func (c *SysDictCollectionClient) mutate(ctx context.Context, m *SysDictCollectionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SysDictCollectionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SysDictCollectionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SysDictCollectionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SysDictCollectionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown SysDictCollection mutation op: %q", m.Op())
	}
}

// SysDictItemClient is a client for the SysDictItem schema.
type SysDictItemClient struct {
	config
}

// NewSysDictItemClient returns a client for the SysDictItem from the given config.
func NewSysDictItemClient(c config) *SysDictItemClient {
	return &SysDictItemClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `sysdictitem.Hooks(f(g(h())))`.
func (c *SysDictItemClient) Use(hooks ...Hook) {
	c.hooks.SysDictItem = append(c.hooks.SysDictItem, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `sysdictitem.Intercept(f(g(h())))`.
func (c *SysDictItemClient) Intercept(interceptors ...Interceptor) {
	c.inters.SysDictItem = append(c.inters.SysDictItem, interceptors...)
}

// Create returns a builder for creating a SysDictItem entity.
func (c *SysDictItemClient) Create() *SysDictItemCreate {
	mutation := newSysDictItemMutation(c.config, OpCreate)
	return &SysDictItemCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of SysDictItem entities.
func (c *SysDictItemClient) CreateBulk(builders ...*SysDictItemCreate) *SysDictItemCreateBulk {
	return &SysDictItemCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SysDictItemClient) MapCreateBulk(slice any, setFunc func(*SysDictItemCreate, int)) *SysDictItemCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SysDictItemCreateBulk{err: fmt.Errorf("calling to SysDictItemClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SysDictItemCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SysDictItemCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for SysDictItem.
func (c *SysDictItemClient) Update() *SysDictItemUpdate {
	mutation := newSysDictItemMutation(c.config, OpUpdate)
	return &SysDictItemUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SysDictItemClient) UpdateOne(_m *SysDictItem) *SysDictItemUpdateOne {
	mutation := newSysDictItemMutation(c.config, OpUpdateOne, withSysDictItem(_m))
	return &SysDictItemUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SysDictItemClient) UpdateOneID(id idgen.ID) *SysDictItemUpdateOne {
	mutation := newSysDictItemMutation(c.config, OpUpdateOne, withSysDictItemID(id))
	return &SysDictItemUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for SysDictItem.
func (c *SysDictItemClient) Delete() *SysDictItemDelete {
	mutation := newSysDictItemMutation(c.config, OpDelete)
	return &SysDictItemDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SysDictItemClient) DeleteOne(_m *SysDictItem) *SysDictItemDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SysDictItemClient) DeleteOneID(id idgen.ID) *SysDictItemDeleteOne {
	builder := c.Delete().Where(sysdictitem.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SysDictItemDeleteOne{builder}
}

// Query returns a query builder for SysDictItem.
func (c *SysDictItemClient) Query() *SysDictItemQuery {
	return &SysDictItemQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSysDictItem},
		inters: c.Interceptors(),
	}
}

// Get returns a SysDictItem entity by its id.
func (c *SysDictItemClient) Get(ctx context.Context, id idgen.ID) (*SysDictItem, error) {
	return c.Query().Where(sysdictitem.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SysDictItemClient) GetX(ctx context.Context, id idgen.ID) *SysDictItem {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryCollection queries the collection edge of a SysDictItem.
func (c *SysDictItemClient) QueryCollection(_m *SysDictItem) *SysDictCollectionQuery {
	query := (&SysDictCollectionClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(sysdictitem.Table, sysdictitem.FieldID, id),
			sqlgraph.To(sysdictcollection.Table, sysdictcollection.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, sysdictitem.CollectionTable, sysdictitem.CollectionColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *SysDictItemClient) Hooks() []Hook {
	return c.hooks.SysDictItem
}

// Interceptors returns the client interceptors.
func (c *SysDictItemClient) Interceptors() []Interceptor {
	return c.inters.SysDictItem
}

func (c *SysDictItemClient) mutate(ctx context.Context, m *SysDictItemMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SysDictItemCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SysDictItemUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SysDictItemUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SysDictItemDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown SysDictItem mutation op: %q", m.Op())
	}
}

// SysMenuClient is a client for the SysMenu schema.
type SysMenuClient struct {
	config
}

// NewSysMenuClient returns a client for the SysMenu from the given config.
func NewSysMenuClient(c config) *SysMenuClient {
	return &SysMenuClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `sysmenu.Hooks(f(g(h())))`.
func (c *SysMenuClient) Use(hooks ...Hook) {
	c.hooks.SysMenu = append(c.hooks.SysMenu, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `sysmenu.Intercept(f(g(h())))`.
func (c *SysMenuClient) Intercept(interceptors ...Interceptor) {
	c.inters.SysMenu = append(c.inters.SysMenu, interceptors...)
}

// Create returns a builder for creating a SysMenu entity.
func (c *SysMenuClient) Create() *SysMenuCreate {
	mutation := newSysMenuMutation(c.config, OpCreate)
	return &SysMenuCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of SysMenu entities.
func (c *SysMenuClient) CreateBulk(builders ...*SysMenuCreate) *SysMenuCreateBulk {
	return &SysMenuCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SysMenuClient) MapCreateBulk(slice any, setFunc func(*SysMenuCreate, int)) *SysMenuCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SysMenuCreateBulk{err: fmt.Errorf("calling to SysMenuClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SysMenuCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SysMenuCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for SysMenu.
func (c *SysMenuClient) Update() *SysMenuUpdate {
	mutation := newSysMenuMutation(c.config, OpUpdate)
	return &SysMenuUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SysMenuClient) UpdateOne(_m *SysMenu) *SysMenuUpdateOne {
	mutation := newSysMenuMutation(c.config, OpUpdateOne, withSysMenu(_m))
	return &SysMenuUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SysMenuClient) UpdateOneID(id idgen.ID) *SysMenuUpdateOne {
	mutation := newSysMenuMutation(c.config, OpUpdateOne, withSysMenuID(id))
	return &SysMenuUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for SysMenu.
func (c *SysMenuClient) Delete() *SysMenuDelete {
	mutation := newSysMenuMutation(c.config, OpDelete)
	return &SysMenuDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SysMenuClient) DeleteOne(_m *SysMenu) *SysMenuDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SysMenuClient) DeleteOneID(id idgen.ID) *SysMenuDeleteOne {
	builder := c.Delete().Where(sysmenu.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SysMenuDeleteOne{builder}
}

// Query returns a query builder for SysMenu.
func (c *SysMenuClient) Query() *SysMenuQuery {
	return &SysMenuQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSysMenu},
		inters: c.Interceptors(),
	}
}

// Get returns a SysMenu entity by its id.
func (c *SysMenuClient) Get(ctx context.Context, id idgen.ID) (*SysMenu, error) {
	return c.Query().Where(sysmenu.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SysMenuClient) GetX(ctx context.Context, id idgen.ID) *SysMenu {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryParent queries the parent edge of a SysMenu.
func (c *SysMenuClient) QueryParent(_m *SysMenu) *SysMenuQuery {
	query := (&SysMenuClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(sysmenu.Table, sysmenu.FieldID, id),
			sqlgraph.To(sysmenu.Table, sysmenu.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, sysmenu.ParentTable, sysmenu.ParentColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryChildren queries the children edge of a SysMenu.
func (c *SysMenuClient) QueryChildren(_m *SysMenu) *SysMenuQuery {
	query := (&SysMenuClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(sysmenu.Table, sysmenu.FieldID, id),
			sqlgraph.To(sysmenu.Table, sysmenu.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, sysmenu.ChildrenTable, sysmenu.ChildrenColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryRoleMenus queries the role_menus edge of a SysMenu.
func (c *SysMenuClient) QueryRoleMenus(_m *SysMenu) *SysRoleMenuQuery {
	query := (&SysRoleMenuClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(sysmenu.Table, sysmenu.FieldID, id),
			sqlgraph.To(sysrolemenu.Table, sysrolemenu.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, sysmenu.RoleMenusTable, sysmenu.RoleMenusColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *SysMenuClient) Hooks() []Hook {
	return c.hooks.SysMenu
}

// Interceptors returns the client interceptors.
func (c *SysMenuClient) Interceptors() []Interceptor {
	return c.inters.SysMenu
}

func (c *SysMenuClient) mutate(ctx context.Context, m *SysMenuMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SysMenuCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SysMenuUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SysMenuUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SysMenuDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown SysMenu mutation op: %q", m.Op())
	}
}

// SysRoleClient is a client for the SysRole schema.
type SysRoleClient struct {
	config
}

// NewSysRoleClient returns a client for the SysRole from the given config.
func NewSysRoleClient(c config) *SysRoleClient {
	return &SysRoleClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `sysrole.Hooks(f(g(h())))`.
func (c *SysRoleClient) Use(hooks ...Hook) {
	c.hooks.SysRole = append(c.hooks.SysRole, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `sysrole.Intercept(f(g(h())))`.
func (c *SysRoleClient) Intercept(interceptors ...Interceptor) {
	c.inters.SysRole = append(c.inters.SysRole, interceptors...)
}

// Create returns a builder for creating a SysRole entity.
func (c *SysRoleClient) Create() *SysRoleCreate {
	mutation := newSysRoleMutation(c.config, OpCreate)
	return &SysRoleCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of SysRole entities.
func (c *SysRoleClient) CreateBulk(builders ...*SysRoleCreate) *SysRoleCreateBulk {
	return &SysRoleCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SysRoleClient) MapCreateBulk(slice any, setFunc func(*SysRoleCreate, int)) *SysRoleCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SysRoleCreateBulk{err: fmt.Errorf("calling to SysRoleClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SysRoleCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SysRoleCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for SysRole.
func (c *SysRoleClient) Update() *SysRoleUpdate {
	mutation := newSysRoleMutation(c.config, OpUpdate)
	return &SysRoleUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SysRoleClient) UpdateOne(_m *SysRole) *SysRoleUpdateOne {
	mutation := newSysRoleMutation(c.config, OpUpdateOne, withSysRole(_m))
	return &SysRoleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SysRoleClient) UpdateOneID(id idgen.ID) *SysRoleUpdateOne {
	mutation := newSysRoleMutation(c.config, OpUpdateOne, withSysRoleID(id))
	return &SysRoleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for SysRole.
func (c *SysRoleClient) Delete() *SysRoleDelete {
	mutation := newSysRoleMutation(c.config, OpDelete)
	return &SysRoleDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SysRoleClient) DeleteOne(_m *SysRole) *SysRoleDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SysRoleClient) DeleteOneID(id idgen.ID) *SysRoleDeleteOne {
	builder := c.Delete().Where(sysrole.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SysRoleDeleteOne{builder}
}

// Query returns a query builder for SysRole.
func (c *SysRoleClient) Query() *SysRoleQuery {
	return &SysRoleQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSysRole},
		inters: c.Interceptors(),
	}
}

// Get returns a SysRole entity by its id.
func (c *SysRoleClient) Get(ctx context.Context, id idgen.ID) (*SysRole, error) {
	return c.Query().Where(sysrole.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SysRoleClient) GetX(ctx context.Context, id idgen.ID) *SysRole {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUserRoles queries the user_roles edge of a SysRole.
func (c *SysRoleClient) QueryUserRoles(_m *SysRole) *SysUserRoleQuery {
	query := (&SysUserRoleClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(sysrole.Table, sysrole.FieldID, id),
			sqlgraph.To(sysuserrole.Table, sysuserrole.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, sysrole.UserRolesTable, sysrole.UserRolesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryRoleMenus queries the role_menus edge of a SysRole.
func (c *SysRoleClient) QueryRoleMenus(_m *SysRole) *SysRoleMenuQuery {
	query := (&SysRoleMenuClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(sysrole.Table, sysrole.FieldID, id),
			sqlgraph.To(sysrolemenu.Table, sysrolemenu.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, sysrole.RoleMenusTable, sysrole.RoleMenusColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *SysRoleClient) Hooks() []Hook {
	return c.hooks.SysRole
}

// Interceptors returns the client interceptors.
func (c *SysRoleClient) Interceptors() []Interceptor {
	return c.inters.SysRole
}

func (c *SysRoleClient) mutate(ctx context.Context, m *SysRoleMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SysRoleCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SysRoleUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SysRoleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SysRoleDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown SysRole mutation op: %q", m.Op())
	}
}

// SysRoleMenuClient is a client for the SysRoleMenu schema.
type SysRoleMenuClient struct {
	config
}

// NewSysRoleMenuClient returns a client for the SysRoleMenu from the given config.
func NewSysRoleMenuClient(c config) *SysRoleMenuClient {
	return &SysRoleMenuClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `sysrolemenu.Hooks(f(g(h())))`.
func (c *SysRoleMenuClient) Use(hooks ...Hook) {
	c.hooks.SysRoleMenu = append(c.hooks.SysRoleMenu, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `sysrolemenu.Intercept(f(g(h())))`.
func (c *SysRoleMenuClient) Intercept(interceptors ...Interceptor) {
	c.inters.SysRoleMenu = append(c.inters.SysRoleMenu, interceptors...)
}

// Create returns a builder for creating a SysRoleMenu entity.
func (c *SysRoleMenuClient) Create() *SysRoleMenuCreate {
	mutation := newSysRoleMenuMutation(c.config, OpCreate)
	return &SysRoleMenuCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of SysRoleMenu entities.
func (c *SysRoleMenuClient) CreateBulk(builders ...*SysRoleMenuCreate) *SysRoleMenuCreateBulk {
	return &SysRoleMenuCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SysRoleMenuClient) MapCreateBulk(slice any, setFunc func(*SysRoleMenuCreate, int)) *SysRoleMenuCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SysRoleMenuCreateBulk{err: fmt.Errorf("calling to SysRoleMenuClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SysRoleMenuCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SysRoleMenuCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for SysRoleMenu.
func (c *SysRoleMenuClient) Update() *SysRoleMenuUpdate {
	mutation := newSysRoleMenuMutation(c.config, OpUpdate)
	return &SysRoleMenuUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SysRoleMenuClient) UpdateOne(_m *SysRoleMenu) *SysRoleMenuUpdateOne {
	mutation := newSysRoleMenuMutation(c.config, OpUpdateOne, withSysRoleMenu(_m))
	return &SysRoleMenuUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SysRoleMenuClient) UpdateOneID(id idgen.ID) *SysRoleMenuUpdateOne {
	mutation := newSysRoleMenuMutation(c.config, OpUpdateOne, withSysRoleMenuID(id))
	return &SysRoleMenuUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for SysRoleMenu.
func (c *SysRoleMenuClient) Delete() *SysRoleMenuDelete {
	mutation := newSysRoleMenuMutation(c.config, OpDelete)
	return &SysRoleMenuDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SysRoleMenuClient) DeleteOne(_m *SysRoleMenu) *SysRoleMenuDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SysRoleMenuClient) DeleteOneID(id idgen.ID) *SysRoleMenuDeleteOne {
	builder := c.Delete().Where(sysrolemenu.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SysRoleMenuDeleteOne{builder}
}

// Query returns a query builder for SysRoleMenu.
func (c *SysRoleMenuClient) Query() *SysRoleMenuQuery {
	return &SysRoleMenuQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSysRoleMenu},
		inters: c.Interceptors(),
	}
}

// Get returns a SysRoleMenu entity by its id.
func (c *SysRoleMenuClient) Get(ctx context.Context, id idgen.ID) (*SysRoleMenu, error) {
	return c.Query().Where(sysrolemenu.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SysRoleMenuClient) GetX(ctx context.Context, id idgen.ID) *SysRoleMenu {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryRole queries the role edge of a SysRoleMenu.
func (c *SysRoleMenuClient) QueryRole(_m *SysRoleMenu) *SysRoleQuery {
	query := (&SysRoleClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(sysrolemenu.Table, sysrolemenu.FieldID, id),
			sqlgraph.To(sysrole.Table, sysrole.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, sysrolemenu.RoleTable, sysrolemenu.RoleColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryMenu queries the menu edge of a SysRoleMenu.
func (c *SysRoleMenuClient) QueryMenu(_m *SysRoleMenu) *SysMenuQuery {
	query := (&SysMenuClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(sysrolemenu.Table, sysrolemenu.FieldID, id),
			sqlgraph.To(sysmenu.Table, sysmenu.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, sysrolemenu.MenuTable, sysrolemenu.MenuColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *SysRoleMenuClient) Hooks() []Hook {
	return c.hooks.SysRoleMenu
}

// Interceptors returns the client interceptors.
func (c *SysRoleMenuClient) Interceptors() []Interceptor {
	return c.inters.SysRoleMenu
}

func (c *SysRoleMenuClient) mutate(ctx context.Context, m *SysRoleMenuMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SysRoleMenuCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SysRoleMenuUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SysRoleMenuUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SysRoleMenuDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown SysRoleMenu mutation op: %q", m.Op())
	}
}

// SysUserClient is a client for the SysUser schema.
type SysUserClient struct {
	config
}

// NewSysUserClient returns a client for the SysUser from the given config.
func NewSysUserClient(c config) *SysUserClient {
	return &SysUserClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `sysuser.Hooks(f(g(h())))`.
func (c *SysUserClient) Use(hooks ...Hook) {
	c.hooks.SysUser = append(c.hooks.SysUser, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `sysuser.Intercept(f(g(h())))`.
func (c *SysUserClient) Intercept(interceptors ...Interceptor) {
	c.inters.SysUser = append(c.inters.SysUser, interceptors...)
}

// Create returns a builder for creating a SysUser entity.
func (c *SysUserClient) Create() *SysUserCreate {
	mutation := newSysUserMutation(c.config, OpCreate)
	return &SysUserCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of SysUser entities.
func (c *SysUserClient) CreateBulk(builders ...*SysUserCreate) *SysUserCreateBulk {
	return &SysUserCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SysUserClient) MapCreateBulk(slice any, setFunc func(*SysUserCreate, int)) *SysUserCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SysUserCreateBulk{err: fmt.Errorf("calling to SysUserClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SysUserCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SysUserCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for SysUser.
func (c *SysUserClient) Update() *SysUserUpdate {
	mutation := newSysUserMutation(c.config, OpUpdate)
	return &SysUserUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SysUserClient) UpdateOne(_m *SysUser) *SysUserUpdateOne {
	mutation := newSysUserMutation(c.config, OpUpdateOne, withSysUser(_m))
	return &SysUserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SysUserClient) UpdateOneID(id idgen.ID) *SysUserUpdateOne {
	mutation := newSysUserMutation(c.config, OpUpdateOne, withSysUserID(id))
	return &SysUserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for SysUser.
func (c *SysUserClient) Delete() *SysUserDelete {
	mutation := newSysUserMutation(c.config, OpDelete)
	return &SysUserDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SysUserClient) DeleteOne(_m *SysUser) *SysUserDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SysUserClient) DeleteOneID(id idgen.ID) *SysUserDeleteOne {
	builder := c.Delete().Where(sysuser.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SysUserDeleteOne{builder}
}

// Query returns a query builder for SysUser.
func (c *SysUserClient) Query() *SysUserQuery {
	return &SysUserQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSysUser},
		inters: c.Interceptors(),
	}
}

// Get returns a SysUser entity by its id.
func (c *SysUserClient) Get(ctx context.Context, id idgen.ID) (*SysUser, error) {
	return c.Query().Where(sysuser.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SysUserClient) GetX(ctx context.Context, id idgen.ID) *SysUser {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUserRoles queries the user_roles edge of a SysUser.
func (c *SysUserClient) QueryUserRoles(_m *SysUser) *SysUserRoleQuery {
	query := (&SysUserRoleClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(sysuser.Table, sysuser.FieldID, id),
			sqlgraph.To(sysuserrole.Table, sysuserrole.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, sysuser.UserRolesTable, sysuser.UserRolesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *SysUserClient) Hooks() []Hook {
	return c.hooks.SysUser
}

// Interceptors returns the client interceptors.
func (c *SysUserClient) Interceptors() []Interceptor {
	return c.inters.SysUser
}

func (c *SysUserClient) mutate(ctx context.Context, m *SysUserMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SysUserCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SysUserUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SysUserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SysUserDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown SysUser mutation op: %q", m.Op())
	}
}

// SysUserRoleClient is a client for the SysUserRole schema.
type SysUserRoleClient struct {
	config
}

// NewSysUserRoleClient returns a client for the SysUserRole from the given config.
func NewSysUserRoleClient(c config) *SysUserRoleClient {
	return &SysUserRoleClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `sysuserrole.Hooks(f(g(h())))`.
func (c *SysUserRoleClient) Use(hooks ...Hook) {
	c.hooks.SysUserRole = append(c.hooks.SysUserRole, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `sysuserrole.Intercept(f(g(h())))`.
func (c *SysUserRoleClient) Intercept(interceptors ...Interceptor) {
	c.inters.SysUserRole = append(c.inters.SysUserRole, interceptors...)
}

// Create returns a builder for creating a SysUserRole entity.
func (c *SysUserRoleClient) Create() *SysUserRoleCreate {
	mutation := newSysUserRoleMutation(c.config, OpCreate)
	return &SysUserRoleCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of SysUserRole entities.
func (c *SysUserRoleClient) CreateBulk(builders ...*SysUserRoleCreate) *SysUserRoleCreateBulk {
	return &SysUserRoleCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SysUserRoleClient) MapCreateBulk(slice any, setFunc func(*SysUserRoleCreate, int)) *SysUserRoleCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SysUserRoleCreateBulk{err: fmt.Errorf("calling to SysUserRoleClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SysUserRoleCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SysUserRoleCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for SysUserRole.
func (c *SysUserRoleClient) Update() *SysUserRoleUpdate {
	mutation := newSysUserRoleMutation(c.config, OpUpdate)
	return &SysUserRoleUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SysUserRoleClient) UpdateOne(_m *SysUserRole) *SysUserRoleUpdateOne {
	mutation := newSysUserRoleMutation(c.config, OpUpdateOne, withSysUserRole(_m))
	return &SysUserRoleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SysUserRoleClient) UpdateOneID(id idgen.ID) *SysUserRoleUpdateOne {
	mutation := newSysUserRoleMutation(c.config, OpUpdateOne, withSysUserRoleID(id))
	return &SysUserRoleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for SysUserRole.
func (c *SysUserRoleClient) Delete() *SysUserRoleDelete {
	mutation := newSysUserRoleMutation(c.config, OpDelete)
	return &SysUserRoleDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SysUserRoleClient) DeleteOne(_m *SysUserRole) *SysUserRoleDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SysUserRoleClient) DeleteOneID(id idgen.ID) *SysUserRoleDeleteOne {
	builder := c.Delete().Where(sysuserrole.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SysUserRoleDeleteOne{builder}
}

// Query returns a query builder for SysUserRole.
func (c *SysUserRoleClient) Query() *SysUserRoleQuery {
	return &SysUserRoleQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSysUserRole},
		inters: c.Interceptors(),
	}
}

// Get returns a SysUserRole entity by its id.
func (c *SysUserRoleClient) Get(ctx context.Context, id idgen.ID) (*SysUserRole, error) {
	return c.Query().Where(sysuserrole.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SysUserRoleClient) GetX(ctx context.Context, id idgen.ID) *SysUserRole {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUser queries the user edge of a SysUserRole.
func (c *SysUserRoleClient) QueryUser(_m *SysUserRole) *SysUserQuery {
	query := (&SysUserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(sysuserrole.Table, sysuserrole.FieldID, id),
			sqlgraph.To(sysuser.Table, sysuser.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, sysuserrole.UserTable, sysuserrole.UserColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryRole queries the role edge of a SysUserRole.
func (c *SysUserRoleClient) QueryRole(_m *SysUserRole) *SysRoleQuery {
	query := (&SysRoleClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(sysuserrole.Table, sysuserrole.FieldID, id),
			sqlgraph.To(sysrole.Table, sysrole.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, sysuserrole.RoleTable, sysuserrole.RoleColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *SysUserRoleClient) Hooks() []Hook {
	return c.hooks.SysUserRole
}

// Interceptors returns the client interceptors.
func (c *SysUserRoleClient) Interceptors() []Interceptor {
	return c.inters.SysUserRole
}

func (c *SysUserRoleClient) mutate(ctx context.Context, m *SysUserRoleMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SysUserRoleCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SysUserRoleUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SysUserRoleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SysUserRoleDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown SysUserRole mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		SysConfig, SysDictCollection, SysDictItem, SysMenu, SysRole, SysRoleMenu,
		SysUser, SysUserRole []ent.Hook
	}
	inters struct {
		SysConfig, SysDictCollection, SysDictItem, SysMenu, SysRole, SysRoleMenu,
		SysUser, SysUserRole []ent.Interceptor
	}
)
