// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/teamsillybees/initra/examples/internal/data/ent/sysconfig"
)

// 系统配置表，用于集中存放可在后台维护的运行时配置。
type SysConfig struct {
	config `json:"-"`
	// ID of the ent.
	// 雪花算法生成的主键 ID。
	ID int64 `json:"id,omitempty"`
	// 逻辑删除时间，NULL 表示未删除。
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// 创建时间。
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 最后更新时间。
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 创建人用户 ID。
	CreatedBy *int64 `json:"created_by,omitempty"`
	// 最后更新人用户 ID。
	UpdatedBy *int64 `json:"updated_by,omitempty"`
	// 配置键，程序通过该键读取配置。
	ConfigKey string `json:"config_key,omitempty"`
	// 配置值。
	ConfigValue string `json:"config_value,omitempty"`
	// 配置项描述。
	ConfigDesc *string `json:"config_desc,omitempty"`
	// 是否为系统内置配置，内置配置通常不允许删除。
	IsBuiltin bool `json:"is_builtin,omitempty"`
	// 排序值。
	SortID       int `json:"sort_id,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SysConfig) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case sysconfig.FieldIsBuiltin:
			values[i] = new(sql.NullBool)
		case sysconfig.FieldID, sysconfig.FieldCreatedBy, sysconfig.FieldUpdatedBy, sysconfig.FieldSortID:
			values[i] = new(sql.NullInt64)
		case sysconfig.FieldConfigKey, sysconfig.FieldConfigValue, sysconfig.FieldConfigDesc:
			values[i] = new(sql.NullString)
		case sysconfig.FieldDeletedAt, sysconfig.FieldCreatedAt, sysconfig.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SysConfig fields.
func (_m *SysConfig) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case sysconfig.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case sysconfig.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case sysconfig.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case sysconfig.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case sysconfig.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = new(int64)
				*_m.CreatedBy = value.Int64
			}
		case sysconfig.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				_m.UpdatedBy = new(int64)
				*_m.UpdatedBy = value.Int64
			}
		case sysconfig.FieldConfigKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field config_key", values[i])
			} else if value.Valid {
				_m.ConfigKey = value.String
			}
		case sysconfig.FieldConfigValue:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field config_value", values[i])
			} else if value.Valid {
				_m.ConfigValue = value.String
			}
		case sysconfig.FieldConfigDesc:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field config_desc", values[i])
			} else if value.Valid {
				_m.ConfigDesc = new(string)
				*_m.ConfigDesc = value.String
			}
		case sysconfig.FieldIsBuiltin:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_builtin", values[i])
			} else if value.Valid {
				_m.IsBuiltin = value.Bool
			}
		case sysconfig.FieldSortID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort_id", values[i])
			} else if value.Valid {
				_m.SortID = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SysConfig.
// This includes values selected through modifiers, order, etc.
func (_m *SysConfig) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this SysConfig.
// Note that you need to call SysConfig.Unwrap() before calling this method if this SysConfig
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SysConfig) Update() *SysConfigUpdateOne {
	return NewSysConfigClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SysConfig entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SysConfig) Unwrap() *SysConfig {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SysConfig is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SysConfig) String() string {
	var builder strings.Builder
	builder.WriteString("SysConfig(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.CreatedBy; v != nil {
		builder.WriteString("created_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.UpdatedBy; v != nil {
		builder.WriteString("updated_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("config_key=")
	builder.WriteString(_m.ConfigKey)
	builder.WriteString(", ")
	builder.WriteString("config_value=")
	builder.WriteString(_m.ConfigValue)
	builder.WriteString(", ")
	if v := _m.ConfigDesc; v != nil {
		builder.WriteString("config_desc=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("is_builtin=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsBuiltin))
	builder.WriteString(", ")
	builder.WriteString("sort_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SortID))
	builder.WriteByte(')')
	return builder.String()
}

// SysConfigs is a parsable slice of SysConfig.
type SysConfigs []*SysConfig
