// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/teamsillybees/initra/examples/internal/data/ent/sysdictcollection"
	"github.com/teamsillybees/initra/examples/internal/data/ent/sysdictitem"
	"github.com/teamsillybees/initra/pkg/idgen"
)

// SysDictItemCreate is the builder for creating a SysDictItem entity.
type SysDictItemCreate struct {
	config
	mutation *SysDictItemMutation
	hooks    []Hook
}

// SetCollectionID sets the "collection_id" field.
func (_c *SysDictItemCreate) SetCollectionID(v idgen.ID) *SysDictItemCreate {
	_c.mutation.SetCollectionID(v)
	return _c
}

// SetCollectionCode sets the "collection_code" field.
func (_c *SysDictItemCreate) SetCollectionCode(v string) *SysDictItemCreate {
	_c.mutation.SetCollectionCode(v)
	return _c
}

// SetCode sets the "code" field.
func (_c *SysDictItemCreate) SetCode(v string) *SysDictItemCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetParentCode sets the "parent_code" field.
func (_c *SysDictItemCreate) SetParentCode(v string) *SysDictItemCreate {
	_c.mutation.SetParentCode(v)
	return _c
}

// SetNillableParentCode sets the "parent_code" field if the given value is not nil.
func (_c *SysDictItemCreate) SetNillableParentCode(v *string) *SysDictItemCreate {
	if v != nil {
		_c.SetParentCode(*v)
	}
	return _c
}

// SetLabel sets the "label" field.
func (_c *SysDictItemCreate) SetLabel(v string) *SysDictItemCreate {
	_c.mutation.SetLabel(v)
	return _c
}

// SetIsDefaultValue sets the "is_default_value" field.
func (_c *SysDictItemCreate) SetIsDefaultValue(v bool) *SysDictItemCreate {
	_c.mutation.SetIsDefaultValue(v)
	return _c
}

// SetNillableIsDefaultValue sets the "is_default_value" field if the given value is not nil.
func (_c *SysDictItemCreate) SetNillableIsDefaultValue(v *bool) *SysDictItemCreate {
	if v != nil {
		_c.SetIsDefaultValue(*v)
	}
	return _c
}

// SetIsEnable sets the "is_enable" field.
func (_c *SysDictItemCreate) SetIsEnable(v bool) *SysDictItemCreate {
	_c.mutation.SetIsEnable(v)
	return _c
}

// SetNillableIsEnable sets the "is_enable" field if the given value is not nil.
func (_c *SysDictItemCreate) SetNillableIsEnable(v *bool) *SysDictItemCreate {
	if v != nil {
		_c.SetIsEnable(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *SysDictItemCreate) SetDescription(v string) *SysDictItemCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *SysDictItemCreate) SetNillableDescription(v *string) *SysDictItemCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetSortID sets the "sort_id" field.
func (_c *SysDictItemCreate) SetSortID(v int32) *SysDictItemCreate {
	_c.mutation.SetSortID(v)
	return _c
}

// SetNillableSortID sets the "sort_id" field if the given value is not nil.
func (_c *SysDictItemCreate) SetNillableSortID(v *int32) *SysDictItemCreate {
	if v != nil {
		_c.SetSortID(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *SysDictItemCreate) SetDeletedAt(v time.Time) *SysDictItemCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *SysDictItemCreate) SetNillableDeletedAt(v *time.Time) *SysDictItemCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SysDictItemCreate) SetCreatedAt(v time.Time) *SysDictItemCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SysDictItemCreate) SetNillableCreatedAt(v *time.Time) *SysDictItemCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SysDictItemCreate) SetUpdatedAt(v time.Time) *SysDictItemCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SysDictItemCreate) SetNillableUpdatedAt(v *time.Time) *SysDictItemCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *SysDictItemCreate) SetCreatedBy(v idgen.ID) *SysDictItemCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *SysDictItemCreate) SetNillableCreatedBy(v *idgen.ID) *SysDictItemCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *SysDictItemCreate) SetUpdatedBy(v idgen.ID) *SysDictItemCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *SysDictItemCreate) SetNillableUpdatedBy(v *idgen.ID) *SysDictItemCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SysDictItemCreate) SetID(v idgen.ID) *SysDictItemCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *SysDictItemCreate) SetNillableID(v *idgen.ID) *SysDictItemCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetCollection sets the "collection" edge to the SysDictCollection entity.
func (_c *SysDictItemCreate) SetCollection(v *SysDictCollection) *SysDictItemCreate {
	return _c.SetCollectionID(v.ID)
}

// Mutation returns the SysDictItemMutation object of the builder.
func (_c *SysDictItemCreate) Mutation() *SysDictItemMutation {
	return _c.mutation
}

// Save creates the SysDictItem in the database.
func (_c *SysDictItemCreate) Save(ctx context.Context) (*SysDictItem, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SysDictItemCreate) SaveX(ctx context.Context) *SysDictItem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SysDictItemCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SysDictItemCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SysDictItemCreate) defaults() {
	if _, ok := _c.mutation.ParentCode(); !ok {
		v := sysdictitem.DefaultParentCode
		_c.mutation.SetParentCode(v)
	}
	if _, ok := _c.mutation.IsDefaultValue(); !ok {
		v := sysdictitem.DefaultIsDefaultValue
		_c.mutation.SetIsDefaultValue(v)
	}
	if _, ok := _c.mutation.IsEnable(); !ok {
		v := sysdictitem.DefaultIsEnable
		_c.mutation.SetIsEnable(v)
	}
	if _, ok := _c.mutation.SortID(); !ok {
		v := sysdictitem.DefaultSortID
		_c.mutation.SetSortID(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := sysdictitem.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := sysdictitem.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := sysdictitem.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SysDictItemCreate) check() error {
	if _, ok := _c.mutation.CollectionID(); !ok {
		return &ValidationError{Name: "collection_id", err: errors.New(`ent: missing required field "SysDictItem.collection_id"`)}
	}
	if v, ok := _c.mutation.CollectionID(); ok {
		if err := sysdictitem.CollectionIDValidator(int64(v)); err != nil {
			return &ValidationError{Name: "collection_id", err: fmt.Errorf(`ent: validator failed for field "SysDictItem.collection_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CollectionCode(); !ok {
		return &ValidationError{Name: "collection_code", err: errors.New(`ent: missing required field "SysDictItem.collection_code"`)}
	}
	if v, ok := _c.mutation.CollectionCode(); ok {
		if err := sysdictitem.CollectionCodeValidator(v); err != nil {
			return &ValidationError{Name: "collection_code", err: fmt.Errorf(`ent: validator failed for field "SysDictItem.collection_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "SysDictItem.code"`)}
	}
	if v, ok := _c.mutation.Code(); ok {
		if err := sysdictitem.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "SysDictItem.code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ParentCode(); !ok {
		return &ValidationError{Name: "parent_code", err: errors.New(`ent: missing required field "SysDictItem.parent_code"`)}
	}
	if v, ok := _c.mutation.ParentCode(); ok {
		if err := sysdictitem.ParentCodeValidator(v); err != nil {
			return &ValidationError{Name: "parent_code", err: fmt.Errorf(`ent: validator failed for field "SysDictItem.parent_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Label(); !ok {
		return &ValidationError{Name: "label", err: errors.New(`ent: missing required field "SysDictItem.label"`)}
	}
	if v, ok := _c.mutation.Label(); ok {
		if err := sysdictitem.LabelValidator(v); err != nil {
			return &ValidationError{Name: "label", err: fmt.Errorf(`ent: validator failed for field "SysDictItem.label": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsDefaultValue(); !ok {
		return &ValidationError{Name: "is_default_value", err: errors.New(`ent: missing required field "SysDictItem.is_default_value"`)}
	}
	if _, ok := _c.mutation.IsEnable(); !ok {
		return &ValidationError{Name: "is_enable", err: errors.New(`ent: missing required field "SysDictItem.is_enable"`)}
	}
	if _, ok := _c.mutation.SortID(); !ok {
		return &ValidationError{Name: "sort_id", err: errors.New(`ent: missing required field "SysDictItem.sort_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SysDictItem.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SysDictItem.updated_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := sysdictitem.IDValidator(int64(v)); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "SysDictItem.id": %w`, err)}
		}
	}
	if len(_c.mutation.CollectionIDs()) == 0 {
		return &ValidationError{Name: "collection", err: errors.New(`ent: missing required edge "SysDictItem.collection"`)}
	}
	return nil
}

func (_c *SysDictItemCreate) sqlSave(ctx context.Context) (*SysDictItem, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = idgen.ID(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SysDictItemCreate) createSpec() (*SysDictItem, *sqlgraph.CreateSpec) {
	var (
		_node = &SysDictItem{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(sysdictitem.Table, sqlgraph.NewFieldSpec(sysdictitem.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CollectionCode(); ok {
		_spec.SetField(sysdictitem.FieldCollectionCode, field.TypeString, value)
		_node.CollectionCode = value
	}
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(sysdictitem.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := _c.mutation.ParentCode(); ok {
		_spec.SetField(sysdictitem.FieldParentCode, field.TypeString, value)
		_node.ParentCode = value
	}
	if value, ok := _c.mutation.Label(); ok {
		_spec.SetField(sysdictitem.FieldLabel, field.TypeString, value)
		_node.Label = value
	}
	if value, ok := _c.mutation.IsDefaultValue(); ok {
		_spec.SetField(sysdictitem.FieldIsDefaultValue, field.TypeBool, value)
		_node.IsDefaultValue = value
	}
	if value, ok := _c.mutation.IsEnable(); ok {
		_spec.SetField(sysdictitem.FieldIsEnable, field.TypeBool, value)
		_node.IsEnable = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(sysdictitem.FieldDescription, field.TypeString, value)
		_node.Description = &value
	}
	if value, ok := _c.mutation.SortID(); ok {
		_spec.SetField(sysdictitem.FieldSortID, field.TypeInt32, value)
		_node.SortID = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(sysdictitem.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(sysdictitem.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(sysdictitem.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(sysdictitem.FieldCreatedBy, field.TypeInt64, value)
		_node.CreatedBy = &value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(sysdictitem.FieldUpdatedBy, field.TypeInt64, value)
		_node.UpdatedBy = &value
	}
	if nodes := _c.mutation.CollectionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   sysdictitem.CollectionTable,
			Columns: []string{sysdictitem.CollectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sysdictcollection.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CollectionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SysDictItemCreateBulk is the builder for creating many SysDictItem entities in bulk.
type SysDictItemCreateBulk struct {
	config
	err      error
	builders []*SysDictItemCreate
}

// Save creates the SysDictItem entities in the database.
func (_c *SysDictItemCreateBulk) Save(ctx context.Context) ([]*SysDictItem, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SysDictItem, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SysDictItemMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = idgen.ID(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SysDictItemCreateBulk) SaveX(ctx context.Context) []*SysDictItem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SysDictItemCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SysDictItemCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
