// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/teamsillybees/initra/examples/internal/data/ent/sysdictcollection"
	"github.com/teamsillybees/initra/pkg/idgen"
)

// 系统字典集表，用于定义一类字典的元信息。
type SysDictCollection struct {
	config `json:"-"`
	// ID of the ent.
	// 雪花算法生成的主键 ID。
	ID idgen.ID `json:"id,omitempty"`
	// 字典集唯一编码，程序通过该编码读取字典项。
	Code string `json:"code,omitempty"`
	// 字典集名称。
	Name string `json:"name,omitempty"`
	// 字典集是否启用。
	IsEnable bool `json:"is_enable,omitempty"`
	// 字典集说明。
	Description *string `json:"description,omitempty"`
	// 字典值推荐长度上限。
	ItemLength *int32 `json:"item_length,omitempty"`
	// 是否为系统内置字典集。
	IsBuiltin bool `json:"is_builtin,omitempty"`
	// 排序值。
	SortID int32 `json:"sort_id,omitempty"`
	// 逻辑删除时间，NULL 表示未删除。
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// 创建时间。
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 最后更新时间。
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 创建人用户 ID。
	CreatedBy *idgen.ID `json:"created_by,omitempty"`
	// 最后更新人用户 ID。
	UpdatedBy *idgen.ID `json:"updated_by,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SysDictCollectionQuery when eager-loading is set.
	Edges        SysDictCollectionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SysDictCollectionEdges holds the relations/edges for other nodes in the graph.
type SysDictCollectionEdges struct {
	// Items holds the value of the items edge.
	Items []*SysDictItem `json:"items,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ItemsOrErr returns the Items value or an error if the edge
// was not loaded in eager-loading.
func (e SysDictCollectionEdges) ItemsOrErr() ([]*SysDictItem, error) {
	if e.loadedTypes[0] {
		return e.Items, nil
	}
	return nil, &NotLoadedError{edge: "items"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SysDictCollection) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case sysdictcollection.FieldIsEnable, sysdictcollection.FieldIsBuiltin:
			values[i] = new(sql.NullBool)
		case sysdictcollection.FieldID, sysdictcollection.FieldItemLength, sysdictcollection.FieldSortID, sysdictcollection.FieldCreatedBy, sysdictcollection.FieldUpdatedBy:
			values[i] = new(sql.NullInt64)
		case sysdictcollection.FieldCode, sysdictcollection.FieldName, sysdictcollection.FieldDescription:
			values[i] = new(sql.NullString)
		case sysdictcollection.FieldDeletedAt, sysdictcollection.FieldCreatedAt, sysdictcollection.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SysDictCollection fields.
func (_m *SysDictCollection) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case sysdictcollection.FieldID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = idgen.ID(value.Int64)
			}
		case sysdictcollection.FieldCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code", values[i])
			} else if value.Valid {
				_m.Code = value.String
			}
		case sysdictcollection.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case sysdictcollection.FieldIsEnable:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_enable", values[i])
			} else if value.Valid {
				_m.IsEnable = value.Bool
			}
		case sysdictcollection.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = new(string)
				*_m.Description = value.String
			}
		case sysdictcollection.FieldItemLength:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field item_length", values[i])
			} else if value.Valid {
				_m.ItemLength = new(int32)
				*_m.ItemLength = int32(value.Int64)
			}
		case sysdictcollection.FieldIsBuiltin:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_builtin", values[i])
			} else if value.Valid {
				_m.IsBuiltin = value.Bool
			}
		case sysdictcollection.FieldSortID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort_id", values[i])
			} else if value.Valid {
				_m.SortID = int32(value.Int64)
			}
		case sysdictcollection.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case sysdictcollection.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case sysdictcollection.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case sysdictcollection.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = new(idgen.ID)
				*_m.CreatedBy = idgen.ID(value.Int64)
			}
		case sysdictcollection.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				_m.UpdatedBy = new(idgen.ID)
				*_m.UpdatedBy = idgen.ID(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SysDictCollection.
// This includes values selected through modifiers, order, etc.
func (_m *SysDictCollection) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryItems queries the "items" edge of the SysDictCollection entity.
func (_m *SysDictCollection) QueryItems() *SysDictItemQuery {
	return NewSysDictCollectionClient(_m.config).QueryItems(_m)
}

// Update returns a builder for updating this SysDictCollection.
// Note that you need to call SysDictCollection.Unwrap() before calling this method if this SysDictCollection
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SysDictCollection) Update() *SysDictCollectionUpdateOne {
	return NewSysDictCollectionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SysDictCollection entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SysDictCollection) Unwrap() *SysDictCollection {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SysDictCollection is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SysDictCollection) String() string {
	var builder strings.Builder
	builder.WriteString("SysDictCollection(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("code=")
	builder.WriteString(_m.Code)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("is_enable=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsEnable))
	builder.WriteString(", ")
	if v := _m.Description; v != nil {
		builder.WriteString("description=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ItemLength; v != nil {
		builder.WriteString("item_length=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("is_builtin=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsBuiltin))
	builder.WriteString(", ")
	builder.WriteString("sort_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SortID))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.CreatedBy; v != nil {
		builder.WriteString("created_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.UpdatedBy; v != nil {
		builder.WriteString("updated_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// SysDictCollections is a parsable slice of SysDictCollection.
type SysDictCollections []*SysDictCollection
