// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/teamsillybees/initra/examples/internal/data/ent/sysdictcollection"
	"github.com/teamsillybees/initra/examples/internal/data/ent/sysdictitem"
	"github.com/teamsillybees/initra/pkg/idgen"
)

// SysDictCollectionCreate is the builder for creating a SysDictCollection entity.
type SysDictCollectionCreate struct {
	config
	mutation *SysDictCollectionMutation
	hooks    []Hook
}

// SetCode sets the "code" field.
func (_c *SysDictCollectionCreate) SetCode(v string) *SysDictCollectionCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetName sets the "name" field.
func (_c *SysDictCollectionCreate) SetName(v string) *SysDictCollectionCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetIsEnable sets the "is_enable" field.
func (_c *SysDictCollectionCreate) SetIsEnable(v bool) *SysDictCollectionCreate {
	_c.mutation.SetIsEnable(v)
	return _c
}

// SetNillableIsEnable sets the "is_enable" field if the given value is not nil.
func (_c *SysDictCollectionCreate) SetNillableIsEnable(v *bool) *SysDictCollectionCreate {
	if v != nil {
		_c.SetIsEnable(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *SysDictCollectionCreate) SetDescription(v string) *SysDictCollectionCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *SysDictCollectionCreate) SetNillableDescription(v *string) *SysDictCollectionCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetItemLength sets the "item_length" field.
func (_c *SysDictCollectionCreate) SetItemLength(v int32) *SysDictCollectionCreate {
	_c.mutation.SetItemLength(v)
	return _c
}

// SetNillableItemLength sets the "item_length" field if the given value is not nil.
func (_c *SysDictCollectionCreate) SetNillableItemLength(v *int32) *SysDictCollectionCreate {
	if v != nil {
		_c.SetItemLength(*v)
	}
	return _c
}

// SetIsBuiltin sets the "is_builtin" field.
func (_c *SysDictCollectionCreate) SetIsBuiltin(v bool) *SysDictCollectionCreate {
	_c.mutation.SetIsBuiltin(v)
	return _c
}

// SetNillableIsBuiltin sets the "is_builtin" field if the given value is not nil.
func (_c *SysDictCollectionCreate) SetNillableIsBuiltin(v *bool) *SysDictCollectionCreate {
	if v != nil {
		_c.SetIsBuiltin(*v)
	}
	return _c
}

// SetSortID sets the "sort_id" field.
func (_c *SysDictCollectionCreate) SetSortID(v int32) *SysDictCollectionCreate {
	_c.mutation.SetSortID(v)
	return _c
}

// SetNillableSortID sets the "sort_id" field if the given value is not nil.
func (_c *SysDictCollectionCreate) SetNillableSortID(v *int32) *SysDictCollectionCreate {
	if v != nil {
		_c.SetSortID(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *SysDictCollectionCreate) SetDeletedAt(v time.Time) *SysDictCollectionCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *SysDictCollectionCreate) SetNillableDeletedAt(v *time.Time) *SysDictCollectionCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SysDictCollectionCreate) SetCreatedAt(v time.Time) *SysDictCollectionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SysDictCollectionCreate) SetNillableCreatedAt(v *time.Time) *SysDictCollectionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SysDictCollectionCreate) SetUpdatedAt(v time.Time) *SysDictCollectionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SysDictCollectionCreate) SetNillableUpdatedAt(v *time.Time) *SysDictCollectionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *SysDictCollectionCreate) SetCreatedBy(v idgen.ID) *SysDictCollectionCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *SysDictCollectionCreate) SetNillableCreatedBy(v *idgen.ID) *SysDictCollectionCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *SysDictCollectionCreate) SetUpdatedBy(v idgen.ID) *SysDictCollectionCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *SysDictCollectionCreate) SetNillableUpdatedBy(v *idgen.ID) *SysDictCollectionCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SysDictCollectionCreate) SetID(v idgen.ID) *SysDictCollectionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *SysDictCollectionCreate) SetNillableID(v *idgen.ID) *SysDictCollectionCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddItemIDs adds the "items" edge to the SysDictItem entity by IDs.
func (_c *SysDictCollectionCreate) AddItemIDs(ids ...idgen.ID) *SysDictCollectionCreate {
	_c.mutation.AddItemIDs(ids...)
	return _c
}

// AddItems adds the "items" edges to the SysDictItem entity.
func (_c *SysDictCollectionCreate) AddItems(v ...*SysDictItem) *SysDictCollectionCreate {
	ids := make([]idgen.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddItemIDs(ids...)
}

// Mutation returns the SysDictCollectionMutation object of the builder.
func (_c *SysDictCollectionCreate) Mutation() *SysDictCollectionMutation {
	return _c.mutation
}

// Save creates the SysDictCollection in the database.
func (_c *SysDictCollectionCreate) Save(ctx context.Context) (*SysDictCollection, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SysDictCollectionCreate) SaveX(ctx context.Context) *SysDictCollection {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SysDictCollectionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SysDictCollectionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SysDictCollectionCreate) defaults() {
	if _, ok := _c.mutation.IsEnable(); !ok {
		v := sysdictcollection.DefaultIsEnable
		_c.mutation.SetIsEnable(v)
	}
	if _, ok := _c.mutation.IsBuiltin(); !ok {
		v := sysdictcollection.DefaultIsBuiltin
		_c.mutation.SetIsBuiltin(v)
	}
	if _, ok := _c.mutation.SortID(); !ok {
		v := sysdictcollection.DefaultSortID
		_c.mutation.SetSortID(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := sysdictcollection.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := sysdictcollection.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := sysdictcollection.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SysDictCollectionCreate) check() error {
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "SysDictCollection.code"`)}
	}
	if v, ok := _c.mutation.Code(); ok {
		if err := sysdictcollection.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "SysDictCollection.code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "SysDictCollection.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := sysdictcollection.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SysDictCollection.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsEnable(); !ok {
		return &ValidationError{Name: "is_enable", err: errors.New(`ent: missing required field "SysDictCollection.is_enable"`)}
	}
	if _, ok := _c.mutation.IsBuiltin(); !ok {
		return &ValidationError{Name: "is_builtin", err: errors.New(`ent: missing required field "SysDictCollection.is_builtin"`)}
	}
	if _, ok := _c.mutation.SortID(); !ok {
		return &ValidationError{Name: "sort_id", err: errors.New(`ent: missing required field "SysDictCollection.sort_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SysDictCollection.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SysDictCollection.updated_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := sysdictcollection.IDValidator(int64(v)); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "SysDictCollection.id": %w`, err)}
		}
	}
	return nil
}

func (_c *SysDictCollectionCreate) sqlSave(ctx context.Context) (*SysDictCollection, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = idgen.ID(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SysDictCollectionCreate) createSpec() (*SysDictCollection, *sqlgraph.CreateSpec) {
	var (
		_node = &SysDictCollection{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(sysdictcollection.Table, sqlgraph.NewFieldSpec(sysdictcollection.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(sysdictcollection.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(sysdictcollection.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.IsEnable(); ok {
		_spec.SetField(sysdictcollection.FieldIsEnable, field.TypeBool, value)
		_node.IsEnable = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(sysdictcollection.FieldDescription, field.TypeString, value)
		_node.Description = &value
	}
	if value, ok := _c.mutation.ItemLength(); ok {
		_spec.SetField(sysdictcollection.FieldItemLength, field.TypeInt32, value)
		_node.ItemLength = &value
	}
	if value, ok := _c.mutation.IsBuiltin(); ok {
		_spec.SetField(sysdictcollection.FieldIsBuiltin, field.TypeBool, value)
		_node.IsBuiltin = value
	}
	if value, ok := _c.mutation.SortID(); ok {
		_spec.SetField(sysdictcollection.FieldSortID, field.TypeInt32, value)
		_node.SortID = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(sysdictcollection.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(sysdictcollection.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(sysdictcollection.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(sysdictcollection.FieldCreatedBy, field.TypeInt64, value)
		_node.CreatedBy = &value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(sysdictcollection.FieldUpdatedBy, field.TypeInt64, value)
		_node.UpdatedBy = &value
	}
	if nodes := _c.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sysdictcollection.ItemsTable,
			Columns: []string{sysdictcollection.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sysdictitem.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SysDictCollectionCreateBulk is the builder for creating many SysDictCollection entities in bulk.
type SysDictCollectionCreateBulk struct {
	config
	err      error
	builders []*SysDictCollectionCreate
}

// Save creates the SysDictCollection entities in the database.
func (_c *SysDictCollectionCreateBulk) Save(ctx context.Context) ([]*SysDictCollection, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SysDictCollection, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SysDictCollectionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = idgen.ID(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SysDictCollectionCreateBulk) SaveX(ctx context.Context) []*SysDictCollection {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SysDictCollectionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SysDictCollectionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
