// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/teamsillybees/initra/examples/internal/data/ent/predicate"
	"github.com/teamsillybees/initra/examples/internal/data/ent/sysdictcollection"
	"github.com/teamsillybees/initra/examples/internal/data/ent/sysdictitem"
)

// SysDictItemUpdate is the builder for updating SysDictItem entities.
type SysDictItemUpdate struct {
	config
	hooks    []Hook
	mutation *SysDictItemMutation
}

// Where appends a list predicates to the SysDictItemUpdate builder.
func (_u *SysDictItemUpdate) Where(ps ...predicate.SysDictItem) *SysDictItemUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *SysDictItemUpdate) SetDeletedAt(v time.Time) *SysDictItemUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *SysDictItemUpdate) SetNillableDeletedAt(v *time.Time) *SysDictItemUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *SysDictItemUpdate) ClearDeletedAt() *SysDictItemUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SysDictItemUpdate) SetUpdatedAt(v time.Time) *SysDictItemUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *SysDictItemUpdate) SetNillableUpdatedAt(v *time.Time) *SysDictItemUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *SysDictItemUpdate) SetCreatedBy(v int64) *SysDictItemUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *SysDictItemUpdate) SetNillableCreatedBy(v *int64) *SysDictItemUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *SysDictItemUpdate) AddCreatedBy(v int64) *SysDictItemUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *SysDictItemUpdate) ClearCreatedBy() *SysDictItemUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *SysDictItemUpdate) SetUpdatedBy(v int64) *SysDictItemUpdate {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *SysDictItemUpdate) SetNillableUpdatedBy(v *int64) *SysDictItemUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *SysDictItemUpdate) AddUpdatedBy(v int64) *SysDictItemUpdate {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *SysDictItemUpdate) ClearUpdatedBy() *SysDictItemUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetCollectionID sets the "collection_id" field.
func (_u *SysDictItemUpdate) SetCollectionID(v int64) *SysDictItemUpdate {
	_u.mutation.SetCollectionID(v)
	return _u
}

// SetNillableCollectionID sets the "collection_id" field if the given value is not nil.
func (_u *SysDictItemUpdate) SetNillableCollectionID(v *int64) *SysDictItemUpdate {
	if v != nil {
		_u.SetCollectionID(*v)
	}
	return _u
}

// SetCollectionCode sets the "collection_code" field.
func (_u *SysDictItemUpdate) SetCollectionCode(v string) *SysDictItemUpdate {
	_u.mutation.SetCollectionCode(v)
	return _u
}

// SetNillableCollectionCode sets the "collection_code" field if the given value is not nil.
func (_u *SysDictItemUpdate) SetNillableCollectionCode(v *string) *SysDictItemUpdate {
	if v != nil {
		_u.SetCollectionCode(*v)
	}
	return _u
}

// SetCode sets the "code" field.
func (_u *SysDictItemUpdate) SetCode(v string) *SysDictItemUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *SysDictItemUpdate) SetNillableCode(v *string) *SysDictItemUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetParentCode sets the "parent_code" field.
func (_u *SysDictItemUpdate) SetParentCode(v string) *SysDictItemUpdate {
	_u.mutation.SetParentCode(v)
	return _u
}

// SetNillableParentCode sets the "parent_code" field if the given value is not nil.
func (_u *SysDictItemUpdate) SetNillableParentCode(v *string) *SysDictItemUpdate {
	if v != nil {
		_u.SetParentCode(*v)
	}
	return _u
}

// SetLabel sets the "label" field.
func (_u *SysDictItemUpdate) SetLabel(v string) *SysDictItemUpdate {
	_u.mutation.SetLabel(v)
	return _u
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_u *SysDictItemUpdate) SetNillableLabel(v *string) *SysDictItemUpdate {
	if v != nil {
		_u.SetLabel(*v)
	}
	return _u
}

// SetIsDefaultValue sets the "is_default_value" field.
func (_u *SysDictItemUpdate) SetIsDefaultValue(v bool) *SysDictItemUpdate {
	_u.mutation.SetIsDefaultValue(v)
	return _u
}

// SetNillableIsDefaultValue sets the "is_default_value" field if the given value is not nil.
func (_u *SysDictItemUpdate) SetNillableIsDefaultValue(v *bool) *SysDictItemUpdate {
	if v != nil {
		_u.SetIsDefaultValue(*v)
	}
	return _u
}

// SetIsEnable sets the "is_enable" field.
func (_u *SysDictItemUpdate) SetIsEnable(v bool) *SysDictItemUpdate {
	_u.mutation.SetIsEnable(v)
	return _u
}

// SetNillableIsEnable sets the "is_enable" field if the given value is not nil.
func (_u *SysDictItemUpdate) SetNillableIsEnable(v *bool) *SysDictItemUpdate {
	if v != nil {
		_u.SetIsEnable(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *SysDictItemUpdate) SetDescription(v string) *SysDictItemUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *SysDictItemUpdate) SetNillableDescription(v *string) *SysDictItemUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *SysDictItemUpdate) ClearDescription() *SysDictItemUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetSortID sets the "sort_id" field.
func (_u *SysDictItemUpdate) SetSortID(v int) *SysDictItemUpdate {
	_u.mutation.ResetSortID()
	_u.mutation.SetSortID(v)
	return _u
}

// SetNillableSortID sets the "sort_id" field if the given value is not nil.
func (_u *SysDictItemUpdate) SetNillableSortID(v *int) *SysDictItemUpdate {
	if v != nil {
		_u.SetSortID(*v)
	}
	return _u
}

// AddSortID adds value to the "sort_id" field.
func (_u *SysDictItemUpdate) AddSortID(v int) *SysDictItemUpdate {
	_u.mutation.AddSortID(v)
	return _u
}

// SetCollection sets the "collection" edge to the SysDictCollection entity.
func (_u *SysDictItemUpdate) SetCollection(v *SysDictCollection) *SysDictItemUpdate {
	return _u.SetCollectionID(v.ID)
}

// Mutation returns the SysDictItemMutation object of the builder.
func (_u *SysDictItemUpdate) Mutation() *SysDictItemMutation {
	return _u.mutation
}

// ClearCollection clears the "collection" edge to the SysDictCollection entity.
func (_u *SysDictItemUpdate) ClearCollection() *SysDictItemUpdate {
	_u.mutation.ClearCollection()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SysDictItemUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SysDictItemUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SysDictItemUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SysDictItemUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SysDictItemUpdate) check() error {
	if v, ok := _u.mutation.CollectionID(); ok {
		if err := sysdictitem.CollectionIDValidator(v); err != nil {
			return &ValidationError{Name: "collection_id", err: fmt.Errorf(`ent: validator failed for field "SysDictItem.collection_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CollectionCode(); ok {
		if err := sysdictitem.CollectionCodeValidator(v); err != nil {
			return &ValidationError{Name: "collection_code", err: fmt.Errorf(`ent: validator failed for field "SysDictItem.collection_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Code(); ok {
		if err := sysdictitem.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "SysDictItem.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ParentCode(); ok {
		if err := sysdictitem.ParentCodeValidator(v); err != nil {
			return &ValidationError{Name: "parent_code", err: fmt.Errorf(`ent: validator failed for field "SysDictItem.parent_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Label(); ok {
		if err := sysdictitem.LabelValidator(v); err != nil {
			return &ValidationError{Name: "label", err: fmt.Errorf(`ent: validator failed for field "SysDictItem.label": %w`, err)}
		}
	}
	if _u.mutation.CollectionCleared() && len(_u.mutation.CollectionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SysDictItem.collection"`)
	}
	return nil
}

func (_u *SysDictItemUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sysdictitem.Table, sysdictitem.Columns, sqlgraph.NewFieldSpec(sysdictitem.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(sysdictitem.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(sysdictitem.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(sysdictitem.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(sysdictitem.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(sysdictitem.FieldCreatedBy, field.TypeInt64, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(sysdictitem.FieldCreatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(sysdictitem.FieldUpdatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(sysdictitem.FieldUpdatedBy, field.TypeInt64, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(sysdictitem.FieldUpdatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.CollectionCode(); ok {
		_spec.SetField(sysdictitem.FieldCollectionCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(sysdictitem.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.ParentCode(); ok {
		_spec.SetField(sysdictitem.FieldParentCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Label(); ok {
		_spec.SetField(sysdictitem.FieldLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsDefaultValue(); ok {
		_spec.SetField(sysdictitem.FieldIsDefaultValue, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsEnable(); ok {
		_spec.SetField(sysdictitem.FieldIsEnable, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(sysdictitem.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(sysdictitem.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.SortID(); ok {
		_spec.SetField(sysdictitem.FieldSortID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortID(); ok {
		_spec.AddField(sysdictitem.FieldSortID, field.TypeInt, value)
	}
	if _u.mutation.CollectionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sysdictitem.CollectionTable,
			Columns: []string{sysdictitem.CollectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sysdictcollection.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CollectionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sysdictitem.CollectionTable,
			Columns: []string{sysdictitem.CollectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sysdictcollection.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sysdictitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SysDictItemUpdateOne is the builder for updating a single SysDictItem entity.
type SysDictItemUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SysDictItemMutation
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *SysDictItemUpdateOne) SetDeletedAt(v time.Time) *SysDictItemUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *SysDictItemUpdateOne) SetNillableDeletedAt(v *time.Time) *SysDictItemUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *SysDictItemUpdateOne) ClearDeletedAt() *SysDictItemUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SysDictItemUpdateOne) SetUpdatedAt(v time.Time) *SysDictItemUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *SysDictItemUpdateOne) SetNillableUpdatedAt(v *time.Time) *SysDictItemUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *SysDictItemUpdateOne) SetCreatedBy(v int64) *SysDictItemUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *SysDictItemUpdateOne) SetNillableCreatedBy(v *int64) *SysDictItemUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *SysDictItemUpdateOne) AddCreatedBy(v int64) *SysDictItemUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *SysDictItemUpdateOne) ClearCreatedBy() *SysDictItemUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *SysDictItemUpdateOne) SetUpdatedBy(v int64) *SysDictItemUpdateOne {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *SysDictItemUpdateOne) SetNillableUpdatedBy(v *int64) *SysDictItemUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *SysDictItemUpdateOne) AddUpdatedBy(v int64) *SysDictItemUpdateOne {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *SysDictItemUpdateOne) ClearUpdatedBy() *SysDictItemUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetCollectionID sets the "collection_id" field.
func (_u *SysDictItemUpdateOne) SetCollectionID(v int64) *SysDictItemUpdateOne {
	_u.mutation.SetCollectionID(v)
	return _u
}

// SetNillableCollectionID sets the "collection_id" field if the given value is not nil.
func (_u *SysDictItemUpdateOne) SetNillableCollectionID(v *int64) *SysDictItemUpdateOne {
	if v != nil {
		_u.SetCollectionID(*v)
	}
	return _u
}

// SetCollectionCode sets the "collection_code" field.
func (_u *SysDictItemUpdateOne) SetCollectionCode(v string) *SysDictItemUpdateOne {
	_u.mutation.SetCollectionCode(v)
	return _u
}

// SetNillableCollectionCode sets the "collection_code" field if the given value is not nil.
func (_u *SysDictItemUpdateOne) SetNillableCollectionCode(v *string) *SysDictItemUpdateOne {
	if v != nil {
		_u.SetCollectionCode(*v)
	}
	return _u
}

// SetCode sets the "code" field.
func (_u *SysDictItemUpdateOne) SetCode(v string) *SysDictItemUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *SysDictItemUpdateOne) SetNillableCode(v *string) *SysDictItemUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetParentCode sets the "parent_code" field.
func (_u *SysDictItemUpdateOne) SetParentCode(v string) *SysDictItemUpdateOne {
	_u.mutation.SetParentCode(v)
	return _u
}

// SetNillableParentCode sets the "parent_code" field if the given value is not nil.
func (_u *SysDictItemUpdateOne) SetNillableParentCode(v *string) *SysDictItemUpdateOne {
	if v != nil {
		_u.SetParentCode(*v)
	}
	return _u
}

// SetLabel sets the "label" field.
func (_u *SysDictItemUpdateOne) SetLabel(v string) *SysDictItemUpdateOne {
	_u.mutation.SetLabel(v)
	return _u
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_u *SysDictItemUpdateOne) SetNillableLabel(v *string) *SysDictItemUpdateOne {
	if v != nil {
		_u.SetLabel(*v)
	}
	return _u
}

// SetIsDefaultValue sets the "is_default_value" field.
func (_u *SysDictItemUpdateOne) SetIsDefaultValue(v bool) *SysDictItemUpdateOne {
	_u.mutation.SetIsDefaultValue(v)
	return _u
}

// SetNillableIsDefaultValue sets the "is_default_value" field if the given value is not nil.
func (_u *SysDictItemUpdateOne) SetNillableIsDefaultValue(v *bool) *SysDictItemUpdateOne {
	if v != nil {
		_u.SetIsDefaultValue(*v)
	}
	return _u
}

// SetIsEnable sets the "is_enable" field.
func (_u *SysDictItemUpdateOne) SetIsEnable(v bool) *SysDictItemUpdateOne {
	_u.mutation.SetIsEnable(v)
	return _u
}

// SetNillableIsEnable sets the "is_enable" field if the given value is not nil.
func (_u *SysDictItemUpdateOne) SetNillableIsEnable(v *bool) *SysDictItemUpdateOne {
	if v != nil {
		_u.SetIsEnable(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *SysDictItemUpdateOne) SetDescription(v string) *SysDictItemUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *SysDictItemUpdateOne) SetNillableDescription(v *string) *SysDictItemUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *SysDictItemUpdateOne) ClearDescription() *SysDictItemUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetSortID sets the "sort_id" field.
func (_u *SysDictItemUpdateOne) SetSortID(v int) *SysDictItemUpdateOne {
	_u.mutation.ResetSortID()
	_u.mutation.SetSortID(v)
	return _u
}

// SetNillableSortID sets the "sort_id" field if the given value is not nil.
func (_u *SysDictItemUpdateOne) SetNillableSortID(v *int) *SysDictItemUpdateOne {
	if v != nil {
		_u.SetSortID(*v)
	}
	return _u
}

// AddSortID adds value to the "sort_id" field.
func (_u *SysDictItemUpdateOne) AddSortID(v int) *SysDictItemUpdateOne {
	_u.mutation.AddSortID(v)
	return _u
}

// SetCollection sets the "collection" edge to the SysDictCollection entity.
func (_u *SysDictItemUpdateOne) SetCollection(v *SysDictCollection) *SysDictItemUpdateOne {
	return _u.SetCollectionID(v.ID)
}

// Mutation returns the SysDictItemMutation object of the builder.
func (_u *SysDictItemUpdateOne) Mutation() *SysDictItemMutation {
	return _u.mutation
}

// ClearCollection clears the "collection" edge to the SysDictCollection entity.
func (_u *SysDictItemUpdateOne) ClearCollection() *SysDictItemUpdateOne {
	_u.mutation.ClearCollection()
	return _u
}

// Where appends a list predicates to the SysDictItemUpdate builder.
func (_u *SysDictItemUpdateOne) Where(ps ...predicate.SysDictItem) *SysDictItemUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SysDictItemUpdateOne) Select(field string, fields ...string) *SysDictItemUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SysDictItem entity.
func (_u *SysDictItemUpdateOne) Save(ctx context.Context) (*SysDictItem, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SysDictItemUpdateOne) SaveX(ctx context.Context) *SysDictItem {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SysDictItemUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SysDictItemUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SysDictItemUpdateOne) check() error {
	if v, ok := _u.mutation.CollectionID(); ok {
		if err := sysdictitem.CollectionIDValidator(v); err != nil {
			return &ValidationError{Name: "collection_id", err: fmt.Errorf(`ent: validator failed for field "SysDictItem.collection_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CollectionCode(); ok {
		if err := sysdictitem.CollectionCodeValidator(v); err != nil {
			return &ValidationError{Name: "collection_code", err: fmt.Errorf(`ent: validator failed for field "SysDictItem.collection_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Code(); ok {
		if err := sysdictitem.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "SysDictItem.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ParentCode(); ok {
		if err := sysdictitem.ParentCodeValidator(v); err != nil {
			return &ValidationError{Name: "parent_code", err: fmt.Errorf(`ent: validator failed for field "SysDictItem.parent_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Label(); ok {
		if err := sysdictitem.LabelValidator(v); err != nil {
			return &ValidationError{Name: "label", err: fmt.Errorf(`ent: validator failed for field "SysDictItem.label": %w`, err)}
		}
	}
	if _u.mutation.CollectionCleared() && len(_u.mutation.CollectionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SysDictItem.collection"`)
	}
	return nil
}

func (_u *SysDictItemUpdateOne) sqlSave(ctx context.Context) (_node *SysDictItem, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sysdictitem.Table, sysdictitem.Columns, sqlgraph.NewFieldSpec(sysdictitem.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SysDictItem.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sysdictitem.FieldID)
		for _, f := range fields {
			if !sysdictitem.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != sysdictitem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(sysdictitem.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(sysdictitem.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(sysdictitem.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(sysdictitem.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(sysdictitem.FieldCreatedBy, field.TypeInt64, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(sysdictitem.FieldCreatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(sysdictitem.FieldUpdatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(sysdictitem.FieldUpdatedBy, field.TypeInt64, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(sysdictitem.FieldUpdatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.CollectionCode(); ok {
		_spec.SetField(sysdictitem.FieldCollectionCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(sysdictitem.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.ParentCode(); ok {
		_spec.SetField(sysdictitem.FieldParentCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Label(); ok {
		_spec.SetField(sysdictitem.FieldLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsDefaultValue(); ok {
		_spec.SetField(sysdictitem.FieldIsDefaultValue, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsEnable(); ok {
		_spec.SetField(sysdictitem.FieldIsEnable, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(sysdictitem.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(sysdictitem.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.SortID(); ok {
		_spec.SetField(sysdictitem.FieldSortID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortID(); ok {
		_spec.AddField(sysdictitem.FieldSortID, field.TypeInt, value)
	}
	if _u.mutation.CollectionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sysdictitem.CollectionTable,
			Columns: []string{sysdictitem.CollectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sysdictcollection.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CollectionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sysdictitem.CollectionTable,
			Columns: []string{sysdictitem.CollectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sysdictcollection.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SysDictItem{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sysdictitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
