// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/teamsillybees/initra/examples/internal/data/ent/sysmenu"
	"github.com/teamsillybees/initra/pkg/idgen"
)

// 系统菜单与按钮权限表，统一承载菜单、目录、按钮三类资源。
type SysMenu struct {
	config `json:"-"`
	// ID of the ent.
	// 雪花算法生成的主键 ID。
	ID idgen.ID `json:"id,omitempty"`
	// 父级菜单 ID，NULL 表示顶级目录。
	ParentID *idgen.ID `json:"parent_id,omitempty"`
	// 所属应用编码，用于多应用场景区分菜单树。
	AppID *string `json:"app_id,omitempty"`
	// 菜单或按钮展示标题。
	Title string `json:"title,omitempty"`
	// 资源类型：0-菜单，1-按钮，2-目录。
	MenuType int16 `json:"menu_type,omitempty"`
	// 前端路由路径。
	RoutePath *string `json:"route_path,omitempty"`
	// 前端组件路径。
	ComponentPath *string `json:"component_path,omitempty"`
	// 权限资源编码，例如 system:user:read。
	PermissionCode *string `json:"permission_code,omitempty"`
	// 菜单图标标识。
	Icon *string `json:"icon,omitempty"`
	// 是否在前端菜单树中可见。
	IsVisible bool `json:"is_visible,omitempty"`
	// 前端页面是否缓存。
	IsCached bool `json:"is_cached,omitempty"`
	// 排序值，值越小越靠前。
	SortID int32 `json:"sort_id,omitempty"`
	// 逻辑删除时间，NULL 表示未删除。
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// 创建时间。
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 最后更新时间。
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 创建人用户 ID。
	CreatedBy *idgen.ID `json:"created_by,omitempty"`
	// 最后更新人用户 ID。
	UpdatedBy *idgen.ID `json:"updated_by,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SysMenuQuery when eager-loading is set.
	Edges        SysMenuEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SysMenuEdges holds the relations/edges for other nodes in the graph.
type SysMenuEdges struct {
	// RoleMenus holds the value of the role_menus edge.
	RoleMenus []*SysRoleMenu `json:"role_menus,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// RoleMenusOrErr returns the RoleMenus value or an error if the edge
// was not loaded in eager-loading.
func (e SysMenuEdges) RoleMenusOrErr() ([]*SysRoleMenu, error) {
	if e.loadedTypes[0] {
		return e.RoleMenus, nil
	}
	return nil, &NotLoadedError{edge: "role_menus"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SysMenu) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case sysmenu.FieldIsVisible, sysmenu.FieldIsCached:
			values[i] = new(sql.NullBool)
		case sysmenu.FieldID, sysmenu.FieldParentID, sysmenu.FieldMenuType, sysmenu.FieldSortID, sysmenu.FieldCreatedBy, sysmenu.FieldUpdatedBy:
			values[i] = new(sql.NullInt64)
		case sysmenu.FieldAppID, sysmenu.FieldTitle, sysmenu.FieldRoutePath, sysmenu.FieldComponentPath, sysmenu.FieldPermissionCode, sysmenu.FieldIcon:
			values[i] = new(sql.NullString)
		case sysmenu.FieldDeletedAt, sysmenu.FieldCreatedAt, sysmenu.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SysMenu fields.
func (_m *SysMenu) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case sysmenu.FieldID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = idgen.ID(value.Int64)
			}
		case sysmenu.FieldParentID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field parent_id", values[i])
			} else if value.Valid {
				_m.ParentID = new(idgen.ID)
				*_m.ParentID = idgen.ID(value.Int64)
			}
		case sysmenu.FieldAppID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field app_id", values[i])
			} else if value.Valid {
				_m.AppID = new(string)
				*_m.AppID = value.String
			}
		case sysmenu.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case sysmenu.FieldMenuType:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field menu_type", values[i])
			} else if value.Valid {
				_m.MenuType = int16(value.Int64)
			}
		case sysmenu.FieldRoutePath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field route_path", values[i])
			} else if value.Valid {
				_m.RoutePath = new(string)
				*_m.RoutePath = value.String
			}
		case sysmenu.FieldComponentPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field component_path", values[i])
			} else if value.Valid {
				_m.ComponentPath = new(string)
				*_m.ComponentPath = value.String
			}
		case sysmenu.FieldPermissionCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field permission_code", values[i])
			} else if value.Valid {
				_m.PermissionCode = new(string)
				*_m.PermissionCode = value.String
			}
		case sysmenu.FieldIcon:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field icon", values[i])
			} else if value.Valid {
				_m.Icon = new(string)
				*_m.Icon = value.String
			}
		case sysmenu.FieldIsVisible:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_visible", values[i])
			} else if value.Valid {
				_m.IsVisible = value.Bool
			}
		case sysmenu.FieldIsCached:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_cached", values[i])
			} else if value.Valid {
				_m.IsCached = value.Bool
			}
		case sysmenu.FieldSortID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort_id", values[i])
			} else if value.Valid {
				_m.SortID = int32(value.Int64)
			}
		case sysmenu.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case sysmenu.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case sysmenu.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case sysmenu.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = new(idgen.ID)
				*_m.CreatedBy = idgen.ID(value.Int64)
			}
		case sysmenu.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				_m.UpdatedBy = new(idgen.ID)
				*_m.UpdatedBy = idgen.ID(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SysMenu.
// This includes values selected through modifiers, order, etc.
func (_m *SysMenu) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRoleMenus queries the "role_menus" edge of the SysMenu entity.
func (_m *SysMenu) QueryRoleMenus() *SysRoleMenuQuery {
	return NewSysMenuClient(_m.config).QueryRoleMenus(_m)
}

// Update returns a builder for updating this SysMenu.
// Note that you need to call SysMenu.Unwrap() before calling this method if this SysMenu
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SysMenu) Update() *SysMenuUpdateOne {
	return NewSysMenuClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SysMenu entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SysMenu) Unwrap() *SysMenu {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SysMenu is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SysMenu) String() string {
	var builder strings.Builder
	builder.WriteString("SysMenu(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.ParentID; v != nil {
		builder.WriteString("parent_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.AppID; v != nil {
		builder.WriteString("app_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("menu_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.MenuType))
	builder.WriteString(", ")
	if v := _m.RoutePath; v != nil {
		builder.WriteString("route_path=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ComponentPath; v != nil {
		builder.WriteString("component_path=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.PermissionCode; v != nil {
		builder.WriteString("permission_code=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Icon; v != nil {
		builder.WriteString("icon=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("is_visible=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsVisible))
	builder.WriteString(", ")
	builder.WriteString("is_cached=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsCached))
	builder.WriteString(", ")
	builder.WriteString("sort_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SortID))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.CreatedBy; v != nil {
		builder.WriteString("created_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.UpdatedBy; v != nil {
		builder.WriteString("updated_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// SysMenus is a parsable slice of SysMenu.
type SysMenus []*SysMenu
