// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/teamsillybees/initra/examples/internal/data/ent/predicate"
	"github.com/teamsillybees/initra/examples/internal/data/ent/sysmenu"
	"github.com/teamsillybees/initra/examples/internal/data/ent/sysrole"
	"github.com/teamsillybees/initra/examples/internal/data/ent/sysrolemenu"
	"github.com/teamsillybees/initra/pkg/idgen"
)

// SysRoleMenuUpdate is the builder for updating SysRoleMenu entities.
type SysRoleMenuUpdate struct {
	config
	hooks    []Hook
	mutation *SysRoleMenuMutation
}

// Where appends a list predicates to the SysRoleMenuUpdate builder.
func (_u *SysRoleMenuUpdate) Where(ps ...predicate.SysRoleMenu) *SysRoleMenuUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRoleID sets the "role_id" field.
func (_u *SysRoleMenuUpdate) SetRoleID(v idgen.ID) *SysRoleMenuUpdate {
	_u.mutation.SetRoleID(v)
	return _u
}

// SetNillableRoleID sets the "role_id" field if the given value is not nil.
func (_u *SysRoleMenuUpdate) SetNillableRoleID(v *idgen.ID) *SysRoleMenuUpdate {
	if v != nil {
		_u.SetRoleID(*v)
	}
	return _u
}

// SetMenuID sets the "menu_id" field.
func (_u *SysRoleMenuUpdate) SetMenuID(v idgen.ID) *SysRoleMenuUpdate {
	_u.mutation.SetMenuID(v)
	return _u
}

// SetNillableMenuID sets the "menu_id" field if the given value is not nil.
func (_u *SysRoleMenuUpdate) SetNillableMenuID(v *idgen.ID) *SysRoleMenuUpdate {
	if v != nil {
		_u.SetMenuID(*v)
	}
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *SysRoleMenuUpdate) SetDeletedAt(v time.Time) *SysRoleMenuUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *SysRoleMenuUpdate) SetNillableDeletedAt(v *time.Time) *SysRoleMenuUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *SysRoleMenuUpdate) ClearDeletedAt() *SysRoleMenuUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SysRoleMenuUpdate) SetUpdatedAt(v time.Time) *SysRoleMenuUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *SysRoleMenuUpdate) SetCreatedBy(v idgen.ID) *SysRoleMenuUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *SysRoleMenuUpdate) SetNillableCreatedBy(v *idgen.ID) *SysRoleMenuUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *SysRoleMenuUpdate) AddCreatedBy(v idgen.ID) *SysRoleMenuUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *SysRoleMenuUpdate) ClearCreatedBy() *SysRoleMenuUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *SysRoleMenuUpdate) SetUpdatedBy(v idgen.ID) *SysRoleMenuUpdate {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *SysRoleMenuUpdate) SetNillableUpdatedBy(v *idgen.ID) *SysRoleMenuUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *SysRoleMenuUpdate) AddUpdatedBy(v idgen.ID) *SysRoleMenuUpdate {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *SysRoleMenuUpdate) ClearUpdatedBy() *SysRoleMenuUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetRole sets the "role" edge to the SysRole entity.
func (_u *SysRoleMenuUpdate) SetRole(v *SysRole) *SysRoleMenuUpdate {
	return _u.SetRoleID(v.ID)
}

// SetMenu sets the "menu" edge to the SysMenu entity.
func (_u *SysRoleMenuUpdate) SetMenu(v *SysMenu) *SysRoleMenuUpdate {
	return _u.SetMenuID(v.ID)
}

// Mutation returns the SysRoleMenuMutation object of the builder.
func (_u *SysRoleMenuUpdate) Mutation() *SysRoleMenuMutation {
	return _u.mutation
}

// ClearRole clears the "role" edge to the SysRole entity.
func (_u *SysRoleMenuUpdate) ClearRole() *SysRoleMenuUpdate {
	_u.mutation.ClearRole()
	return _u
}

// ClearMenu clears the "menu" edge to the SysMenu entity.
func (_u *SysRoleMenuUpdate) ClearMenu() *SysRoleMenuUpdate {
	_u.mutation.ClearMenu()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SysRoleMenuUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SysRoleMenuUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SysRoleMenuUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SysRoleMenuUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SysRoleMenuUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := sysrolemenu.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SysRoleMenuUpdate) check() error {
	if v, ok := _u.mutation.RoleID(); ok {
		if err := sysrolemenu.RoleIDValidator(int64(v)); err != nil {
			return &ValidationError{Name: "role_id", err: fmt.Errorf(`ent: validator failed for field "SysRoleMenu.role_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MenuID(); ok {
		if err := sysrolemenu.MenuIDValidator(int64(v)); err != nil {
			return &ValidationError{Name: "menu_id", err: fmt.Errorf(`ent: validator failed for field "SysRoleMenu.menu_id": %w`, err)}
		}
	}
	if _u.mutation.RoleCleared() && len(_u.mutation.RoleIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SysRoleMenu.role"`)
	}
	if _u.mutation.MenuCleared() && len(_u.mutation.MenuIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SysRoleMenu.menu"`)
	}
	return nil
}

func (_u *SysRoleMenuUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sysrolemenu.Table, sysrolemenu.Columns, sqlgraph.NewFieldSpec(sysrolemenu.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(sysrolemenu.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(sysrolemenu.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(sysrolemenu.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(sysrolemenu.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(sysrolemenu.FieldCreatedBy, field.TypeInt64, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(sysrolemenu.FieldCreatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(sysrolemenu.FieldUpdatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(sysrolemenu.FieldUpdatedBy, field.TypeInt64, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(sysrolemenu.FieldUpdatedBy, field.TypeInt64)
	}
	if _u.mutation.RoleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sysrolemenu.RoleTable,
			Columns: []string{sysrolemenu.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sysrole.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sysrolemenu.RoleTable,
			Columns: []string{sysrolemenu.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sysrole.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MenuCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sysrolemenu.MenuTable,
			Columns: []string{sysrolemenu.MenuColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sysmenu.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MenuIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sysrolemenu.MenuTable,
			Columns: []string{sysrolemenu.MenuColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sysmenu.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sysrolemenu.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SysRoleMenuUpdateOne is the builder for updating a single SysRoleMenu entity.
type SysRoleMenuUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SysRoleMenuMutation
}

// SetRoleID sets the "role_id" field.
func (_u *SysRoleMenuUpdateOne) SetRoleID(v idgen.ID) *SysRoleMenuUpdateOne {
	_u.mutation.SetRoleID(v)
	return _u
}

// SetNillableRoleID sets the "role_id" field if the given value is not nil.
func (_u *SysRoleMenuUpdateOne) SetNillableRoleID(v *idgen.ID) *SysRoleMenuUpdateOne {
	if v != nil {
		_u.SetRoleID(*v)
	}
	return _u
}

// SetMenuID sets the "menu_id" field.
func (_u *SysRoleMenuUpdateOne) SetMenuID(v idgen.ID) *SysRoleMenuUpdateOne {
	_u.mutation.SetMenuID(v)
	return _u
}

// SetNillableMenuID sets the "menu_id" field if the given value is not nil.
func (_u *SysRoleMenuUpdateOne) SetNillableMenuID(v *idgen.ID) *SysRoleMenuUpdateOne {
	if v != nil {
		_u.SetMenuID(*v)
	}
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *SysRoleMenuUpdateOne) SetDeletedAt(v time.Time) *SysRoleMenuUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *SysRoleMenuUpdateOne) SetNillableDeletedAt(v *time.Time) *SysRoleMenuUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *SysRoleMenuUpdateOne) ClearDeletedAt() *SysRoleMenuUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SysRoleMenuUpdateOne) SetUpdatedAt(v time.Time) *SysRoleMenuUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *SysRoleMenuUpdateOne) SetCreatedBy(v idgen.ID) *SysRoleMenuUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *SysRoleMenuUpdateOne) SetNillableCreatedBy(v *idgen.ID) *SysRoleMenuUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *SysRoleMenuUpdateOne) AddCreatedBy(v idgen.ID) *SysRoleMenuUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *SysRoleMenuUpdateOne) ClearCreatedBy() *SysRoleMenuUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *SysRoleMenuUpdateOne) SetUpdatedBy(v idgen.ID) *SysRoleMenuUpdateOne {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *SysRoleMenuUpdateOne) SetNillableUpdatedBy(v *idgen.ID) *SysRoleMenuUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *SysRoleMenuUpdateOne) AddUpdatedBy(v idgen.ID) *SysRoleMenuUpdateOne {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *SysRoleMenuUpdateOne) ClearUpdatedBy() *SysRoleMenuUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetRole sets the "role" edge to the SysRole entity.
func (_u *SysRoleMenuUpdateOne) SetRole(v *SysRole) *SysRoleMenuUpdateOne {
	return _u.SetRoleID(v.ID)
}

// SetMenu sets the "menu" edge to the SysMenu entity.
func (_u *SysRoleMenuUpdateOne) SetMenu(v *SysMenu) *SysRoleMenuUpdateOne {
	return _u.SetMenuID(v.ID)
}

// Mutation returns the SysRoleMenuMutation object of the builder.
func (_u *SysRoleMenuUpdateOne) Mutation() *SysRoleMenuMutation {
	return _u.mutation
}

// ClearRole clears the "role" edge to the SysRole entity.
func (_u *SysRoleMenuUpdateOne) ClearRole() *SysRoleMenuUpdateOne {
	_u.mutation.ClearRole()
	return _u
}

// ClearMenu clears the "menu" edge to the SysMenu entity.
func (_u *SysRoleMenuUpdateOne) ClearMenu() *SysRoleMenuUpdateOne {
	_u.mutation.ClearMenu()
	return _u
}

// Where appends a list predicates to the SysRoleMenuUpdate builder.
func (_u *SysRoleMenuUpdateOne) Where(ps ...predicate.SysRoleMenu) *SysRoleMenuUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SysRoleMenuUpdateOne) Select(field string, fields ...string) *SysRoleMenuUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SysRoleMenu entity.
func (_u *SysRoleMenuUpdateOne) Save(ctx context.Context) (*SysRoleMenu, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SysRoleMenuUpdateOne) SaveX(ctx context.Context) *SysRoleMenu {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SysRoleMenuUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SysRoleMenuUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SysRoleMenuUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := sysrolemenu.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SysRoleMenuUpdateOne) check() error {
	if v, ok := _u.mutation.RoleID(); ok {
		if err := sysrolemenu.RoleIDValidator(int64(v)); err != nil {
			return &ValidationError{Name: "role_id", err: fmt.Errorf(`ent: validator failed for field "SysRoleMenu.role_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MenuID(); ok {
		if err := sysrolemenu.MenuIDValidator(int64(v)); err != nil {
			return &ValidationError{Name: "menu_id", err: fmt.Errorf(`ent: validator failed for field "SysRoleMenu.menu_id": %w`, err)}
		}
	}
	if _u.mutation.RoleCleared() && len(_u.mutation.RoleIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SysRoleMenu.role"`)
	}
	if _u.mutation.MenuCleared() && len(_u.mutation.MenuIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SysRoleMenu.menu"`)
	}
	return nil
}

func (_u *SysRoleMenuUpdateOne) sqlSave(ctx context.Context) (_node *SysRoleMenu, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sysrolemenu.Table, sysrolemenu.Columns, sqlgraph.NewFieldSpec(sysrolemenu.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SysRoleMenu.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sysrolemenu.FieldID)
		for _, f := range fields {
			if !sysrolemenu.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != sysrolemenu.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(sysrolemenu.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(sysrolemenu.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(sysrolemenu.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(sysrolemenu.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(sysrolemenu.FieldCreatedBy, field.TypeInt64, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(sysrolemenu.FieldCreatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(sysrolemenu.FieldUpdatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(sysrolemenu.FieldUpdatedBy, field.TypeInt64, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(sysrolemenu.FieldUpdatedBy, field.TypeInt64)
	}
	if _u.mutation.RoleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sysrolemenu.RoleTable,
			Columns: []string{sysrolemenu.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sysrole.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sysrolemenu.RoleTable,
			Columns: []string{sysrolemenu.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sysrole.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MenuCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sysrolemenu.MenuTable,
			Columns: []string{sysrolemenu.MenuColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sysmenu.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MenuIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sysrolemenu.MenuTable,
			Columns: []string{sysrolemenu.MenuColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sysmenu.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SysRoleMenu{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sysrolemenu.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
