// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/teamsillybees/initra/examples/internal/data/ent/sysmenu"
	"github.com/teamsillybees/initra/examples/internal/data/ent/sysrole"
	"github.com/teamsillybees/initra/examples/internal/data/ent/sysrolemenu"
)

// SysRoleMenuCreate is the builder for creating a SysRoleMenu entity.
type SysRoleMenuCreate struct {
	config
	mutation *SysRoleMenuMutation
	hooks    []Hook
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *SysRoleMenuCreate) SetDeletedAt(v time.Time) *SysRoleMenuCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *SysRoleMenuCreate) SetNillableDeletedAt(v *time.Time) *SysRoleMenuCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetRoleID sets the "role_id" field.
func (_c *SysRoleMenuCreate) SetRoleID(v int64) *SysRoleMenuCreate {
	_c.mutation.SetRoleID(v)
	return _c
}

// SetMenuID sets the "menu_id" field.
func (_c *SysRoleMenuCreate) SetMenuID(v int64) *SysRoleMenuCreate {
	_c.mutation.SetMenuID(v)
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *SysRoleMenuCreate) SetCreatedBy(v int64) *SysRoleMenuCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *SysRoleMenuCreate) SetNillableCreatedBy(v *int64) *SysRoleMenuCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SysRoleMenuCreate) SetCreatedAt(v time.Time) *SysRoleMenuCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetID sets the "id" field.
func (_c *SysRoleMenuCreate) SetID(v int64) *SysRoleMenuCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetRole sets the "role" edge to the SysRole entity.
func (_c *SysRoleMenuCreate) SetRole(v *SysRole) *SysRoleMenuCreate {
	return _c.SetRoleID(v.ID)
}

// SetMenu sets the "menu" edge to the SysMenu entity.
func (_c *SysRoleMenuCreate) SetMenu(v *SysMenu) *SysRoleMenuCreate {
	return _c.SetMenuID(v.ID)
}

// Mutation returns the SysRoleMenuMutation object of the builder.
func (_c *SysRoleMenuCreate) Mutation() *SysRoleMenuMutation {
	return _c.mutation
}

// Save creates the SysRoleMenu in the database.
func (_c *SysRoleMenuCreate) Save(ctx context.Context) (*SysRoleMenu, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SysRoleMenuCreate) SaveX(ctx context.Context) *SysRoleMenu {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SysRoleMenuCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SysRoleMenuCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SysRoleMenuCreate) check() error {
	if _, ok := _c.mutation.RoleID(); !ok {
		return &ValidationError{Name: "role_id", err: errors.New(`ent: missing required field "SysRoleMenu.role_id"`)}
	}
	if v, ok := _c.mutation.RoleID(); ok {
		if err := sysrolemenu.RoleIDValidator(v); err != nil {
			return &ValidationError{Name: "role_id", err: fmt.Errorf(`ent: validator failed for field "SysRoleMenu.role_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MenuID(); !ok {
		return &ValidationError{Name: "menu_id", err: errors.New(`ent: missing required field "SysRoleMenu.menu_id"`)}
	}
	if v, ok := _c.mutation.MenuID(); ok {
		if err := sysrolemenu.MenuIDValidator(v); err != nil {
			return &ValidationError{Name: "menu_id", err: fmt.Errorf(`ent: validator failed for field "SysRoleMenu.menu_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SysRoleMenu.created_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := sysrolemenu.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "SysRoleMenu.id": %w`, err)}
		}
	}
	if len(_c.mutation.RoleIDs()) == 0 {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required edge "SysRoleMenu.role"`)}
	}
	if len(_c.mutation.MenuIDs()) == 0 {
		return &ValidationError{Name: "menu", err: errors.New(`ent: missing required edge "SysRoleMenu.menu"`)}
	}
	return nil
}

func (_c *SysRoleMenuCreate) sqlSave(ctx context.Context) (*SysRoleMenu, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SysRoleMenuCreate) createSpec() (*SysRoleMenu, *sqlgraph.CreateSpec) {
	var (
		_node = &SysRoleMenu{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(sysrolemenu.Table, sqlgraph.NewFieldSpec(sysrolemenu.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(sysrolemenu.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(sysrolemenu.FieldCreatedBy, field.TypeInt64, value)
		_node.CreatedBy = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(sysrolemenu.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.RoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sysrolemenu.RoleTable,
			Columns: []string{sysrolemenu.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sysrole.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RoleID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MenuIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sysrolemenu.MenuTable,
			Columns: []string{sysrolemenu.MenuColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sysmenu.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.MenuID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SysRoleMenuCreateBulk is the builder for creating many SysRoleMenu entities in bulk.
type SysRoleMenuCreateBulk struct {
	config
	err      error
	builders []*SysRoleMenuCreate
}

// Save creates the SysRoleMenu entities in the database.
func (_c *SysRoleMenuCreateBulk) Save(ctx context.Context) ([]*SysRoleMenu, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SysRoleMenu, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SysRoleMenuMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SysRoleMenuCreateBulk) SaveX(ctx context.Context) []*SysRoleMenu {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SysRoleMenuCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SysRoleMenuCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
