// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/teamsillybees/initra/examples/internal/data/ent/predicate"
	"github.com/teamsillybees/initra/examples/internal/data/ent/sysrole"
	"github.com/teamsillybees/initra/examples/internal/data/ent/sysuser"
	"github.com/teamsillybees/initra/examples/internal/data/ent/sysuserrole"
	"github.com/teamsillybees/initra/pkg/idgen"
)

// SysUserRoleUpdate is the builder for updating SysUserRole entities.
type SysUserRoleUpdate struct {
	config
	hooks    []Hook
	mutation *SysUserRoleMutation
}

// Where appends a list predicates to the SysUserRoleUpdate builder.
func (_u *SysUserRoleUpdate) Where(ps ...predicate.SysUserRole) *SysUserRoleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SysUserRoleUpdate) SetUserID(v idgen.ID) *SysUserRoleUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SysUserRoleUpdate) SetNillableUserID(v *idgen.ID) *SysUserRoleUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetRoleID sets the "role_id" field.
func (_u *SysUserRoleUpdate) SetRoleID(v idgen.ID) *SysUserRoleUpdate {
	_u.mutation.SetRoleID(v)
	return _u
}

// SetNillableRoleID sets the "role_id" field if the given value is not nil.
func (_u *SysUserRoleUpdate) SetNillableRoleID(v *idgen.ID) *SysUserRoleUpdate {
	if v != nil {
		_u.SetRoleID(*v)
	}
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *SysUserRoleUpdate) SetDeletedAt(v time.Time) *SysUserRoleUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *SysUserRoleUpdate) SetNillableDeletedAt(v *time.Time) *SysUserRoleUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *SysUserRoleUpdate) ClearDeletedAt() *SysUserRoleUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SysUserRoleUpdate) SetUpdatedAt(v time.Time) *SysUserRoleUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *SysUserRoleUpdate) SetCreatedBy(v idgen.ID) *SysUserRoleUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *SysUserRoleUpdate) SetNillableCreatedBy(v *idgen.ID) *SysUserRoleUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *SysUserRoleUpdate) AddCreatedBy(v idgen.ID) *SysUserRoleUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *SysUserRoleUpdate) ClearCreatedBy() *SysUserRoleUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *SysUserRoleUpdate) SetUpdatedBy(v idgen.ID) *SysUserRoleUpdate {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *SysUserRoleUpdate) SetNillableUpdatedBy(v *idgen.ID) *SysUserRoleUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *SysUserRoleUpdate) AddUpdatedBy(v idgen.ID) *SysUserRoleUpdate {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *SysUserRoleUpdate) ClearUpdatedBy() *SysUserRoleUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetUser sets the "user" edge to the SysUser entity.
func (_u *SysUserRoleUpdate) SetUser(v *SysUser) *SysUserRoleUpdate {
	return _u.SetUserID(v.ID)
}

// SetRole sets the "role" edge to the SysRole entity.
func (_u *SysUserRoleUpdate) SetRole(v *SysRole) *SysUserRoleUpdate {
	return _u.SetRoleID(v.ID)
}

// Mutation returns the SysUserRoleMutation object of the builder.
func (_u *SysUserRoleUpdate) Mutation() *SysUserRoleMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the SysUser entity.
func (_u *SysUserRoleUpdate) ClearUser() *SysUserRoleUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearRole clears the "role" edge to the SysRole entity.
func (_u *SysUserRoleUpdate) ClearRole() *SysUserRoleUpdate {
	_u.mutation.ClearRole()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SysUserRoleUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SysUserRoleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SysUserRoleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SysUserRoleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SysUserRoleUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := sysuserrole.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SysUserRoleUpdate) check() error {
	if v, ok := _u.mutation.UserID(); ok {
		if err := sysuserrole.UserIDValidator(int64(v)); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "SysUserRole.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RoleID(); ok {
		if err := sysuserrole.RoleIDValidator(int64(v)); err != nil {
			return &ValidationError{Name: "role_id", err: fmt.Errorf(`ent: validator failed for field "SysUserRole.role_id": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SysUserRole.user"`)
	}
	if _u.mutation.RoleCleared() && len(_u.mutation.RoleIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SysUserRole.role"`)
	}
	return nil
}

func (_u *SysUserRoleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sysuserrole.Table, sysuserrole.Columns, sqlgraph.NewFieldSpec(sysuserrole.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(sysuserrole.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(sysuserrole.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(sysuserrole.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(sysuserrole.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(sysuserrole.FieldCreatedBy, field.TypeInt64, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(sysuserrole.FieldCreatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(sysuserrole.FieldUpdatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(sysuserrole.FieldUpdatedBy, field.TypeInt64, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(sysuserrole.FieldUpdatedBy, field.TypeInt64)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sysuserrole.UserTable,
			Columns: []string{sysuserrole.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sysuser.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sysuserrole.UserTable,
			Columns: []string{sysuserrole.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sysuser.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RoleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sysuserrole.RoleTable,
			Columns: []string{sysuserrole.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sysrole.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sysuserrole.RoleTable,
			Columns: []string{sysuserrole.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sysrole.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sysuserrole.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SysUserRoleUpdateOne is the builder for updating a single SysUserRole entity.
type SysUserRoleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SysUserRoleMutation
}

// SetUserID sets the "user_id" field.
func (_u *SysUserRoleUpdateOne) SetUserID(v idgen.ID) *SysUserRoleUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SysUserRoleUpdateOne) SetNillableUserID(v *idgen.ID) *SysUserRoleUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetRoleID sets the "role_id" field.
func (_u *SysUserRoleUpdateOne) SetRoleID(v idgen.ID) *SysUserRoleUpdateOne {
	_u.mutation.SetRoleID(v)
	return _u
}

// SetNillableRoleID sets the "role_id" field if the given value is not nil.
func (_u *SysUserRoleUpdateOne) SetNillableRoleID(v *idgen.ID) *SysUserRoleUpdateOne {
	if v != nil {
		_u.SetRoleID(*v)
	}
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *SysUserRoleUpdateOne) SetDeletedAt(v time.Time) *SysUserRoleUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *SysUserRoleUpdateOne) SetNillableDeletedAt(v *time.Time) *SysUserRoleUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *SysUserRoleUpdateOne) ClearDeletedAt() *SysUserRoleUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SysUserRoleUpdateOne) SetUpdatedAt(v time.Time) *SysUserRoleUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *SysUserRoleUpdateOne) SetCreatedBy(v idgen.ID) *SysUserRoleUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *SysUserRoleUpdateOne) SetNillableCreatedBy(v *idgen.ID) *SysUserRoleUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *SysUserRoleUpdateOne) AddCreatedBy(v idgen.ID) *SysUserRoleUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *SysUserRoleUpdateOne) ClearCreatedBy() *SysUserRoleUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *SysUserRoleUpdateOne) SetUpdatedBy(v idgen.ID) *SysUserRoleUpdateOne {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *SysUserRoleUpdateOne) SetNillableUpdatedBy(v *idgen.ID) *SysUserRoleUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *SysUserRoleUpdateOne) AddUpdatedBy(v idgen.ID) *SysUserRoleUpdateOne {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *SysUserRoleUpdateOne) ClearUpdatedBy() *SysUserRoleUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetUser sets the "user" edge to the SysUser entity.
func (_u *SysUserRoleUpdateOne) SetUser(v *SysUser) *SysUserRoleUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetRole sets the "role" edge to the SysRole entity.
func (_u *SysUserRoleUpdateOne) SetRole(v *SysRole) *SysUserRoleUpdateOne {
	return _u.SetRoleID(v.ID)
}

// Mutation returns the SysUserRoleMutation object of the builder.
func (_u *SysUserRoleUpdateOne) Mutation() *SysUserRoleMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the SysUser entity.
func (_u *SysUserRoleUpdateOne) ClearUser() *SysUserRoleUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearRole clears the "role" edge to the SysRole entity.
func (_u *SysUserRoleUpdateOne) ClearRole() *SysUserRoleUpdateOne {
	_u.mutation.ClearRole()
	return _u
}

// Where appends a list predicates to the SysUserRoleUpdate builder.
func (_u *SysUserRoleUpdateOne) Where(ps ...predicate.SysUserRole) *SysUserRoleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SysUserRoleUpdateOne) Select(field string, fields ...string) *SysUserRoleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SysUserRole entity.
func (_u *SysUserRoleUpdateOne) Save(ctx context.Context) (*SysUserRole, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SysUserRoleUpdateOne) SaveX(ctx context.Context) *SysUserRole {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SysUserRoleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SysUserRoleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SysUserRoleUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := sysuserrole.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SysUserRoleUpdateOne) check() error {
	if v, ok := _u.mutation.UserID(); ok {
		if err := sysuserrole.UserIDValidator(int64(v)); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "SysUserRole.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RoleID(); ok {
		if err := sysuserrole.RoleIDValidator(int64(v)); err != nil {
			return &ValidationError{Name: "role_id", err: fmt.Errorf(`ent: validator failed for field "SysUserRole.role_id": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SysUserRole.user"`)
	}
	if _u.mutation.RoleCleared() && len(_u.mutation.RoleIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SysUserRole.role"`)
	}
	return nil
}

func (_u *SysUserRoleUpdateOne) sqlSave(ctx context.Context) (_node *SysUserRole, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sysuserrole.Table, sysuserrole.Columns, sqlgraph.NewFieldSpec(sysuserrole.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SysUserRole.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sysuserrole.FieldID)
		for _, f := range fields {
			if !sysuserrole.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != sysuserrole.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(sysuserrole.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(sysuserrole.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(sysuserrole.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(sysuserrole.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(sysuserrole.FieldCreatedBy, field.TypeInt64, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(sysuserrole.FieldCreatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(sysuserrole.FieldUpdatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(sysuserrole.FieldUpdatedBy, field.TypeInt64, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(sysuserrole.FieldUpdatedBy, field.TypeInt64)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sysuserrole.UserTable,
			Columns: []string{sysuserrole.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sysuser.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sysuserrole.UserTable,
			Columns: []string{sysuserrole.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sysuser.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RoleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sysuserrole.RoleTable,
			Columns: []string{sysuserrole.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sysrole.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sysuserrole.RoleTable,
			Columns: []string{sysuserrole.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sysrole.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SysUserRole{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sysuserrole.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
