// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/teamsillybees/initra/examples/internal/data/ent/sysuser"
	"github.com/teamsillybees/initra/pkg/idgen"
)

// 系统后台用户表，用于后台登录、审计和权限归属。
type SysUser struct {
	config `json:"-"`
	// ID of the ent.
	// 雪花算法生成的主键 ID。
	ID idgen.ID `json:"id,omitempty"`
	// 逻辑删除时间，NULL 表示未删除。
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// 创建时间。
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 最后更新时间。
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 创建人用户 ID。
	CreatedBy *idgen.ID `json:"created_by,omitempty"`
	// 最后更新人用户 ID。
	UpdatedBy *idgen.ID `json:"updated_by,omitempty"`
	// 登录用户名，全局唯一。
	Username string `json:"username,omitempty"`
	// 经过安全哈希后的密码密文。
	PasswordHash string `json:"password_hash,omitempty"`
	// 用户昵称或显示名。
	Nickname *string `json:"nickname,omitempty"`
	// 手机号，可用于登录或通知。
	Phone *string `json:"phone,omitempty"`
	// 邮箱地址，可用于找回密码和通知。
	Email *string `json:"email,omitempty"`
	// 头像资源地址。
	AvatarURL *string `json:"avatar_url,omitempty"`
	// 是否为超级管理员，超级管理员通常拥有全量权限。
	IsSuperAdmin bool `json:"is_super_admin,omitempty"`
	// 账号是否启用。
	IsEnable bool `json:"is_enable,omitempty"`
	// 排序值，便于后台列表定制顺序。
	SortID int `json:"sort_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SysUserQuery when eager-loading is set.
	Edges        SysUserEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SysUserEdges holds the relations/edges for other nodes in the graph.
type SysUserEdges struct {
	// UserRoles holds the value of the user_roles edge.
	UserRoles []*SysUserRole `json:"user_roles,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserRolesOrErr returns the UserRoles value or an error if the edge
// was not loaded in eager-loading.
func (e SysUserEdges) UserRolesOrErr() ([]*SysUserRole, error) {
	if e.loadedTypes[0] {
		return e.UserRoles, nil
	}
	return nil, &NotLoadedError{edge: "user_roles"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SysUser) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case sysuser.FieldIsSuperAdmin, sysuser.FieldIsEnable:
			values[i] = new(sql.NullBool)
		case sysuser.FieldID, sysuser.FieldCreatedBy, sysuser.FieldUpdatedBy, sysuser.FieldSortID:
			values[i] = new(sql.NullInt64)
		case sysuser.FieldUsername, sysuser.FieldPasswordHash, sysuser.FieldNickname, sysuser.FieldPhone, sysuser.FieldEmail, sysuser.FieldAvatarURL:
			values[i] = new(sql.NullString)
		case sysuser.FieldDeletedAt, sysuser.FieldCreatedAt, sysuser.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SysUser fields.
func (_m *SysUser) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case sysuser.FieldID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = idgen.ID(value.Int64)
			}
		case sysuser.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case sysuser.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case sysuser.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case sysuser.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = new(idgen.ID)
				*_m.CreatedBy = idgen.ID(value.Int64)
			}
		case sysuser.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				_m.UpdatedBy = new(idgen.ID)
				*_m.UpdatedBy = idgen.ID(value.Int64)
			}
		case sysuser.FieldUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field username", values[i])
			} else if value.Valid {
				_m.Username = value.String
			}
		case sysuser.FieldPasswordHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field password_hash", values[i])
			} else if value.Valid {
				_m.PasswordHash = value.String
			}
		case sysuser.FieldNickname:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field nickname", values[i])
			} else if value.Valid {
				_m.Nickname = new(string)
				*_m.Nickname = value.String
			}
		case sysuser.FieldPhone:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field phone", values[i])
			} else if value.Valid {
				_m.Phone = new(string)
				*_m.Phone = value.String
			}
		case sysuser.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				_m.Email = new(string)
				*_m.Email = value.String
			}
		case sysuser.FieldAvatarURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field avatar_url", values[i])
			} else if value.Valid {
				_m.AvatarURL = new(string)
				*_m.AvatarURL = value.String
			}
		case sysuser.FieldIsSuperAdmin:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_super_admin", values[i])
			} else if value.Valid {
				_m.IsSuperAdmin = value.Bool
			}
		case sysuser.FieldIsEnable:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_enable", values[i])
			} else if value.Valid {
				_m.IsEnable = value.Bool
			}
		case sysuser.FieldSortID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort_id", values[i])
			} else if value.Valid {
				_m.SortID = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SysUser.
// This includes values selected through modifiers, order, etc.
func (_m *SysUser) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUserRoles queries the "user_roles" edge of the SysUser entity.
func (_m *SysUser) QueryUserRoles() *SysUserRoleQuery {
	return NewSysUserClient(_m.config).QueryUserRoles(_m)
}

// Update returns a builder for updating this SysUser.
// Note that you need to call SysUser.Unwrap() before calling this method if this SysUser
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SysUser) Update() *SysUserUpdateOne {
	return NewSysUserClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SysUser entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SysUser) Unwrap() *SysUser {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SysUser is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SysUser) String() string {
	var builder strings.Builder
	builder.WriteString("SysUser(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.CreatedBy; v != nil {
		builder.WriteString("created_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.UpdatedBy; v != nil {
		builder.WriteString("updated_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("username=")
	builder.WriteString(_m.Username)
	builder.WriteString(", ")
	builder.WriteString("password_hash=")
	builder.WriteString(_m.PasswordHash)
	builder.WriteString(", ")
	if v := _m.Nickname; v != nil {
		builder.WriteString("nickname=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Phone; v != nil {
		builder.WriteString("phone=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Email; v != nil {
		builder.WriteString("email=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.AvatarURL; v != nil {
		builder.WriteString("avatar_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("is_super_admin=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsSuperAdmin))
	builder.WriteString(", ")
	builder.WriteString("is_enable=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsEnable))
	builder.WriteString(", ")
	builder.WriteString("sort_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SortID))
	builder.WriteByte(')')
	return builder.String()
}

// SysUsers is a parsable slice of SysUser.
type SysUsers []*SysUser
