// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/teamsillybees/initra/examples/internal/data/ent/sysuser"
	"github.com/teamsillybees/initra/examples/internal/data/ent/sysuserrole"
	"github.com/teamsillybees/initra/pkg/idgen"
)

// SysUserCreate is the builder for creating a SysUser entity.
type SysUserCreate struct {
	config
	mutation *SysUserMutation
	hooks    []Hook
}

// SetUsername sets the "username" field.
func (_c *SysUserCreate) SetUsername(v string) *SysUserCreate {
	_c.mutation.SetUsername(v)
	return _c
}

// SetPasswordHash sets the "password_hash" field.
func (_c *SysUserCreate) SetPasswordHash(v string) *SysUserCreate {
	_c.mutation.SetPasswordHash(v)
	return _c
}

// SetNickname sets the "nickname" field.
func (_c *SysUserCreate) SetNickname(v string) *SysUserCreate {
	_c.mutation.SetNickname(v)
	return _c
}

// SetNillableNickname sets the "nickname" field if the given value is not nil.
func (_c *SysUserCreate) SetNillableNickname(v *string) *SysUserCreate {
	if v != nil {
		_c.SetNickname(*v)
	}
	return _c
}

// SetPhone sets the "phone" field.
func (_c *SysUserCreate) SetPhone(v string) *SysUserCreate {
	_c.mutation.SetPhone(v)
	return _c
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_c *SysUserCreate) SetNillablePhone(v *string) *SysUserCreate {
	if v != nil {
		_c.SetPhone(*v)
	}
	return _c
}

// SetEmail sets the "email" field.
func (_c *SysUserCreate) SetEmail(v string) *SysUserCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_c *SysUserCreate) SetNillableEmail(v *string) *SysUserCreate {
	if v != nil {
		_c.SetEmail(*v)
	}
	return _c
}

// SetAvatarURL sets the "avatar_url" field.
func (_c *SysUserCreate) SetAvatarURL(v string) *SysUserCreate {
	_c.mutation.SetAvatarURL(v)
	return _c
}

// SetNillableAvatarURL sets the "avatar_url" field if the given value is not nil.
func (_c *SysUserCreate) SetNillableAvatarURL(v *string) *SysUserCreate {
	if v != nil {
		_c.SetAvatarURL(*v)
	}
	return _c
}

// SetIsSuperAdmin sets the "is_super_admin" field.
func (_c *SysUserCreate) SetIsSuperAdmin(v bool) *SysUserCreate {
	_c.mutation.SetIsSuperAdmin(v)
	return _c
}

// SetNillableIsSuperAdmin sets the "is_super_admin" field if the given value is not nil.
func (_c *SysUserCreate) SetNillableIsSuperAdmin(v *bool) *SysUserCreate {
	if v != nil {
		_c.SetIsSuperAdmin(*v)
	}
	return _c
}

// SetIsEnable sets the "is_enable" field.
func (_c *SysUserCreate) SetIsEnable(v bool) *SysUserCreate {
	_c.mutation.SetIsEnable(v)
	return _c
}

// SetNillableIsEnable sets the "is_enable" field if the given value is not nil.
func (_c *SysUserCreate) SetNillableIsEnable(v *bool) *SysUserCreate {
	if v != nil {
		_c.SetIsEnable(*v)
	}
	return _c
}

// SetSortID sets the "sort_id" field.
func (_c *SysUserCreate) SetSortID(v int32) *SysUserCreate {
	_c.mutation.SetSortID(v)
	return _c
}

// SetNillableSortID sets the "sort_id" field if the given value is not nil.
func (_c *SysUserCreate) SetNillableSortID(v *int32) *SysUserCreate {
	if v != nil {
		_c.SetSortID(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *SysUserCreate) SetDeletedAt(v time.Time) *SysUserCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *SysUserCreate) SetNillableDeletedAt(v *time.Time) *SysUserCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SysUserCreate) SetCreatedAt(v time.Time) *SysUserCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SysUserCreate) SetNillableCreatedAt(v *time.Time) *SysUserCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SysUserCreate) SetUpdatedAt(v time.Time) *SysUserCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SysUserCreate) SetNillableUpdatedAt(v *time.Time) *SysUserCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *SysUserCreate) SetCreatedBy(v idgen.ID) *SysUserCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *SysUserCreate) SetNillableCreatedBy(v *idgen.ID) *SysUserCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *SysUserCreate) SetUpdatedBy(v idgen.ID) *SysUserCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *SysUserCreate) SetNillableUpdatedBy(v *idgen.ID) *SysUserCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SysUserCreate) SetID(v idgen.ID) *SysUserCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *SysUserCreate) SetNillableID(v *idgen.ID) *SysUserCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddUserRoleIDs adds the "user_roles" edge to the SysUserRole entity by IDs.
func (_c *SysUserCreate) AddUserRoleIDs(ids ...idgen.ID) *SysUserCreate {
	_c.mutation.AddUserRoleIDs(ids...)
	return _c
}

// AddUserRoles adds the "user_roles" edges to the SysUserRole entity.
func (_c *SysUserCreate) AddUserRoles(v ...*SysUserRole) *SysUserCreate {
	ids := make([]idgen.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddUserRoleIDs(ids...)
}

// Mutation returns the SysUserMutation object of the builder.
func (_c *SysUserCreate) Mutation() *SysUserMutation {
	return _c.mutation
}

// Save creates the SysUser in the database.
func (_c *SysUserCreate) Save(ctx context.Context) (*SysUser, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SysUserCreate) SaveX(ctx context.Context) *SysUser {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SysUserCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SysUserCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SysUserCreate) defaults() {
	if _, ok := _c.mutation.IsSuperAdmin(); !ok {
		v := sysuser.DefaultIsSuperAdmin
		_c.mutation.SetIsSuperAdmin(v)
	}
	if _, ok := _c.mutation.IsEnable(); !ok {
		v := sysuser.DefaultIsEnable
		_c.mutation.SetIsEnable(v)
	}
	if _, ok := _c.mutation.SortID(); !ok {
		v := sysuser.DefaultSortID
		_c.mutation.SetSortID(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := sysuser.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := sysuser.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := sysuser.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SysUserCreate) check() error {
	if _, ok := _c.mutation.Username(); !ok {
		return &ValidationError{Name: "username", err: errors.New(`ent: missing required field "SysUser.username"`)}
	}
	if v, ok := _c.mutation.Username(); ok {
		if err := sysuser.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "SysUser.username": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PasswordHash(); !ok {
		return &ValidationError{Name: "password_hash", err: errors.New(`ent: missing required field "SysUser.password_hash"`)}
	}
	if v, ok := _c.mutation.PasswordHash(); ok {
		if err := sysuser.PasswordHashValidator(v); err != nil {
			return &ValidationError{Name: "password_hash", err: fmt.Errorf(`ent: validator failed for field "SysUser.password_hash": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Nickname(); ok {
		if err := sysuser.NicknameValidator(v); err != nil {
			return &ValidationError{Name: "nickname", err: fmt.Errorf(`ent: validator failed for field "SysUser.nickname": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Phone(); ok {
		if err := sysuser.PhoneValidator(v); err != nil {
			return &ValidationError{Name: "phone", err: fmt.Errorf(`ent: validator failed for field "SysUser.phone": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Email(); ok {
		if err := sysuser.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "SysUser.email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsSuperAdmin(); !ok {
		return &ValidationError{Name: "is_super_admin", err: errors.New(`ent: missing required field "SysUser.is_super_admin"`)}
	}
	if _, ok := _c.mutation.IsEnable(); !ok {
		return &ValidationError{Name: "is_enable", err: errors.New(`ent: missing required field "SysUser.is_enable"`)}
	}
	if _, ok := _c.mutation.SortID(); !ok {
		return &ValidationError{Name: "sort_id", err: errors.New(`ent: missing required field "SysUser.sort_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SysUser.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SysUser.updated_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := sysuser.IDValidator(int64(v)); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "SysUser.id": %w`, err)}
		}
	}
	return nil
}

func (_c *SysUserCreate) sqlSave(ctx context.Context) (*SysUser, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = idgen.ID(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SysUserCreate) createSpec() (*SysUser, *sqlgraph.CreateSpec) {
	var (
		_node = &SysUser{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(sysuser.Table, sqlgraph.NewFieldSpec(sysuser.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Username(); ok {
		_spec.SetField(sysuser.FieldUsername, field.TypeString, value)
		_node.Username = value
	}
	if value, ok := _c.mutation.PasswordHash(); ok {
		_spec.SetField(sysuser.FieldPasswordHash, field.TypeString, value)
		_node.PasswordHash = value
	}
	if value, ok := _c.mutation.Nickname(); ok {
		_spec.SetField(sysuser.FieldNickname, field.TypeString, value)
		_node.Nickname = &value
	}
	if value, ok := _c.mutation.Phone(); ok {
		_spec.SetField(sysuser.FieldPhone, field.TypeString, value)
		_node.Phone = &value
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(sysuser.FieldEmail, field.TypeString, value)
		_node.Email = &value
	}
	if value, ok := _c.mutation.AvatarURL(); ok {
		_spec.SetField(sysuser.FieldAvatarURL, field.TypeString, value)
		_node.AvatarURL = &value
	}
	if value, ok := _c.mutation.IsSuperAdmin(); ok {
		_spec.SetField(sysuser.FieldIsSuperAdmin, field.TypeBool, value)
		_node.IsSuperAdmin = value
	}
	if value, ok := _c.mutation.IsEnable(); ok {
		_spec.SetField(sysuser.FieldIsEnable, field.TypeBool, value)
		_node.IsEnable = value
	}
	if value, ok := _c.mutation.SortID(); ok {
		_spec.SetField(sysuser.FieldSortID, field.TypeInt32, value)
		_node.SortID = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(sysuser.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(sysuser.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(sysuser.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(sysuser.FieldCreatedBy, field.TypeInt64, value)
		_node.CreatedBy = &value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(sysuser.FieldUpdatedBy, field.TypeInt64, value)
		_node.UpdatedBy = &value
	}
	if nodes := _c.mutation.UserRolesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   sysuser.UserRolesTable,
			Columns: []string{sysuser.UserRolesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sysuserrole.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SysUserCreateBulk is the builder for creating many SysUser entities in bulk.
type SysUserCreateBulk struct {
	config
	err      error
	builders []*SysUserCreate
}

// Save creates the SysUser entities in the database.
func (_c *SysUserCreateBulk) Save(ctx context.Context) ([]*SysUser, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SysUser, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SysUserMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = idgen.ID(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SysUserCreateBulk) SaveX(ctx context.Context) []*SysUser {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SysUserCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SysUserCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
